### ISSUE TITLE
Homebrew Installation on Mac OS X

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#109]
Installtion command for Homebrew should be:

```
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"
```

instead of: 

```
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
```

You need to add "/install" at the end.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/109
- Originally Reported By: [Nao Tokui](http://bitbucket.org/naotokui)
- Originally Created At: 2014-01-30T00:49:19.686

**Comment by Hoverbear** [comment]
I think this can be closed!

**Comment by qubitter** [comment]
Does this really matter?

**Comment by ataffanel** [comment]
I guess this is not a problem anymore, lets close it.
