### ISSUE TITLE
Filter input device configurations depending on OS

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#111]
Some input devices doesn't have the same axis IDs across different OSes, like the Playstation 3/4 controllers. Add a field to the input device configuration that specifies which host OS it was configured on and then only show the config when running on this OS.

There's no need to detect versions of the OS, just the type (Win/Linux/OSX).

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/111
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2014-02-04T11:36:11.773

**Comment by ataffanel** [comment]
Since we switched to pysdl2 we have not seen this issue anymore. closing.
