### ISSUE TITLE
Investigate why an error on log config start

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#112]
Sometimes after a log config has been added and started, the Crazyflie will send back an error that the log config was not found. This would trigger a dialog in the UI and was therefore disabled in the 2014.01 release. This needs to be fixed.

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/112
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2014-02-04T11:38:10.955

**Comment by ataffanel** [comment]
Bug not seen recently. Closing.
