### ISSUE TITLE
Fetch all parameter values once before connected callback

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#116]
Currently the TOCs for parameters and log variables are fetched during the connection "setup", before the callback connected is called. Once the connected callback has been called the application will start log configurations and trigger reading of all the parameters once. Since the logging that is started a lot of downlink bandwidth is being used for the data. Due to this the parameter reading will take much longer than needed.

Move the initial fetching of all the parameter values into the connection "setup" and don't trigger the connected callback until all the values have been read.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/116
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2014-02-04T11:45:50.947

**Comment by evoggy** [comment]
This was due to an error in the parameter implementation, not to the logging clogging the link. Fetching the parameters are still done after the connection is "done", but the performance is much better now.

**Comment by hawanna** [comment]
Hello!

 

New message, please read <http://naileseker.com/act.php?jiz>

 

haw@xdstudios.de
