### ISSUE TITLE
Possible bug in x-mode calculation

### ISSUE THREAD

**Issue by alibenpeng** [bitcraze/crazyflie-clients-python#125]
In commander.py, in set_setpoint() it reads:

        if self._x_mode:
            roll = 0.707 * (roll - pitch)
            pitch = 0.707 * (roll + pitch)

The pitch-value is calculated using the already altered roll value. Is this right?

**Comment by evoggy** [comment]
No, this look like a bug.

**Comment by evoggy** [comment]
This was fixed in #171.
