### ISSUE TITLE
Use static code checking

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#13]
To avoid bugs and make the Python code better a static code checking tool should be used. Currently the top candidate is flake8: https://pypi.python.org/pypi/flake8

This issue is for choosing the tool and removing all the errors.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/13
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-02-23T18:58:38.130

**Comment by ataffanel** [comment]
Travis is checking pep8 for each commit.
