### ISSUE TITLE
Parameter tab remains empty after connecting to CF1.0

### ISSUE THREAD

**Issue by cstanke** [bitcraze/crazyflie-clients-python#139]
Hello,

I haven't checked into this too much so I'm not sure where or why but with a Crazyflie 1.0, official firmware, and the latest cfclient (2d2ce86a699788c5a98b6e4b85b260151aeef9b6) no parameters show up on the Parameters tab. I can control CF1.0 OK but I cannot change or view parameters in firmware.

I'm on Mac OS X (10.10) FWIW, but I'm not sure if that has any bearing on this issue

Let me know if there's anything I can dot help track this one down.

**Comment by evoggy** [comment]
Workaround implemented in 927af489b21fccfd87c88f109c6345ecabdbc49a.
