### ISSUE TITLE
Cloader instance has no attribute 'coldboot'`

### ISSUE THREAD

**Issue by rwaldron** [bitcraze/crazyflie-clients-python#145]
Using the latest release of the client, attempting to update a CrazyFlie2. When I click on "Initiate bootloader cold boot", the following error is logged: 

```
/bootloader.py", line 272, in initiateColdBoot
    if self.loader.coldboot():
AttributeError: Cloader instance has no attribute 'coldboot'
```

**Comment by evoggy** [comment]
I can't reproduce this one, is it the 2014.12.1 release? Could you try the latest version from the repo and see if you could reproduce it?

**Comment by evoggy** [comment]
This was tested again with the latest version without being able to reproduce it.
