### ISSUE TITLE
Detect disconnected Crazyflie 2.0 when USB is disconnected

### ISSUE THREAD

**Issue by evoggy** [bitcraze/crazyflie-clients-python#148]
If you connect to the Crazyflie 2.0 via USB (usb://) and disconnect the USB cable then the client doesn't detect the disconnection. The lib should detect the disconnection and signal the client (similar to what happens when too many radio packets are lost).

**Comment by fredg02** [comment]
I guess this also leads to the freeze/crash of the Python client after connect, disconnect, reconnect, that I'm seeing here with the 2014.12.3 release.
