### ISSUE TITLE
Improve filtering for the radio link-quality indicator

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#15]
The filtering in the current implementation of the radio link-quality reporting should be improved so the indicator in the UI will looks a bit smoother.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/15
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-04-08T22:09:38.463

**Comment by evoggy** [comment]
This is replaced with #181 instead.
