### ISSUE TITLE
CRITICAL:cfclient.cfclient:No PyQT4 installation found, exiting!

### ISSUE THREAD

**Issue by raighneweng** [bitcraze/crazyflie-clients-python#151]
when I run in terminal
>“python bin/cfclient” 

it shows：
>CRITICAL:cfclient.cfclient:No PyQT4 installation found, exiting!

**Comment by Hoverbear** [comment]
@raighneweng Please include your operating system and python version! Thanks.

**Comment by evoggy** [comment]
I'm guessing [this tweet](https://twitter.com/RaighneWeng/status/556452112675377152) refers to the same issue. If so then please have a look at the [install instruction](https://github.com/bitcraze/crazyflie-clients-python/blob/master/README.md) for Mac OSX and see if installing the pre-requisites solves the issue.

**Comment by raighneweng** [comment]
I can not understand this step
>
echo 'export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH' >> ~/.bashrc
source ~/.bashrc

Copy & paste it into the terminal window and hit Return?

**Comment by ataffanel** [comment]
@raighneweng can you please precise your operating system, and how are you installing the dependencies (ie. if on a mac with brew or mac ports).

**Comment by raighneweng** [comment]
I run it on osx10.9.5,I just follow the Installation on this page https://github.com/bitcraze/crazyflie-clients-python

**Comment by ataffanel** [comment]
Can you try:
```
/usr/local/bin/python bin/cfclient
```
If it does not work make sure you have installed all prerequisites with brew and pip.

**Comment by raighneweng** [comment]
it shows
>
~ Raighne$ /usr/local/bin/python bin/cfclient
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'bin/cfclient': [Errno 2] No such file or directory
RaighnedeMacBook-Pro:~ Raighne$

**Comment by ataffanel** [comment]
You should run this command while being in the crazyflie-clients-python directory. The same way you did with your original message.

**Comment by raighneweng** [comment]
RaighnedeMacBook-Pro:crazyflie-clients-python Raighne$ /usr/local/bin/python bin/cfclient
CRITICAL:cfclient.cfclient:No pyusb installation found, exiting!
RaighnedeMacBook-Pro:crazyflie-clients-python Raighne$

**Comment by ataffanel** [comment]
Looks like the python dependencies where not installed because you do not have the brew python in your path. You can try to install them with: 
```
/usr/local/bin/pip install --pre pysdl2 pyusb pyqtgraph
```

Then you should be able to run the client with the command I give earlier.

Did you try to copy-paste the two following lines in the terminal?
```
echo 'export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH' >> ~/.bashrc
source ~/.bashrc
```
When I tried with brew on 10.10 the good python was in the path automatically, maybe it is not the case with 10.9

**Comment by raighneweng** [comment]
thank u，u solved my problem，thank u

**Comment by ataffanel** [comment]
Great! I will review the readme to make it more clear.

**Comment by lamiastella** [comment]
I have the same issue. I have OSX Yosemite:
Monas-MacBook-Pro:bin mona$ /usr/local/bin/python cfclient
Info: Using config path:  /Users/mona/iotlab/crazyflie/cfclient-2013.4.2/lib/../conf
Info: sys.path= ['/Users/mona/iotlab/crazyflie/cfclient-2013.4.2/lib', '/Users/mona/iotlab/crazyflie/cfclient-2013.4.2/lib/../conf', '/Users/mona/iotlab/crazyflie/cfclient-2013.4.2/bin', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/psycopg2-2.5.4-py2.7-macosx-10.5-intel.egg', '/Library/Python/2.7/site-packages/Cython-0.19.2-py2.7-macosx-10.9-intel.egg', '/Library/Python/2.7/site-packages/BeautifulSoup-3.2.1-py2.7.egg', '/Library/Python/2.7/site-packages/beautifulsoup4-4.3.2-py2.7.egg', '/Library/Python/2.7/site-packages/config-0.3.9-py2.7.egg', '/Library/Python/2.7/site-packages/requests-2.4.0-py2.7.egg', '/Library/Python/2.7/site-packages/certifi-14.05.14-py2.7.egg', '/Library/Python/2.7/site-packages/Scrapy-0.24.4-py2.7.egg', '/Library/Python/2.7/site-packages/cssselect-0.9.1-py2.7.egg', '/Library/Python/2.7/site-packages/microsofttranslator-0.6-py2.7.egg', '/Library/Python/2.7/site-packages/goslate-1.3.0-py2.7.egg', '/Library/Python/2.7/site-packages/futures-2.2.0-py2.7.egg', '/Library/Python/2.7/site-packages/pip-1.2.1-py2.7.egg', '/usr/local/lib/python2.7/site-packages', '/Users/mona/iotlab/crazyflie/cfclient-2013.4.2/bin', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Users/mona/Library/Python/2.7/lib/python/site-packages', '/usr/local/Cellar/numpy/1.9.2_1/libexec/nose/lib/python2.7/site-packages', '/usr/local/Cellar/protobuf/2.6.1/libexec/lib/python2.7/site-packages', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages', '/Library/Python/2.7/site-packages']
CRITICAL:cfclient.cfclient:No pyusb installation found, exiting!
Monas-MacBook-Pro:bin mona$ /usr/local/bin/pip install --pre pysdl2 pyusb pyqtgraph
Usage: pip install [OPTIONS] PACKAGE_NAMES...
no such option: --pre

**Comment by evoggy** [comment]
@lamiastella this seems like it's an issue with the install, not the actual application. Please drop by our [support forum](https://forum.bitcraze.io/viewforum.php?f=5&sid=46ccd5800967e7b07a0d06a583e0b782) and create a topic there instead.

**Comment by jackantico1** [comment]
I keep getting `CRITICAL:cfclient.gui:No PyQT5 installation found, exiting!`

**Comment by ataffanel** [comment]
@jackantico1 Since this ticket is closed and was for a much older version (using PyQT4), can you please create a new ticket explaining a bit more about your OS and the way you installed the client.
