### ISSUE TITLE
Dangerous initial input values when gamepad is not connected

### ISSUE THREAD

**Issue by fredg02** [bitcraze/crazyflie-clients-python#156]
Cfclient version: 2014.12.3-7-g2e85d27 +
System: linux2
OS: Kubuntu 12.04.5 LTS

Hi,
When I start the cfclient without a PS3 controller connected, the values for thrust, pitch, roll, yaw are set to random numbers. If one connects to the Crazyflie without noticing the initial input values, the Crazyflie goes...well, crazy. ;)
I'd suggest to reset those values during client startup and just to be sure always when you hit the connect/quick connect button.

Regards,

Fred 
![crazyflie_client_startupproblem2](https://cloud.githubusercontent.com/assets/605957/6023132/67b5aeda-abc2-11e4-86e6-8c0d28a6307f.png)

**Comment by evoggy** [comment]
Hi,

Yeah, this is not very good. We have [changed the firmware](https://github.com/bitcraze/crazyflie-firmware/commit/a21fee8ae81d76131169bdc62e7246b4c0ebad44) to work around this but there should also be a change in the client.

**Comment by qubitter** [comment]
I had the same issue.  To fix:

Connect the gamepad BEFORE you connect to the CF.  Otherwise, your CF will go everywhere.  I know this from personal experience.

**Comment by evoggy** [comment]
This seems to be a Linux issue, not an issue in the client. Until the PS button has been pressed the reading from /dev/input/js* will give max negative values. I've also tested this in jstest-gtk and it shows the same. I think that the fix would be to implement #56 which would avoid the issue.
