### ISSUE TITLE
Wrong directory name in setup.py

### ISSUE THREAD

**Issue by tompe17** [bitcraze/crazyflie-clients-python#158]
In setup.py

cfclient.utils.inputdevices

should probably be something else. At least what happened for me was that the install failed and I had to change this to:

cfclient.utils.inputreaders

But it does not fail on all my computers which is strange.

**Comment by mechAndy** [comment]
I found the same issue that you did. To work around it I had to add a little more. I had to add
fclient.utils.inputreaders and cfclient.utils.mux along with cfclient.utils.inputreaders

**Comment by qubitter** [comment]
I have the issue too:  

When installing using setup.py I got this error:

python setup.py install
fatal: Not a git repository (or any of the parent directories): .git
Warning: Version file cannot be written.
running install
running build
running build_py
error: package directory 'lib/cfclient/utils/inputdevices' does not exist

This is very annoying.  I have cfclient.utils.inputreaders and cfclient.utils.inputinterfaces, but no cfclient.utils.inputdevices.  What should I rename and to what?

**Comment by rs1990** [comment]
Any luck solving this ? I tried qubitter's way but it failed again.

maverick@maverick:~/indigo_ws/src/crazyflie-clients-python$ sudo ./setup.sh 
groupadd: group 'plugdev' already exists
running install
running build
running build_py
copying lib/cfclient/version.py -> build/lib.linux-i686-2.7/cfclient
error: package directory 'lib/cfclient/utils/inputdevices' does not exist

**Comment by mechAndy** [comment]
I had to slightly modify my initial parameters in setup.py Lines 59-63:
packages=['cfclient', 'cfclient.ui', 'cfclient.ui.tabs',
                'cfclient.ui.toolboxes', 'cfclient.ui.widgets',
                'cfclient.utils', 'cfclient.ui.dialogs', 'cflib',
                'cflib.bootloader', 'cflib.crazyflie', 'cflib.drivers',
                'cflib.utils', 'cflib.crtp', 'cfclient.utils.mux', 'cfclient.utils.inputreaders','cfclient.utils.mux','cfclient.utils.inputinterfaces'],

I am using the radio-multilink version but I have had to modify my setup.py the same way every time regardless of branch. you can look at it here:
https://github.com/UtahDARCLab/crazyflie-clients-python/blob/radio_multilink/setup.py

**Comment by hawanna** [comment]
Hello!

 

New message, please read <http://sekshikayelerix.net/seen.php?jxiwv>

 

haw@xdstudios.de

**Comment by ataffanel** [comment]
Since this bug was reported, setup.py has been fixed to work both with pip and with py2exe without problem so this has been fixed in the process.
