### ISSUE TITLE
Port callbacks not unregistered on disconnect

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#16]
When disconnecting and reconnecting multiple times it has been observed that some port callbacks that are registered on connect are not unregistered on disconnect. This should be fixed.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/16
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-04-15T09:59:48.475

**Comment by evoggy** [comment]
This has been fixed.
