### ISSUE TITLE
Thrust configuration instructions unclear

### ISSUE THREAD

**Issue by Hoverbear** [bitcraze/crazyflie-clients-python#160]
Host OS and version of OS: OS X Yosemite
Crazyflie/Crazyradio version: Client commit c8bf7fd31a58a2ec23c1ef95a27c3af690f660b9

I've been trying to get the triggers on a PS4 controller to act as thrust input. The instructions are quite unclear.

![screen shot](https://cloud.githubusercontent.com/assets/130903/6427214/b646e698-bf2e-11e4-9368-0bf78dc5456f.png)

Should it be "Center the thrust axis, and then do max thrust"?

**Comment by qubitter** [comment]
Just do it.  Grammar issues are really low priority seeing as there are more important things like bugs

**Comment by hawanna** [comment]
Hello!

 

New message, please read <http://banrangsit.com/business.php?mzqy>

 

haw@xdstudios.de
