### ISSUE TITLE
Improve exception handling in cflib

### ISSUE THREAD

**Issue by bitbrain** [bitcraze/crazyflie-clients-python#163]
I would like to propose to improve exception handling inside the library code. It seems that inner exceptions are not forwarded properly:

``` python
 try:
            self.crazyflie = Crazyflie()
            self.crazyflie.connected.add_callback(self.connectSetupFinished)
            self.crazyflie.connection_failed.add_callback(self.connectionFailure)
            cflib.crtp.init_drivers()
            self.crazyflie.open_link("radio://0/10/250K")
 except Exception:
            print "Exited program." + e
```

When no dongle is installed, an exception is thrown inside. Unfortunately it is not forwarded in the `open_link` method. As a result, the `except` block will never be executed.

_Possible solution_: forward inner exceptions up to the user of the Crazyflie class.

**Comment by evoggy** [comment]
The current API is made to be asynchronous, only using callbacks to report errors. But we've been discussing creating a synchronous API (more like the ZMQ server). This would make it easier to write the scripts like the one above.
