### ISSUE TITLE
Flashing memory does not work

### ISSUE THREAD

**Issue by dbrgn** [bitcraze/crazyflie-clients-python#166]
Flashing the 1-wire memory does not seem to work...

I created this script: https://github.com/dbrgn/crazyflie-clients-python/blob/flash-example/examples/flash-memory.py

It first updates the attributes of the memory instance. Then it sends a write command using `mem.write_data(data_written)`.

If I inspect the memory instance from within the `data_written` callback, the attributes correspond to the new values. But when I disconnect and reconnect, the old values are present again.

What could be the problem here?

**Comment by dbrgn** [comment]
Any news on this? :)

**Comment by ataffanel** [comment]
The one-wire memories are written by the nRF51 and it is hard to implement writing the memories while having the bluetooth enabled so the nRF51 can only write the one wire memories when the bluetooth stack is disabled.

You can flash an nRF51 firmware without bluetooth by running: 
```
crazyflie2-nrf-firmware$ make BLE=0
...
crazyflie2-nrf-firmware$ make BLE=0 cload
...
```

Then flashing the one wire memory should work.

**Comment by dbrgn** [comment]
Thanks, I'll try that!

**Comment by evoggy** [comment]
I'm closing this one since it's not a client issue and referring to https://github.com/bitcraze/crazyflie2-nrf-firmware/issues/3 for the real issue.

**Comment by dbrgn** [comment]
Just for the record, this worked :)
