### ISSUE TITLE
WindowsError when attempting to configure joysticks

### ISSUE THREAD

**Issue by qrohlf** [bitcraze/crazyflie-clients-python#167]
In the client, I am getting WindowsError: Access Violation messages when attempting to configure joystick input mappings. This issue is present on 7c99f7533759899d0b2ff35d841469ec8b360849.

Specifically, going to Input Device > Configure device mapping and hitting the configure button will cause this to occur. I am unable to configure any input mappings due to this issue.

![image](https://cloud.githubusercontent.com/assets/347189/7145173/08f0a8d2-e29f-11e4-9f33-a4af70b0c446.png)

**Comment by zforum69** [comment]
I can confirm the same error and symptoms on 2014.12.1, 2014.12.2 and 2014.12.3.  Had to go back to 2014.01.0 to make the joystick work again.

Z
