### ISSUE TITLE
Altitude hold not working correctly

### ISSUE THREAD

**Issue by evoggy** [bitcraze/crazyflie-clients-python#169]
After the merge of the dev-inputmux branch to develop the alt-hold setpoint is set incorrectly since [has_pressure_sensor](https://github.com/bitcraze/crazyflie-clients-python/commit/dc32835fc3be33219c84d74ea18e047ed01a6d8b#diff-1da3535b033c64e0ba677bb79a05d436R110) is not set. This will cause the hover set-point to slowly go down over time.

**Comment by Hoverbear** [comment]
Has altitude hold been working at all? I've tested it on a number of occasions and it's never seemed to actually be able to maintain atitude.

**Comment by qubitter** [comment]
Yeah, same here.  With mine, no matter the thrust, if I hit the althold button it launches then drifts back to earth
