### ISSUE TITLE
Ushort error

### ISSUE THREAD

**Issue by qubitter** [bitcraze/crazyflie-clients-python#170]
I got the error: Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "tester.py", line 93, in _ramp_motors
    self._cf.commander.send_setpoint(0, 0, 0, 66590)
  File "../lib/cflib/crazyflie/commander.py", line 73, in send_setpoint
    pk.data = struct.pack('<fffH', roll, -pitch, yaw, thrust)
error: ushort format requires 0 <= number <= USHRT_MAX

when running escape.py.  I found that deleting the spaces in between the values in the first commander call fixed it.  This might just be chance, but that needs to be changed.

**Comment by cstanke** [comment]
Spaces between arguments in a Python function call is an issue of coding style, not functionality. I don't believe this is the cause of your problem.

**Comment by cstanke** [comment]
Sorry, I also meant to write that the problem is your argument 66590 exceeds the size of USHRT_MAX which is 65535. Just what the error message "error: ushort format requires 0 <= number <= USHRT_MAX" states. This is not a bug.

**Comment by qubitter** [comment]
oh, thanks

**Comment by evoggy** [comment]
Let's change the error message so it looks less like a bug and more like a input error.
