### ISSUE TITLE
Battery variable

### ISSUE THREAD

**Issue by qubitter** [bitcraze/crazyflie-clients-python#173]
Can you please add a variable to the logging that consists of the current battery level as a percentage?  For me(and I think a lot of other people too), my althold doesn't work and I have to hand-tailor the programs that I write for my cf2 to fly autonomously.  Every time I charge it, I have to change my code which is a hassle.

**Comment by evoggy** [comment]
The firmware has been modified to take the voltage into consideration in https://github.com/bitcraze/crazyflie-firmware/commit/65d1e0dc6493868287d03c6568fc447c8294c4f5. Using this firmware should give you consistency between fully charged battery and nearly depleted battery.
