### ISSUE TITLE
SDK

### ISSUE THREAD

**Issue by kentwills** [bitcraze/crazyflie-clients-python#175]
Would love to support this project, but have found the different setup configs per platform as well as the inability to make a project using just pypi requirements challenging.  I would like to propose a separation of the client and the cflib.  Basically create a package to support running examples and that can be uploaded to the pypi server.  This I believe would become your base driver/SDK python package for crazyflie for which everything else depends on, including the client.  

Some tools we everyday in our shop:
* [pre-commit](https://github.com/pre-commit/pre-commit) to ensure proper linting
* [tox](https://tox.readthedocs.org/en/latest/) to ensure forward compatibility for python versions
* [travis](https://travis-ci.org/) for continuous integration
* [coverage](https://pypi.python.org/pypi/coverage) for ensuring test code coverage
* [pytest](pytest.org) for testing
* Makefile for managing the build process and integration for CI

I could introduce these tools as well as separate out a package that could be built using only pypi dependencies.  Would like to hear your thoughts on whether you would support such an endeavor.

An example start with a working ramp example is at https://github.com/kentwills/crazyflie-clients-python/tree/cflib_packaging

**Comment by ataffanel** [comment]
Really sorry for the late answer. 

We are finally getting there. We now have continuous integration setup and we are going to separate cflib and cfclient in order to push them to pypi. We will track the progress in the ticket #227.
