### ISSUE TITLE
Readme.md Mac Homebrew section should include pygame

### ISSUE THREAD

**Issue by adjavaherian** [bitcraze/crazyflie-clients-python#176]
The stock instructions seem fine, but I had to install pygame from this bitbucket

`pip install hg+http://bitbucket.org/pygame/pygame`

See https://bitbucket.org/pygame/pygame/issue/82/homebrew-on-leopard-fails-to-install#comment-627494  

After installing this, client runs fine!

**Comment by ataffanel** [comment]
Pygame is not used anymore and the mac section of the readme is now tested more often and believed to be updated.
