### ISSUE TITLE
Cannot catkin_make on indigo

### ISSUE THREAD

**Issue by rs1990** [bitcraze/crazyflie-clients-python#179]
Hello,

I tried to catkin_make this on Indigo but i get the following error : 

maverick@maverick:~/indigo_ws$ catkin_make
Base path: /home/maverick/indigo_ws
Source space: /home/maverick/indigo_ws/src
Build space: /home/maverick/indigo_ws/build
Devel space: /home/maverick/indigo_ws/devel
Install space: /home/maverick/indigo_ws/install
WARNING: Package "cfclient" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
#### 
#### 

-- Using CATKIN_DEVEL_PREFIX: /home/maverick/indigo_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/maverick/indigo_ws/devel;/opt/ros/indigo
-- This workspace overlays: /home/maverick/indigo_ws/devel;/opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/maverick/indigo_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.14
-- BUILD_SHARED_LIBS is on
WARNING: Package "cfclient" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
WARNING: Package "cfclient" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 2 packages in topological order:
-- ~~  - cfclient
-- ~~  - ardrone_autonomy
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'cfclient'
-- ==> add_subdirectory(crazyflie-clients-python)
WARNING: Package "cfclient" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
Warning: Version file cannot be written.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_python_setup.cmake:79 (message):
  catkin_python_setup() version in setup.py (2014.12.3-74-g3a65a5c) differs
  from version in package.xml (2014.04.9001)
Call Stack (most recent call first):
  crazyflie-clients-python/CMakeLists.txt:5 (catkin_python_setup)

-- Configuring incomplete, errors occurred!
See also "/home/maverick/indigo_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/maverick/indigo_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

and solution?.
i need to run this on ubuntu 14.04

**Comment by evoggy** [comment]
Hi,

What branch/version of the client are you trying to build?

**Comment by ataffanel** [comment]
This is very old so I close it. Feel free to re-open if there is any news.
