### ISSUE TITLE
Use RSSI measurement for the link quality indicator

### ISSUE THREAD

**Issue by evoggy** [bitcraze/crazyflie-clients-python#181]
For the Crazyflie 2.0 an RSSI measurement for the radio link is available. This value should be used to indicate the link quality in the UI instead of the dropped packets measurements we use now.

Currently this is implemented using logging but in the future this could also be implemented in the radio driver using https://github.com/bitcraze/crazyflie2-nrf-firmware/issues/6

**Comment by jonasdn** [comment]
Is this still relevant, @evoggy ?

**Comment by evoggy** [comment]
The RSSI is not a good way to do this so let's keep it as is and close this.
