### ISSUE TITLE
Syntax Error using setup_linux.sh

### ISSUE THREAD

**Issue by 4estlaine** [bitcraze/crazyflie-clients-python#208]
byte-compiling /usr/local/lib/python3.4/dist-packages/cfclient/version.py to version.cpython-34.pyc
  File "/usr/local/lib/python3.4/dist-packages/cfclient/version.py", line 1
    VERSION='b'2015.08-66-g1854385''
                     ^
SyntaxError: invalid syntax

I obtain the following error when I run setup.py using python3. When I run setup.py using python2.7 I get a different syntax error. Any pointers how to fix this?

**Comment by evoggy** [comment]
This fixes the issue for me. Could you try to pull the latest changes and test?
