### ISSUE TITLE
segfault when starting client

### ISSUE THREAD

**Issue by Franky333** [bitcraze/crazyflie-clients-python#211]
The client crashes with a segfault shortly after being started. Tested on Ubuntu 14.04. The pre-Python3 versions of the client work fine. Removing the UsbDriver solves the segfault on startup but it still segfaults when trying to scan for a CFN. Connecting to a cfn works fine.
More info here:  https://forum.bitcraze.io/viewtopic.php?f=5&t=1683

**Comment by ataffanel** [comment]
Solved on the forum so I close it here :).
