### ISSUE TITLE
UI doesn't get feedback 

### ISSUE THREAD

**Issue by infusion** [bitcraze/crazyflie-clients-python#212]
Hi,

when I bought crazyflie1.0 back then from seeedstudio, I had trouble to make it work as it always drifted away and did not have a stable position in air. Yes, I double checked the correct soldering and the props are rotating in the right direction.

I still can't manage to fly it as in your presentation videos, but I now have minor problems. I still can control the thrust via my Macbook and a PS3 controller, but don't get a feedback of the thrust of every individual motor and the sensors anymore. 

What I also see running over the screen is this debug message:
INFO:cflib.crazyflie:Resending for pattern (76, 1)

Is this a bug? A firmware problem? Or another problem which is known?

Thanks!

**Comment by ataffanel** [comment]
Are you running the latest version of the firmware and client? If the two does not match we have seen this kind of problems.

As for the drift can you post a message in the forum (http://forum.bitcraze.se)?

**Comment by infusion** [comment]
I run the latest version of the client, but the firmware is the original. This might be the problem. According to https://wiki.bitcraze.io/doc:crazyflie:client:pycfclient:index#bootloader the step "For Crazyflie 1.0 now power it on within 5 seconds using the battery (not USB), the booloader should now connect" doesn't work. Should I use an older version of the client?

Otherwise thanks! I'll try my luck in the forum.

**Comment by ataffanel** [comment]
This is the issue then, you should update the Crazyflie. It is not normal that it does not bootload but this is another problem. Hence I can close this ticket.
