### ISSUE TITLE
Unable to use Crazyradio PA with Python Client on Ubuntu 14.04

### ISSUE THREAD

**Issue by troiwilliams** [bitcraze/crazyflie-clients-python#214]
**Issue:**
The Python client does not recognize (or probably detect) the Crazyradio PA interface upon starting the client and clicking the scan button. I ran the client as a regular user and as root, but I get the same results. I am not using the Bitcraze VM because it is unable to detect the Crazyflie 2.0 connection via USB nor the radio dongle.

**Output on the terminal:**
INFO:cfclient.utils.zmq_param:Biding ZMQ for parameters at tcp://*:1213
INFO:cfclient.utils.zmq_led_driver:Biding ZMQ for LED driverat tcp://*:1214
INFO:cfclient.utils.input:Using device blacklist [(VirtualBox|VMware)]
INFO:cflib.crtp.radiodriver:v0.53 dongle with serial N/A found
WARNING:cfclient.ui.tabs.GpsTab:GPS tab not enabled since no Pythonbindings for Marble was found
INFO:cfclient.utils.input:Selected MUX: Normal
INFO:cfclient.ui.main:Role of USB Joystick      USB Joystick is Device
INFO:cfclient.utils.input.mux:Adding device USB Joystick      USB Joystick to MUX Normal
INFO:cflib.drivers.cfusb:Looking for devices....
INFO:cflib.crtp.radiodriver:v0.53 dongle with serial N/A found
INFO:cflib.drivers.cfusb:Looking for devices....

**Client versions:**
I have used the latest Python clients from the GitHub repository (both Crazyflie PC client 2015.09 release [release: 2015.09; commit: 7080441] and the zipped download from the "develop" branch [commit: 46cb04a]).

**Dongle version:**
Crazyradio PA ver. 0.53 (successfully flashed via the usbtools scripts).

**Comment by ataffanel** [comment]
Can you copy-paste the content of help/about/debug? From the output it seems that the radio dongle is correctly detected.

**Comment by troiwilliams** [comment]
I also tested the dongle in Mac OS X El Capitan and in the Bitcraze VM on the same Mac OS system. I got the same result in Mac OS as I did in Ubuntu 14.04. That is, the output in the terminal prints the following whenever I click scan:
INFO:cflib.crtp.radiodriver:v0.53 dongle with serial N/A found
INFO:cflib.drivers.cfusb:Looking for devices....

However, the radio interface does not appear as an option in the "Select an interface" drop down menu in the Python client.

On the other hand, I did have better results with the Bitcraze VM in Mac OS. Virtualbox detected the USB dongle, but it too printed out the same information to the terminal: it found the dongle and it is looking for devices. But the VM does not provide a radio option connect to the Crazyflie.

I also changed the communication channel and the data rate for the Crazyflie in the VM (on Mac OS) and in Mac OS itself. But still nothing.

Below has the debug information from Mac OS El Capitan, Ubuntu 14.04 LTS, and the Bitcraze VM on Mac OS. The only differences among the systems are in the output for "Cfclient" and "Input readers", which I specify.

**Cfclient** (*on Mac OS X El Capitan*)
Cfclient version: dev+
System: darwin
Python: 3.5.0

**Cfclient** (*on Ubuntu 14.04 LTS*)
Cfclient version: dev+
System: linux
Python: 3.4.3

**Cfclient** (*on Bitcraze VM*)
Cfclient version: 2015.08
System: linux2

**Interface status**
UsbCdc: No information available
radio: Crazyradio version 0.53
serial: None
udp: None

**Input readers** (*on Mac OS X El Capitan*)
PySDL2 (0 devices connected)

**Input readers** (*on Ubuntu 14.04 LTS*)
linuxjsdev (0 devices connected)

**Input readers** (*on Bitcraze VM*)
linuxjsdev (2 devices connected)

**Input devices**
None

**Crazyflie**
Connected: None
Firmware: None
**Sensors found**
**Sensors tests**

**Comment by ataffanel** [comment]
There seems to be no problem with the USB connection of the client, your client is connected to a Crazyradio. Maybe there is a problem with the Crazyradio itself.

When you click on the "Scan" button do you  see the LEDs blinking on the Crazyradio? It should blink red mostly with a bit of Green if a Crazyflie is detected. Then the dorpdown should show something like "radio://0/80/250k"

**Comment by troiwilliams** [comment]
So, initially when I received the dongle I think it had version 0.51. When I plugged the dongle into the USB port, the green LED lit up for approximately one second then turned off. And whenever I scanned for the Crazyflie via the PC client the red LED continually flashed until the client's scan failed to detect the Crazyflie. The green LED never blinked during the scan.

However, with version 0.53 the dongle's green LED remains on when it's plugged into the USB port. And when I scan for the Crazyflie, I can see the red LED blinking if I am a few centimeters away from the dongle; the red LED's brightness is dominated by the green LED so it is barely noticeable. Should the green LED remain on once it's plugged in? I assume not if you are saying that the green LED should blink a bit if a Crazyflie is detected.

Also, no the radio interface has never shown up during any of the scans that I did (for neither dongle versions).

**Comment by troiwilliams** [comment]
Does anyone have any additional suggestions? I tried the installation and setup instructions on the wiki, but those were not successful. I have also looked at other forum posts, but those were not useful either.

**Comment by fredg02** [comment]
Did you try it on another machine (preferably not a Mac), or with one of the mobile clients? Can you connect to the Crazyflie 2.0 via Bluetooth on a mobile device?

**Comment by evoggy** [comment]
It looks as if you find the dongle correctly since it's printed in the console:
```INFO:cflib.crtp.radiodriver:v0.53 dongle with serial N/A found```

Here's what's supposed to happen, let me know at what step there's an issue:
1. Plug the Crazyradio in the computer, the two LEDs will light up quickly and then they will go off again
2. Start your Crazyflie 2.0, check that the LEDs blink according to [this](https://vine.co/v/OgzwVPTpnHl)
3. Start the client and press the *Connect* button, then press *Scan*. Now the red LED on the Crazyradio will blink really fast (it looks like it's lit) and at one point the green LED should blink
4. You should now get a list of links, where there should be one entry saying something like ```radio://0/10/250K```

You said that you were able to change the address of your Crazyflie 2.0, so you can connect the bootloader?

**Comment by troiwilliams** [comment]
When I plug the dongle into the computer, the green light remains on. I don't know if the red light blinks as well since the intensity of the green LED is much higher than the red LED.

The start-up light sequence for the Crazyflie is normal; I verified it via the tutorial, so I know the Crazyflie works. I've also flown the Crazyflie using the Android app as well.

Whenever I press the scan button on the console, I can see the red LED blinking rapidly if I am a few inches away from the dongle. But the green LED never comes off; from the time the dongle is plugged in, the green LED remains on.

And I have never seen the "radio" interface in the dropdown menu. This is also true for firmware 0.51.

I am also not able to access the Crazyflie 2.0 bootloader. I am only connect to the Crazyflie via USB.

**Comment by ataffanel** [comment]
This looks like a Hardware problem with your Crazyradio. Can you send a mail to the Bitcraze contact email about it, we can handle it from there.

As far as I see this is not a software problem so I close the issue.

**Comment by nurp** [comment]
I have the same problem.
I did the steps 1,2,3 but "connect" button is disabled.
this is the console output:

`VirtualBox:~/projects/crazyflie-clients-python/bin$ ./cfclient 
INFO:cfclient.cfclient:Disabling STL printouts
INFO:cfclient.utils.input.inputreaders:Found readers: ['pysdl2', 'linuxjsdev']
INFO:cfclient.utils.input.inputreaders:Could not initialize [pysdl2]: No SDL2 support on Linux
INFO:cfclient.utils.input.inputreaders:Successfully initialized [linuxjsdev]
INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['leapmotion', 'wiimote', 'zmqpull']
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk.Leap')
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid'
INFO:cfclient.utils.config:Dist config read from /home/nurp/projects/crazyflie-clients-python/src/cfclient/configs/config.json
INFO:cfclient.utils.config:Config file read from [/home/nurp/projects/crazyflie-clients-python/src/../conf/config.json]
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: ZMQ input disabled in config file
INFO:cfclient.utils.zmq_param:Biding ZMQ for parameters at tcp://*:1213
INFO:cfclient.utils.zmq_led_driver:Biding ZMQ for LED driverat tcp://*:1214
INFO:cfclient.utils.input:Using device blacklist [(VirtualBox|VMware)]
INFO:cflib.drivers.cfusb:Looking for devices....
`

**Comment by ataffanel** [comment]
Do you see the dongle with lsusb?

**Comment by hualiu01** [comment]
I had the same issue. But it turned out that I forgot to turn on the drone...So please try to turn on the drone.
