### ISSUE TITLE
WARNING:cflib.crtp.usbdriver:Exception while scanning for Crazyflie USB: [Errno 13] Access denied (insufficient permissions)

### ISSUE THREAD

**Issue by mittenchops** [bitcraze/crazyflie-clients-python#216]
I'm on Ubuntu 14.04, and installed the python3 dependencies enough that I can run the client successfully in a venv.

I see that there's [a section](https://github.com/bitcraze/crazyflie-clients-python/blob/develop/README.md#setting-udev-permissions) on setting udev permissions for radio.  I'm not using the radio, just trying to have my crazyflie 2.0 attached by USB to read the sensors to get started, understand logging, etc.

```
/crazyflie-clients-python$ python3 bin/cfclient
INFO:cfclient.cfclient:Disabling STL printouts
INFO:cfclient.utils.input.inputreaders:Found readers: ['linuxjsdev', 'pysdl2']
INFO:cfclient.utils.input.inputreaders:Successfully initialized [linuxjsdev]
INFO:cfclient.utils.input.inputreaders:Could not initialize [pysdl2]: No SDL2 support on Linux
INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['zmqpull', 'wiimote', 'leapmotion']
INFO:cfclient.utils.config:Dist config read from /home/USER/crazyflie-clients-python/lib/cfclient/configs/config.json
INFO:cfclient.utils.config:Config file read from [/home/USER/crazyflie-clients-python/lib/../conf/config.json]
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: ZMQ input disabled in config file
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid'
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk.Leap')
INFO:cfclient.utils.zmq_param:Biding ZMQ for parameters at tcp://*:1213
INFO:cfclient.utils.zmq_led_driver:Biding ZMQ for LED driverat tcp://*:1214
INFO:cfclient.utils.input:Using device blacklist [(VirtualBox|VMware)]
INFO:cflib.drivers.cfusb:Looking for devices....
WARNING:cflib.crtp.usbdriver:Exception while scanning for Crazyflie USB: [Errno 13] Access denied (insufficient permissions)
WARNING:cfclient.ui.tabs.GpsTab:GPS tab not enabled since no Pythonbindings for Marble was found
INFO:cflib.drivers.cfusb:Looking for devices....
WARNING:cflib.crtp.usbdriver:Exception while scanning for Crazyflie USB: [Errno 13] Access denied (insufficient permissions)
INFO:cflib.drivers.cfusb:Looking for devices....
```

How should I allow the client access to my usb without launching the client in sudo?  But giving it sufficient permissions to avoid:

```
WARNING:cflib.crtp.usbdriver:Exception while scanning for Crazyflie USB: [Errno 13] Access denied (insufficient permissions)
```

Looks like a very cool piece of flying machine, excited to contribute!

**Comment by ataffanel** [comment]
Thanks for the report, you need to create a Udev rules file for the Crazyflie as well. I updated the readme.

Please tell me if it works and we can close this ticket.

**Comment by mittenchops** [comment]
I don't understand udev rules even after some googling, but it looked like my installation did automatically generate `/etc/udev/rules.d/99-crazyradio.rules`

With the following:

```
SUBSYSTEM=="usb", ATTRS{idVendor}=="1915", ATTRS{idProduct}=="7777", MODE="0664", GROUP="plugdev"
```

Should I overwrite

```
SUBSYSTEM=="usb", ATTRS{idVendor}=="1915", ATTRS{idProduct}=="7777", MODE="0664", GROUP="plugdev"
```

With the one you suggested?

```
SUBSYSTEM=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="5740", MODE="0664", GROUP="plugdev"
```

Should the latter have come with the installation?  Should I append it to the file?  (Also, my user is a member of the plugdev group, so I assume my issue remains because of not having the correct ATTRS numbers)

**Comment by ataffanel** [comment]
You should create a new rule file with the last line you copied. The reason is that the Crazyflie has a different VID/PID than the Crazyradio so it requires its own rule.

What installation? Do you mean setup_linux.sh?

**Comment by mittenchops** [comment]
Thanks!
