### ISSUE TITLE
Communication via ZMQ

### ISSUE THREAD

**Issue by mittenchops** [bitcraze/crazyflie-clients-python#218]
I checked the [wiki documentation here](https://wiki.bitcraze.io/doc:crazyflie:client:pycfclient:zmq#input_device) on ZMQ and the [code example](https://github.com/bitcraze/crazyflie-clients-python/blob/develop/examples/zmqclientinput.py) here, and have not had success sending commands to my crazyflie2.0.

```
import zmq
import logging

logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
logging.propagate = True

msg = {
    "version": 1,
    "client_name": "ZMQ client",
    "ctrl": {
        "roll": 0.0,
        "pitch": 0.0,
        "yaw": 0.0,
        "thrust": 0.1
    }
}

PORT = 1212

# FROM WIKI
# context = zmq.Context()
# socket = context.socket(zmq.PUSH)
# socket.connect("tcp://127.0.0.1:{}".format(PORT))

# socket.send_json(msg)

# FROM EXAMPLES
context = zmq.Context()
sender = context.socket(zmq.PUSH)
bind_addr = "tcp://127.0.0.1:{}".format(1024 + 188) # why is this written this way instead of 1212?
sender.connect(bind_addr)

sender.send_json(msg)
```

I tried varying the thrust value, didn't see any changes.  No response from the socket on recv() calls and no action from the robot.  

My questions:

1. How can I communicate via ZMQ in python?
2. What's the best way to debug this, or to get access to a verbose mode?  I am seeing nothing in my logs either on the python client or in the python script I'm trying to run to send messages.

**Comment by ataffanel** [comment]
For ZMQ input to work you should run the client and configure it with ZMQ as input device. Is it configured that way and is it running on the same machine as the python script?

**Comment by ataffanel** [comment]
Closing for now, feel free to reopen if you have more questions.

**Comment by chitrang6** [comment]
I have a question regarding this. I am doing my project on Crazyflie 2.0 My problem is I want to enable ZMQ service. But in the python-cfclient-lib, I am not able to find the cons/conf.jason file. Can you help me here. 

Thank you.

**Comment by ataffanel** [comment]
Answered in your issue #240. Please do not double post (making a new issue was the best there :-)
