### ISSUE TITLE
Disable option to set channel to 127 - crazyflie 2.0

### ISSUE THREAD

**Issue by Venris** [bitcraze/crazyflie-clients-python#223]
Hello, there should not be an option to set channel higher than 125 which is the highest available according to your's wiki. Furthermore in application I can choose channels 126 and 127 and set them to crazyflie 2.0 and after reboot  crazyflie works fine but cannot be found or connected by using crazyradio. How it is possible to change it back to normal channel?

**Comment by Venris** [comment]
I manged to change back radio channel but still there should not be an option to mess this.

**Comment by ataffanel** [comment]
Thanks for the report, this needs to be fixed

**Comment by krichardsson** [comment]
Fixed in #424
