### ISSUE TITLE
can't get the installer to work...

### ISSUE THREAD

**Issue by melzinga** [bitcraze/crazyflie-clients-python#226]
C:\Downloads\crazy.new\crazyflie-clients-python>\Python34\python.exe -m pip install pyusb==1.0.0b2 pyzmq pysdl2 pyqtgraph
Requirement already satisfied (use --upgrade to upgrade): pyusb==1.0.0b2 in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): pyzmq in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): pysdl2 in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): pyqtgraph in c:\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\python34\lib\site-packages (from pyqtgraph)

C:\Downloads\crazy.new\crazyflie-clients-python>\Python34\python bin\cfclient
CRITICAL:cfclient.cfclient:No pysdl2 installation found, exiting!

using win10, 64bit

my crazyflie 2.0 is new and is failing with 5 red flashes immediately and i would like to see if i can determine why but i also can't get the cfclient installed...

is there a PATH variable that I have't defined somewhere?

thanks in advance,

me

**Comment by ataffanel** [comment]
To run from source you need to have the SDL2.dll (from https://www.libsdl.org/download-2.0.php). It should work putting it in the crazyflie-clients-python project root directory.

Otherwise you can try running an old version of the windows installer or running from within the virtual machine (the virtual machine is, unfortunately, the only supported way to run the client until we fix the windows build).

**Comment by melzinga** [comment]
I have the dll in the correct directory.  I did not know there was a vm.
Where is that supported version?

**Comment by ataffanel** [comment]
It is strange that it is not working with the dll. We are currently cleaning up the client state (among other things the windows build), so I will be able to help more at the end of the week for Windows.

The VM download link and usage is documented on the Bitcraze website: https://www.bitcraze.io/getting-started-with-the-crazyflie-2-0/#inst-comp

**Comment by melzinga** [comment]
Thanks. I'll try that for now. But I would like to try to get the client to
load natively.  I look forward to further updates.

**Comment by melzinga** [comment]
Do I need to be in that directory when I call setup.py?

**Comment by ataffanel** [comment]
The setup.py is currently broken. To run from source you should just need to run ```python bin/cfclient``` or, on windows, ```\python34\python.exe bin\cfclient```

**Comment by melzinga** [comment]
Ok. I tried that too.  That's the screen shot.

**Comment by melzinga** [comment]
Ok, now I have the VM installed but I'm not clear on what to do next.  How
do I troubleshoot this device?

**Comment by melzinga** [comment]
---

SYS: Crazyflie is up and running!

SYS: Build 164:0dbbb77772a9 (production1.1) CLEAN

SYS: I am 0x313238323133470D310027 and I have 1024KB of flash!

I2CDEV: Error callback nr: 1024

IMU: MPU9250 I2C connection [FAIL].

I2CDEV: Error callback nr: 1024

I2CDEV: Error callback nr: 1024

I2CDEV: Error callback nr: 1024

I2CDEV: Error callback nr: 1024

I2CDEV: Error callback nr: 1024

I2CDEV: Error callback nr: 1024

I2CDEV: Error callback nr: 1024

I2CDEV: Error callback nr: 1024

I2CDEV: Error callback nr: 1024

IMU: AK8963 I2C connection [FAIL].

I2CDEV: Error callback nr: 1024

IMU: LPS25H I2C connection [FAIL].

EXPBRD: Found 0 memories.

EEPROM: I2C connection [OK].

OW: Found 0.

30 78 42 43 0 50 0 0 0 0 0 0 0 0 0 7D

Status 0

**Comment by melzinga** [comment]
It also won't let me update the firmware on the device as there is no
crazyradio dongle attached.  I don't plan on using a crazryradio, so is
there some way to bypass this?

**Comment by ataffanel** [comment]
This looks like a hardware problem on the Crazyflie side, can you please drop an about it email at contact@bitcraze.se, we can handle it from there.

As for the update, currently the only way to upgrade without Crazyradio is to use the iPhone app. The Android app does not support update by bluetooth yet but it is work in progress.

**Comment by ataffanel** [comment]
I just updated the README in 10454d0f9 with a tested procedure for windows, this includes a script that downloads and puts SDL2.dll in the right place. This closes the Windows part of this ticket.

**Comment by orgr** [comment]
I have SDL2 in place manually and also with prep_windows script and kept getting
`CRITICAL:cfclient.gui:No pysdl2 installation found, exiting!`

 so i forced import sdl2 inside src\cfclient\gui.py and got this
`ImportError: found ['...src\\cfclient\\third_party\\SDL2.dll'], but it's not usable for the library SDL2`

**Comment by ataffanel** [comment]
Are you sure you are running Python 32-bit?

**Comment by orgr** [comment]
Good point, will try with 32-bit in a moment

**Comment by melzinga** [comment]
I sent the email 2 days ago and still haven't heard back.  What's the ETA
on the response?

**Comment by ataffanel** [comment]
> I sent the email 2 days ago and still haven't heard back.  What's the ETA
on the response?

It is now handled, sorry about that I had been tricked by the gmail conversation threads.
