### ISSUE TITLE
Cannot run cfclient from develop branch, encoding fails

### ISSUE THREAD

**Issue by krystian-wojtas** [bitcraze/crazyflie-clients-python#238]
I cannot run cfclient from develop branch. After applying some dirty hacks https://github.com/bitcraze/crazyflie-clients-python/issues/237, I've got

$ ./bin/cfclient 
INFO:cfclient.gui:Disabling STL printouts
INFO:cfclient.utils.input.inputreaders:Found readers: ['pysdl2', 'linuxjsdev']
INFO:cfclient.utils.input.inputreaders:Could not initialize [pysdl2]: No SDL2 support on Linux
INFO:cfclient.utils.input.inputreaders:Successfully initialized [linuxjsdev]
INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['wiimote', 'leapmotion', 'zmqpull']
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid'
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk')
INFO:cfclient.utils.config:Dist config read from /usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/configs/config.json
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: ZMQ input disabled in config file
INFO:cfclient.utils.zmq_param:Biding ZMQ for parameters at tcp://*:1213
INFO:cfclient.utils.zmq_led_driver:Biding ZMQ for LED driverat tcp://*:1214
INFO:cfclient.utils.input:Using device blacklist [(VirtualBox|VMware)]
INFO:cflib.crtp.radiodriver:v0.52 dongle with serial N/A found
===== 2016.03.08 11:03:34 =====
Traceback (most recent call last):
  File "./bin/cfclient", line 5, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/gui.py", line 152, in main
    main_window = MainUI()
  File "/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/ui/main.py", line 290, in __init__
    self._about_dialog = AboutDialog(cfclient.ui.pluginhelper)
  File "/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/ui/dialogs/about.py", line 131, in __init__
    for line in f:
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 325: ordinal not in range(128)

It looks like well-know error made in python
http://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

**Comment by ataffanel** [comment]
Yes it looks like there should be some unicode encoding around this line: https://github.com/bitcraze/crazyflie-clients-python/blob/develop/src/cfclient/ui/dialogs/about.py#L130

**Comment by krystian-wojtas** [comment]
If I uncomment lines 129-134 in this file you mentioned, then it works.

It's strange because I could run master branch without this issue previously. Now I have this issue even on master branch. I didn't change sources of master.

**Comment by ataffanel** [comment]
This is a classical problem with Python 3 and as far as I understand it is also platform specific. When reading text it is very important to explicitly "decode" from, in that case, UTF8.

**Comment by evoggy** [comment]
Could you try to change [this line](https://github.com/bitcraze/crazyflie-clients-python/blob/develop/src/cfclient/ui/dialogs/about.py#L130) (the one Arnaud mentioned) and see if it works?

From:
```with open("CREDITS.txt", 'r') as f:```
To:
```with open("CREDITS.txt", encoding='utf-8', mode='r') as f:```
