### ISSUE TITLE
Crazyflie ZMQ issue

### ISSUE THREAD

**Issue by chitrang6** [bitcraze/crazyflie-clients-python#240]
I have a question regarding this. I am doing my project on Crazyflie 2.0 My problem is I want to enable ZMQ service. But in the python-cfclient-lib, I am not able to find the cons/conf.jason file. Can you help me here.

Thank you.

**Comment by ataffanel** [comment]
You can find the folder where this file is written in the menu "settings/open config folder". Close the client before editing the file (the client write-back the config file when closed).

**Comment by ataffanel** [comment]
I assume this is solved. Feel free to re-open if not.
