### ISSUE TITLE
Add a dead zone configuration for controllers

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-clients-python#245]
Some joysticks/controllers have noise in the values which might cause drift over time. One solution would be to add a dead zone in which the input is ignored.

Preferably the zone should be configurable.

Related to #47

**Comment by tlwmdbt** [comment]
In Windows 7 the standard Joystick helper programs deadzone configuration is over ruled by the Crazyflie client. I have heavy noise on my new Joystick and my Xbox Controller is unusable. I cannot start the Crazyflie without drivting heavily to the noise side. A deadzone control would really be appreciated. It's not just an overtime effect for me. I cannot use it like this.

**Comment by Mitteau** [comment]
Yes, very useful because the precision of a joystick is highly variable, around null position. Very easy to implement.

**Comment by Mitteau** [comment]
I am testing the implementation, see my branch "nexon" from a fork of python client. My repo is Mitteau/... Do I ask for a request to pull? I use also an xbxo360 controller. My dead zone is +- 0.08. A dead band is very confortable for stationnary flight and progressive take off.

**Comment by Mitteau** [comment]
Bug if there is no input map...

**Comment by Mitteau** [comment]
Looks OK now...

**Comment by Mitteau** [comment]
Pull request proposed.

**Comment by krichardsson** [comment]
Implemented in #332
