### ISSUE TITLE
UI freezes when WebView is updated on GPS tab

### ISSUE THREAD

**Issue by evoggy** [bitcraze/crazyflie-clients-python#248]
Host OS and version of OS: All
Crazyflie/Crazyradio version: All
Python version: 3.4.3

The UI freezes shortly when the WebView on the GPS tab is updated.

**Reproduce**
- Connect a Crazyflie or Crazyflie 2.0 with a GPS
- Make sure that long/lat is updated (normally this needs a lock)
- Each updated (1Hz) the UI will freeze shortly (for ~200ms)

**Comment by ataffanel** [comment]
The fix seems to induce a bug in the gps tab update: https://forum.bitcraze.io/viewtopic.php?f=5&t=2033&p=10337#p10337

**Comment by ataffanel** [comment]
The GPS tab is disable so this is not a problem anymore.
