### ISSUE TITLE
Automatically select CF in drop down after scan

### ISSUE THREAD

**Issue by fredg02** [bitcraze/crazyflie-clients-python#249]
When only one Crazyflie is found during a scan (initiated either by a user clicking on the "Scan" button or automatically after the client is started), it should be pre-selected in the "Select an interface" drop down menu. Then the user only has to click on the "Connect" button, instead of clicking on the drop down menu and selecting the interface manually first.
If there is more than one Crazyflie, pre-selecting a CF does not make much sense.

**Comment by evoggy** [comment]
The new behaviour is:
- If the last Crazyflie you connected to is found this is pre-selected
- If no pre-selected Crazyflie is found (or there was none set) then
  - If only one Crazyflie is found this is selected
  - If multiple Crazyflies are found then none is selected

**Comment by fredg02** [comment]
Thanks Marcus. Works great!
