### ISSUE TITLE
No Input-device found on Windows 10 x64  with 2016.4

### ISSUE THREAD

**Issue by jzoss** [bitcraze/crazyflie-clients-python#257]
Using  2016.4 the client is not able to find any input devices on Win 10 x64. Downgrading to 2015.8 the devices are visible. This issue is with both the latest 16.4 release and nightly build.

**Comment by ataffanel** [comment]
Thanks for the report, I can confirm that is it not working anymore, I will have a look at it. This looks like a problem with SDL.

**Comment by ataffanel** [comment]
This is fixed in commit bedee05, until we release a new version the new installer can be downloaded from appveyor: https://ci.appveyor.com/project/bitcraze/crazyflie-clients-python/build/1.0.51/artifacts
