### ISSUE TITLE
Python Client UI elements missing

### ISSUE THREAD

**Issue by adjavaherian** [bitcraze/crazyflie-clients-python#258]
I just built the cfclient from scratch (develop branch ) on my 10.11.5 Mac El Capitan.  Installed python3 and pyqt with python3 as well as per instructions.

Client starts up, but when I move the window the whole UI in the window does not re-draw, leaving a blank space.  I can get the UI elements back by switching window focus or adding or removing tabs from the window options, which resolves some of the drawing issues.  See attached.

![screen shot 2016-08-31 at 2 03 30 pm](https://cloud.githubusercontent.com/assets/3650448/18140688/979fef2a-6f84-11e6-83a3-7e4c5b0519fe.png)

https://github.com/bitcraze/crazyflie-clients-python/commit/09992349c5e8d899307cab6545eceeb3aad4c576

**Comment by krichardsson** [comment]
This is a known problem (I thought I had added an issue for this but I can not find it) that is related to pyqtgraph. It seems as repainting of the window is failing sometimes when pyqtgraph is installed. For instance after a radio scan, the screen is completely blank.  

Uninstalling pyqtgraph fixes the problem (but is of course required for other functionality)  

A workaround is to switching to another window and back to repaint. 

I don't know if we do something wrong or if this is a bug in pyqtgraph. As far as we know this is only seen on OSX.

**Comment by krichardsson** [comment]
Fixed in #260
