### ISSUE TITLE
no pysdl2 installation found

### ISSUE THREAD

**Issue by grains123** [bitcraze/crazyflie-clients-python#259]
When I install the files and run cfclient, get the following error:

(cfclient) F:\data\crazyflie-clients-python\src>cfclient
F:\Users\grains\AppData\Local\Continuum\Miniconda3\envs\cfclient\lib\site-packag
es\sdl2\dll.py:64: DLLWarning: OSError(8, '%1 is not a valid Win32 application',
 None, 193, None)
  warnings.warn(repr(exc), DLLWarning)
CRITICAL:cfclient.gui:No pysdl2 installation found, exiting!

This an installation on Windows 7, 64-bit.
Thanks!

**Comment by migarcias** [comment]
I have the same problem, but it is in MacOS 10.12.1 (Sierra)
when I run the cfclient, appears: 

CRITICAL:cfclient.cfclient:No pysdl2 installation found, exiting!

this happened since I update from Capitan to Sierra.

I don`t find any solution.

Thanks.

**Comment by ataffanel** [comment]
Have you tried to re-install SDL?

**Comment by GioeleCicchini** [comment]
same problem for me. i tried to re-install SDL
cmd report:

Downloading SDL2 from https://www.libsdl.org/release/SDL2-2.0.4-win32-x86.zip ...
Unziping SDL2.dll in src/cfclient/third_party

i'm on windows 10

**Comment by JeremyCrowley** [comment]
I'm getting the same issue with Windows 10. After I activate the cfclient and try to run it, it gives the error 

`C:\Users\myuser\AppData\Local\Continuum\Miniconda2\envs\cfclient\lib\site-packages\sdl2\dll.py:64: DLLWarning: OSError(8, '%1 is not a valid Win32 application', None, 193, None)
  warnings.warn(repr(exc), DLLWarning)
CRITICAL:cfclient.gui:No pysdl2 installation found, exiting!`

Then when I try to install pysdl2 with pip install is tells me the requirement is already satisfied.

**Comment by ataffanel** [comment]
Thanks for copy-pasting the error. This error is what you would get if you have a mis-match in DLL architecture. The crazyflie client is setup to run in a 32bit python so it downloads the 32bit version of SDL, do you have a 64bit python?

If so and you really need to use a 64bit python you can try to download and decompress the 64bit version of sdl manually: https://www.libsdl.org/download-2.0.php. Though this has caused problem before so reinstalling conda 32bit might be an easier option. If it works in 64bit tell me we can update the pre-windows script to pull the right version.

**Comment by ataffanel** [comment]
I will assume this is a 64bit/32bit problem and close this issue. Feel free to re-open if it wasn't the problem.

I just pushed an update to the prep_windows script to pull the 64bit SDL in case python 64bit is detected. Running on 64bit python used to be bugged but is apparently working fine now.

**Comment by acecilia** [comment]
Installing the cfclient in a fresh installation of Macos Mojave (following all the steps in the readme, first installing all dependencies with brew), I got to this same error:

```
MBP-A:~ andres$ cfclient
CRITICAL:cfclient.gui:No pysdl2 installation found, exiting!
```

I solved it by running:

`pip3 install pysdl2`

@ataffanel fyi

**Comment by quellatalo** [comment]
```
PS C:\cygwin64\home\incom\crazyflie-clients-python> python --version
Python 3.7.3
PS C:\cygwin64\home\incom\crazyflie-clients-python> cfclient
CRITICAL:cfclient.gui:No pysdl2 installation found, exiting!
PS C:\cygwin64\home\incom\crazyflie-clients-python> pip install pysdl2
Requirement already satisfied: pysdl2 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (0.9.6)
PS C:\cygwin64\home\incom\crazyflie-clients-python> cfclient
CRITICAL:cfclient.gui:No pysdl2 installation found, exiting!
PS C:\cygwin64\home\incom\crazyflie-clients-python>
```

It's on windows 10, x64

**Comment by quellatalo** [comment]
If I uninstall pysdl2:
```
PS C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64> pip uninstall pysdl2
Uninstalling PySDL2-0.9.6:
  Would remove:
    c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pysdl2-0.9.6-py3.7.egg-info
    c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\sdl2\*
Proceed (y/n)? y
  Successfully uninstalled PySDL2-0.9.6
PS C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64> cfclient
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\cfclient-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pkg_resources\__init__.py", line 3250, in <module>
    @_call_aside
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pkg_resources\__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pkg_resources\__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pysdl2' distribution was not found and is required by cfclient
```

**Comment by ataffanel** [comment]
On Windows you should run ```python tools/build/prep_windows``` script in order to fetch the sdl2 dll. Have you done that and has the sdl dll been copied in the client folder?

**Comment by quellatalo** [comment]
Yes, I have done that step and there is a `SDL2.dll` in the `src\cfclient\third_party` folder.

**Comment by quellatalo** [comment]
I enabled `SDL2.dll` `read & execute` permission to every user/group.
And after some upgrade/reinstall of packages. Now it works.

**Comment by AkashJohnSubash** [comment]
Faced the same issue on windows 10 , Python 3.10.15 x64, pip 22.2.2, with a virtual environment "cfenv", refer image for module versions.

Problem :
1. (cfenv) pip install cfclient
2. (cfenv) python -m cfenv.gui
   CRITICAL : cfclient.gui : No pysdl2 installation found, exiting !
 
Note : python couldn't find Tools/build/prep_windows in the current version, so i manuall installed the package, .dll with pip

Fix:
1. (cfenv) pip install pysdl2
2. (cfenv) pip pysdl2-dll
Works :) !
Note: The package, .dll individually don't seem to work. 

![pysdl_issue](https://user-images.githubusercontent.com/43522391/203311058-32e48741-6a97-422e-88e7-371770034e44.png)

**Comment by knmcguire** [comment]
Have you seen this issue : https://github.com/bitcraze/crazyflie-clients-python/issues/592 

This particular thread is a bit older than the other one.
