### ISSUE TITLE
Python interpreter crashes when running cfclient on windows with 64bit Python

### ISSUE THREAD

**Issue by grains123** [bitcraze/crazyflie-clients-python#261]
Will the SDL2 64-bit library work if installing everything else 64-bit? I tried this and the cfclient gui comes up and I am able to scan for the crazyflie, but any other command casuses python.exe to crash. I am using python 3.4.2 and used pip commands with 64-bit miniconda. 
I need 64-bit to run matlab realt-time kernel.
Here is the scren output when I hit connect and I get a python.exe has crashed:

![image](https://cloud.githubusercontent.com/assets/18633593/18540176/f55abdc2-7aea-11e6-8b0f-fea11f6c06ea.png)

I am using windows 7, 64-bit

**Comment by ataffanel** [comment]
You can run Python 32bit on Windows 7 64Bits. This is the way we are running the client on Windows. If you really want to run 64Bit you will have to get and copy the sdl2 dll manually.

**Comment by grains123** [comment]
THanks,


Can you tell me the sdl2.dll version to use? I downloaded the 64 bit version and the cfclient gui comes up fine when I activate it. But some of the tabs do not work and when I try to connect, the conection to the crazyflie only lasts a second. In all cases, it is stated that python.exe has crashed.


THanks!


Glen C Rains, PhD, PE
Professor - Department of Entomology
Adjunct Professor - College of Engineering
University of Georgia - Tifton Campus
Research website - www.gcrains.weebly.com
Agrability Website - www.farmagain.com
229-386-3520


________________________________

**Comment by ataffanel** [comment]
The version used in 32bit is 2.0.4: https://github.com/bitcraze/crazyflie-clients-python/blob/develop/tools/build/prep_windows#L6

Do you get any errors in the console when it is crashing?

**Comment by grains123** [comment]
I run the prep_windows python file, replacing win32 with win64. THat works fine.


When I start cfclient it comes up fine. When I hit certain tabs it  is OK. However when I hit connect, I get :python.exe has stopped woprking" and I have the attached dos command output/


[cid:eec3d081-b6c8-4b38-895b-7ebe1997ccb7]


python.exe also stops when I click on the parameters tab, but the dos screen is different.


Thanks!


Glen C Rains, PhD, PE
Professor - Department of Entomology
Adjunct Professor - College of Engineering
University of Georgia - Tifton Campus
Research website - www.gcrains.weebly.com
Agrability Website - www.farmagain.com
229-386-3520


________________________________

**Comment by ataffanel** [comment]
I can confirm that replacing
```
url = 'https://www.libsdl.org/release/SDL2-2.0.4-win32-x86.zip'
```
by 
```
url = 'https://www.libsdl.org/release/SDL2-2.0.4-win32-x64.zip'
```
allows to run in 64bits.

I can also see similar crash to what you are seeing. I am changing the name of the issue to reflect the bug. Until we find what is causing the problem, 32bit python should be used to run cfclient.

**Comment by ataffanel** [comment]
There has been quite some change since this ticket was pushed (including a change from pyqt4 to pyqt5) so I tested again and now it seems to work fine on Windows 64bits.

I just added a test in the prep_windows script to pull the right version (32bit or 64bit) of SDL depending of the python platform.
