### ISSUE TITLE
Bug with jsonapi(zmq) in Win7 x64 binary release 2016.4.1

### ISSUE THREAD

**Issue by qwertyuiop7370** [bitcraze/crazyflie-clients-python#262]
In latest release for Windows (https://github.com/bitcraze/crazyflie-clients-python/releases)
Cfclient version: 2016.4.1
System: win32 (Win7 x64)
Python: 3.4.4

The next exception is appeared:
Traceback (most recent call last):
  File "C:\Miniconda35\envs\cfclient\lib\threading.py", line 911, in _bootstrap_inner
  File "c:\projects\crazyflie-clients-python\src\cfclient\utils\zmq_led_driver.py", line 65, in run
  File "C:\Miniconda35\envs\cfclient\lib\site-packages\zmq\sugar\socket.py", line 470, in recv_json
ImportError: cannot import name 'jsonapi'

**Comment by ataffanel** [comment]
Which file have you been using? The .tag.gz or the git-generated zip?

**Comment by qwertyuiop7370** [comment]
cfclient-win32-install-2016.4.1.exe

**Comment by qwertyuiop7370** [comment]
Why this closed?

**Comment by ataffanel** [comment]
I guess you have clicked on the wrong button since you closed the ticket.

I am going to test tomorrow on Windows to see if I can reproduce the bug.

**Comment by ataffanel** [comment]
Thanks for the report, I can reproduce the problem. I am looking at it.

**Comment by ataffanel** [comment]
It is not showing the problem with new builds and zmq input is working (if enable in the config.json file). You can test the new installer from appveyor: https://ci.appveyor.com/project/bitcraze/crazyflie-clients-python/build/1.0.51/artifacts
