### ISSUE TITLE
ZMQ with simulink

### ISSUE THREAD

**Issue by Fetz93** [bitcraze/crazyflie-clients-python#265]
I want to communicate with the crazyflie with MATLAB simulink and for this I wrote an C s-function.
My problem is an exception in the client, when I want to connect to the socket.
I use the client version 2016.4-14 of issue #262 where the ZMQ input is fixed.
The client throws the following message:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Miniconda35\envs\cfclient\lib\threading.py", line 911, in _bootstrap_inner
  File "c:\projects\crazyflie-clients-python\src\cfclient\utils\input\inputinterfaces\zmqpull.py", line 67, in run
  File "C:\Miniconda35\envs\cfclient\lib\site-packages\zmq\sugar\socket.py", line 527, in recv_json
  File "C:\Miniconda35\envs\cfclient\lib\site-packages\zmq\sugar\socket.py", line 419, in _deserialize
  File "C:\Miniconda35\envs\cfclient\lib\site-packages\zmq\sugar\socket.py", line 527, in <lambda>
  File "C:\Miniconda35\envs\cfclient\lib\site-packages\zmq\utils\jsonapi.py", line 54, in loads
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 114-115: invalid continuation byte
```
In MATLAB I get the errno 11.
I also have MATLAB ZMQ working and with an matlab level 2 s-function it works properly and can connect to the socket. But for real-time code I need an c s-function or a *.tlc file for the s-function.

**Comment by ataffanel** [comment]
Can you isolate and print the message that generates this crash? This looks like what it says: you might be sending json not encoded with UTF-8 which causes this problem.

**Comment by Fetz93** [comment]
I have the following code in an c s-function. The crash occurs with the zmq_connect. 

```
void *context;
void *socket_zmq;
const char *address; 
context = zmq_ctx_new();
socket_zmq = zmq_socket(context, ZMQ_PUSH); 
address = "tcp://127.0.0.1:1212";
zmq_connect(socket_zmq, address);
```
How can I cast the message to be encoded with utf-8? How to isolate the message?

**Comment by ataffanel** [comment]
This code is only connecting ZMQ, not sending anything. Is is crashing already at this point or later?

As for utf8 google gave me some functions that might do the job: https://se.mathworks.com/help/matlab/apiref/mxarraytoutf8string.html?requestedDomain=www.mathworks.com

**Comment by Fetz93** [comment]
Yes, it is already crashing with the zmq_connect. So for the moment only this code is relevant.

**Comment by ataffanel** [comment]
This error can only appear if you are sending a message through the zmq socket. I am trying to reproduce it but without any success so far. Are you sure nothing gets sent?

**Comment by Fetz93** [comment]
I'm sorry. I already testet it and thought it would be while connectiong. But I now figured out, that while connecting I only get the errno 11.
So you're right and it crashes while sending.

```
char *cmdMessage[128];
cmdMessage = "{ \"version\": 1, \"ctrl\": { \"roll\": 0.000000, \"pitch\": 0.000000, \"yaw\": 0.000000, \"thrust\": 20.000000 } }";
zmq_send(socket_zmq, cmdMessage, 128, 0);
```

I'm trying to convert the message to utf8, but with no success so far.

**Comment by ataffanel** [comment]
I managed to reproduce the problem with the code pasted bellow.

I actually think I see the problem: you are sending 128 bytes even when the message is smaller. You should send only the length of the message no more. This certainly why Python is complaining about a range of characters.

``` c
#include <zmq.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>

char * message = "{" \
    "\"version\": 1," \
    "\"client_name\": \"ZMQ client\"," \
    "\"ctrl\": {" \
        "\"roll\": 10.0," \
        "\"pitch\": -10.0," \
        "\"yaw\": 0.0," \
        "\"thrust\": 10.0" \
    "}" \
"}";

char * bad_message = "{\x8a}";

int main()
{
  void *context;
  void *socket_zmq;
  const char *address;
  context = zmq_ctx_new();
  socket_zmq = zmq_socket(context, ZMQ_PUSH);
  address = "tcp://127.0.0.1:1212";

  printf("Connecting the socket ...\n");
  zmq_connect(socket_zmq, address);

  sleep(3);

  printf("Sending good message ...\n");
  zmq_send(socket_zmq, message, strlen(message), 0);

  sleep(3);

  printf("Sending bad message ...\n");
  zmq_send(socket_zmq, bad_message, strlen(bad_message), 0);

  zmq_close(socket_zmq);
  zmq_ctx_destroy(context);

  return 0;
}
```

**Comment by Fetz93** [comment]
Thank you very much for your help! It's working now :+1:

**Comment by ataffanel** [comment]
Great!
Would it be possible for you to share your code to connect simulink to Crazyflie? I know a lot of people would be interested in achieving the same.

**Comment by ataffanel** [comment]
Thanks a lot, I am sure this is going to be useful.
