### ISSUE TITLE
Found 0 devices message in cfclient on Windows 

### ISSUE THREAD

**Issue by guadacasuso** [bitcraze/crazyflie-clients-python#268]
Hi there!
I'm running Windows 10 - Have the CrazyRadios PA drivers installed and the Device Manager recognize it. 
I followed the instructions of the wiki and also the ones [here](https://github.com/bitcraze/crazyflie-clients-python/commit/10454d0f95c929519c571bca38a40edebcf5578e) to get the cfclient working.  Great improvement in the steps, Thanks! I was having issues before. 

I overcome some issues and finally have the UI working but with is not connecting with the drone, seems to be that is not recognizing the crazyradio. The Scan does not return any device. 

This are the logs:

INFO:cfclient.gui:Disabling STL printouts
INFO:cfclient.utils.input.inputreaders:Input readers: ['linuxjsdev', 'pysdl2']
INFO:cfclient.utils.input.inputreaders:Could not initialize [linuxjsdev]: Only supported on Linux
INFO:cfclient.utils.input.inputreaders:Successfully initialized [pysdl2]
INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['leapmotion', 'wiimote', 'zmqpull']
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk')
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid'
INFO:cfclient.utils.config:Dist config read from <mydir>\documents\crazyflie-clients-python\src\cfclient/configs/config.json
INFO:cfclient.utils.config:Config file read from [ <mydir>\AppData\Local\Bitcraze\cfclient/config.json]
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: ZMQ input disabled in config file
INFO:cfclient.utils.zmq_param:Biding ZMQ for parameters at tcp://*:1213
INFO:cfclient.utils.zmq_led_driver:Biding ZMQ for LED driverat tcp://*:1214
INFO:cfclient.utils.input:Using device blacklist [(VirtualBox|VMware)]
INFO:cfclient.ui.main:Auto reconnect enabled: True
INFO:cflib.drivers.cfusb:Looking for devices....
WARNING:cflib.crtp.usbdriver:Exception while scanning for Crazyflie USB: No backend available
QNetworkAccessFileBackendFactory: URL has no schema set, use file:// for files
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices

I appreciate any hint to get this working.

![error](https://cloud.githubusercontent.com/assets/527551/19634827/d5b40126-9972-11e6-84af-79c0abc7dc9a.PNG)

**Comment by ataffanel** [comment]
Hi,
Have you installed the USB driver as documented on the wiki: https://wiki.bitcraze.io/doc:crazyradio:install_windows_zadig?  The error you are getting (no backend available) looks as if libusb driver was not installed.

**Comment by guadacasuso** [comment]
Hi ataffanel, 
you were totally right. I was using a different USB Port, not the indicated in the image. I made the change and is working now! 
I have a different issue with the controller but for this case, we can close the ticket :) 
Thanks for the prompt response!

**Comment by ataffanel** [comment]
Glad that it works! Feel free to either open a new tickets or post on the forum about your controller problems. (maybe this can help: #257)
