### ISSUE TITLE
Client cache not updated when parameter name in the Crazyflie is updated

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-clients-python#281]
Host OS and version of OS: OSX 10.11.6
Crazyflie/Crazyradio version: 0.53
Python version: 3.5.1
Client version: development branch, commit 3d8e97477510bf8cf80b9f8f06c74915e0a7b77a

When the name of a log parameter was changed in the firmware, the client did not pick this change up. I had to manually delete the client cache to get the correct TOC.

**Comment by ataffanel** [comment]
This is a bug in the firmware, will be fixed there.
