### ISSUE TITLE
cfclient traceback upon startup

### ISSUE THREAD

**Issue by byronxubin** [bitcraze/crazyflie-clients-python#283]
Hi Everyone,

I have follow all the steps to install the CF client on my Ubuntu 16.04. While when I want to startup cfclient, I get this error. Does anyone have the same problem? I hope anyone could help with me. Thanks in advance.
![capture](https://cloud.githubusercontent.com/assets/19181168/22770735/ab35a236-ee60-11e6-9b6e-f27417914111.PNG)

**Comment by krichardsson** [comment]
Hi!
It looks like you need to update your bitcraze/crazyflie-lib-python. The send_velocity_world_setpoint() method was added in commit 01a52a16202c296f2407a698e7da946f662e1d13.

**Comment by krichardsson** [comment]
Let us know if you still have this problem
