### ISSUE TITLE
I can't install pyqt4 on my mac 

### ISSUE THREAD

**Issue by jerryyip** [bitcraze/crazyflie-clients-python#290]
See this:
```
brew install homebrew/boneyard/pyqt --with-python3

Updating Homebrew...
^C==> Installing pyqt from homebrew/boneyard
==> Downloading https://downloads.sf.net/project/pyqt/PyQt4/PyQt-4.11.4/PyQt
Already downloaded: /Users/jy/Library/Caches/Homebrew/pyqt-4.11.4.tar.gz
==> python configure.py --confirm-license --bindir=/usr/local/Cellar/pyqt/4.
Last 15 lines from /Users/jy/Library/Logs/Homebrew/pyqt/01.python:
2017-03-21 17:55:58 +0800

python
configure.py
--confirm-license
--bindir=/usr/local/Cellar/pyqt/4.11.4/bin
--destdir=/usr/local/Cellar/pyqt/4.11.4/lib/python2.7/site-packages
--sipdir=/usr/local/Cellar/pyqt/4.11.4/share/sip

Error: /usr/local/opt/qt5/bin/qmake failed to create a makefile. Make sure you
have a working Qt qmake on your PATH or use the -q argument to explicitly
specify a working Qt qmake.
Determining the layout of your Qt installation...

Error: pyqt was moved to homebrew-boneyard because it has unfixable issues.
Please do not file any issues about this. Sorry!
```

**Comment by ataffanel** [comment]
This is currently being fixed in #269 by porting the client to PyQt5. It should soon be merged-in. In the mean time you can try the dev-pyqt5 branch https://github.com/bitcraze/crazyflie-clients-python/tree/dev-pyqt5.

**Comment by jerryyip** [comment]
Thanks! I am able to run the client with pyqt5 now!
But another question raised: the client can't scan my crazyradio pa.
And I have got this problem before when I tried to update the firmware of my crazyradio pa. I finally fixed that problem by changing the usb ID in your code as the following picture.
![0102](https://cloud.githubusercontent.com/assets/18615354/24178738/fb1f7cae-0ee5-11e7-8175-2fd6c2e582f3.png)

### **So could it be the same problem? And how could I fix this?**
Thanks.

**Comment by ataffanel** [comment]
This change is not related to the Crazyradio firmware but rather to the Nordic bootloader. It is very strange since we use the nordic bootloader to flash the crazyradio in factory so the vid/pid should always be correct. Can you please push a new ticket about this issue to keep things organized.

**Comment by ataffanel** [comment]
Thanks for creating the new ticket, the PyQt5 port is now merged so I close this one.
