### ISSUE TITLE
Using wrong value to set the thrust to 0

### ISSUE THREAD

**Issue by Montezuma1973** [bitcraze/crazyflie-clients-python#296]
....../cfclient/utils/input/inputreaderinterface.py

 225:               if thrust < -0.90 or emergency_stop:
 226:                   thrust = 0

Should read:

 225:               if thrust < 0.05 or emergency_stop:
 226:                   thrust = 0

Since thrust has already been altered by:

220:               thrust = thrust / 2 + 0.5

**Comment by krichardsson** [comment]
Great!

Would it be possible for you to issue a pull request with the correction? 
You would also get your name into the commit history :-)

**Comment by Montezuma1973** [comment]
Sure, I will do so on the upcoming weekend.

**Comment by krichardsson** [comment]
Thanks!
