### ISSUE TITLE
Slew rate applies to emergency stop

### ISSUE THREAD

**Issue by Montezuma1973** [bitcraze/crazyflie-clients-python#297]
..../cfclient/utils/input/inputreaderinterface.py

                if thrust < -0.90 or emergency_stop:
                    thrust = 0
                else:
                    thrust = self.input.min_thrust + thrust * (
                        self.input.max_thrust -
                        self.input.min_thrust)
                if (self.input.thrust_slew_enabled and
                    self.input.thrust_slew_limit > thrust and not
                        emergency_stop):
                    if self._old_thrust > self.input.thrust_slew_limit:
                        self._old_thrust = self.input.thrust_slew_limit
                    if thrust < (self._old_thrust -
                                 self.input.thrust_slew_rate / 100):
                        thrust = (self._old_thrust -
                                  self.input.thrust_slew_rate / 100)
                    if thrust < -1 or thrust < self.input.min_thrust:
                        thrust = 0

If this better if 

                if thrust < -0.90 or emergency_stop:
                    thrust = 0
                else:
                    thrust = self.input.min_thrust + thrust * (
                        self.input.max_thrust -
                        self.input.min_thrust)
                    if (self.input.thrust_slew_enabled and   **# <---- this block is under the else statement**
                        self.input.thrust_slew_limit > thrust and not
                            emergency_stop):
                        if self._old_thrust > self.input.thrust_slew_limit:
                            self._old_thrust = self.input.thrust_slew_limit
                        if thrust < (self._old_thrust -
                                     self.input.thrust_slew_rate / 100):
                            thrust = (self._old_thrust -
                                      self.input.thrust_slew_rate / 100)
                        if thrust < -1 or thrust < self.input.min_thrust:
                            thrust = 0

**Comment by krichardsson** [comment]
A pull request would be fantastic!
Thanks!

**Comment by Montezuma1973** [comment]
Sure, I will do so on the upcoming weekend.

**Comment by krichardsson** [comment]
:-)

**Comment by jonasdn** [comment]
Is this still being worked at? Please re-open if that is the case @Montezuma1973
