### ISSUE TITLE
Segmentation Fault when attempting to use the drop down menu for selecting an interface

### ISSUE THREAD

**Issue by JeremyCrowley** [bitcraze/crazyflie-clients-python#299]
I have the cfclient running. When I click on scan, it shows this on the command line.

`INFO:cflib.crtp.radiodriver:v0.53 dongle with serial N/A found`
`INFO:cflib.drivers.cfusb:Looking for devices....`

After this, when I try to use the drop down menu to select the interface, the client crashes with a seg fault. The radio is responding fine and the crazyflie is powered on. We are using the same hardware with a different computer (and it works), so we suspect it is an issue with the client and/or how we set it up.

**Comment by ataffanel** [comment]
When porting the client to pyqt5 I have seen some crash on occasion, but I though we ironed-out all of them. A couple of questions:

1. What version of the client are you running?
2. What operating system are you running on and how did you install pyqt5 on this system?
3. Does it happen only when a Crazyflie is switched ON or also when none are detected?

**Comment by JeremyCrowley** [comment]
1. How can I check the version of the client? I cloned the repository about a month ago.

2. We are on Windows 10. Now that I'm looking at the packages installed on the environment, it doesn't look like we have pyqt5 installed.. Maybe this is the problem?

3. It happens in both cases.

**Comment by JeremyCrowley** [comment]
Problem solved. For some reason, updating pyqt on its own wouldn't work so I restarted and set up a new environment, the new environment had pyqt5 on it and the client doesn't crash anymore when trying to select the input device.

Thanks!

**Comment by ataffanel** [comment]
Ok, great. Thanks for keeping us updated. Reinstalling QT would have been my next proposal :-).
