### ISSUE TITLE
By default use input device name for mapping name when configuring

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#30]
When starting an input mapping configuration for an input device the default name of the mapping should be the same name as read from the device.

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/30
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-05-02T08:01:31.646

**Comment by ataffanel** [comment]
Some device have very long name so I am not sure this is wanted. Futhermore this has not been needed since 2014 so I close it. Feel free to re-open if needed.
