### ISSUE TITLE
Only buttons supported for pitch/roll trim, estop and exit

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#31]
Currently only digital buttons are supported when setting the roll/pitch trim, app exit and emergency stop. Some controllers (like XBox 360) have analog axis on the "digital" pad. This means that they cannot be used for pitch/roll trim.

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/31
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-05-02T08:50:10.480

**Comment by jonasdn** [comment]
Is this still valid? @evoggy
