### ISSUE TITLE
Unable to change the crazyflie2.0 address.

### ISSUE THREAD

**Issue by rbellido1** [bitcraze/crazyflie-clients-python#310]
Hi everyone,
I have a problem with updating the crazyflie address, for instance from  0xE7E7E7E7 to 0xE7E7E7E701. I can update the Channel, Bandwith but address and I am using the latest firmware version for nRF51 and STM32 with Crazyradio (no Crazyradio PA). The strange thing is  when I checked the "Crazyflie 2.0 config" window the new address appears there so I tried to connect using this new address but failed and I just can connect to the default address (0xE7E7E7E7E7)
This problem is very similar with a previous post: 
https://github.com/bitcraze/crazyflie-clients-python/issues/220
I reviewed this post and my cf2config.py  file includes all the changes mentioned on the post. It seems this a new bug or I am missing something.
I'd very much appreciate any help. Many thanks
Robert B.

**Comment by krichardsson** [comment]
You have to restart the Crazyflie for the changes to take effect. You probably did, but just checking...

**Comment by rbellido1** [comment]
Thank you for your reply. I restarted the Crazyflie after the changes. Also I tried to rewrite the EEPROM with my new address, 0xE7E7E7E701, using the write-eeprom.py, following the link instructions: https://wiki.bitcraze.io/doc:crazyflie:dev:starting#reset_eeprom. After running the python script the new address is displayed on the terminal command window but when I tried to connect the Crazyflie with crazyradio using the python-client interface with the new address doesn't work, just work with default address. Thanks

**Comment by krichardsson** [comment]
Not completely sure what is happening, but let us try to figure it out. 

Let's start by going through all the steps to change the address and connect to the Crazyflie. It might be unnecessary detailed, but maybe it will give some insights?

To change the address using USB (it can be done with the radio as well but using USB avoids some pitfalls)
1. Unplug your Crazyradio
1. Start the Crazyflie
1. Connect the Crazyflie with USB cable
1. Start the client
1. You should now have something like "usb://0" in the URI selector in the top left corner
1. Click connect
1. Open the Configure 2.0 dialog
1. Change the address
1. Click write
1. Close the configure dialog
1. Restart the Crazyflie
1. Reconnect by clicking Connect
1. Reopen the Config dialog

Do you get the new or old address at this stage?

If you have the new address, the procedure to connect using the radio should be:
1. Close the client
1. Disconnect the USB cable
1. Plug in the radio again
1. Start the client
1. Enter your new address in the Address field
1. Click Scan

Your crazyflie should now appar in the URI selector if all is good and clicking connect should connect to it.

Please let me know the result or where it goes wrong

**Comment by rbellido1** [comment]
Thank you for your reply. I followed your instructions, step by step, but I couldn't change the address. At step 11, restarted the crazyflie by powering OFF and powering back ON and reconnecting. Finally, when I checked the Config dialog window, the old address still there. I noticed the first time I connected the crazyflie, that orientation changes are reflected on Flight data window, but the second time after the changes, when I restarted the crazyflie and reconnected, i don't get changes on flight data by rotating the crazyflie. Do you think that I might using a old version of the Python client or missing to install something? I tried other things with the C code but nothing work for me at this point. Please let me know if you have some ideas about this issue. Many thanks for your help and time.

**Comment by krichardsson** [comment]
Your problem sounds very much like you have an old version of the NRF firmware. Are you sure you have upgraded to the latest version? The easiest way is to follow the instruction in the getting started guide https://www.bitcraze.io/getting-started-with-the-crazyflie-2-0/#latest-fw

The zip that is downloaded in the instructions contains both NRF and STM firmware and both firmwares will be flashed. 

I suggest you re-flash using this method to make sure they are both the latest stable version. Please let me know the result.

**Comment by rbellido1** [comment]
Hi Kristoffer,
Thank you for replying. You were completely correct and the problem was the old version of NRF firmware. I followed your recommendation and I was able to update the address of crazyflie. I tested successfully the connection of two crazyflies controlling by one crazyradio using Crazyflie_ros.
Thank you again and I really appreciated your help and time.
Robert

**Comment by krichardsson** [comment]
Great!

**Comment by thebikerholic** [comment]
Hi sir i have an doubt that is about how to connect multiple crazyflies in in one crazyradio

**Comment by krichardsson** [comment]
@thebikerholic Please don't append comments/questions to old issues! 
Use the forum https://forum.bitcraze.io/ for this type of questions. Also see https://www.bitcraze.io/support/getting-help/
