### ISSUE TITLE
error opening cfclient with linux 17.10

### ISSUE THREAD

**Issue by gianand** [bitcraze/crazyflie-clients-python#316]
Hi all, i have a problem opening cfclient on linux 17.10. Terminal plot this errors:

INFO:cfclient.gui:Disabling STL printouts
INFO:cfclient.utils.input.inputreaders:Input readers: ['linuxjsdev', 'pysdl2']
INFO:cfclient.utils.input.inputreaders:Successfully initialized [linuxjsdev]
INFO:cfclient.utils.input.inputreaders:Could not initialize [pysdl2]: No SDL2 support on Linux
INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['leapmotion', 'wiimote', 'zmqpull']
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk')
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid'
INFO:cfclient.utils.config:Dist config read from /home/gianluca/crazyflie/crazyflie-clients-python/src/cfclient/configs/config.json
INFO:cfclient.utils.config:Config file read from [/home/gianluca/.config/cfclient/config.json]
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: ZMQ input disabled in config file
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Invalid MIT-MAGIC-COOKIE-1 keyQXcbConnection: Could not connect to display :0
Annullato

Have someone a solution?
Please help me!

**Comment by krichardsson** [comment]
Hi!

> Invalid MIT-MAGIC-COOKIE-1 keyQXcbConnection: Could not connect to display :0
indicates that it can not connect to a X-server for displaying graphics. 

I do not know what the problem is, but maybe it can give you some ideas of what to look for?

**Comment by gianand** [comment]
The problem was the updated linux version. In ubuntu 17.04 it works well!

**Comment by tobbeanton** [comment]
I am running a newly fresh install of 17.10 and don't have this problem. Could it be some library that is not up to date (looks like a QT problem).
