### ISSUE TITLE
Gamepad not recognized on Kubuntu 16.04.03

### ISSUE THREAD

**Issue by drfli** [bitcraze/crazyflie-clients-python#317]
Hello, 
I encountered strange problem with KDE plasma desktop confusing cfclient in Kubuntu 16.04.03 when the KDE_FULL_SESSION and XDG_CURRENT_DESKTOP environment variables are set to true. When it is set the cfclient does not properly recognize availability of the gamepad. At cfclient start there is an input device error dialog with following content 

Error while opening/initializing  input device

Traceback (most recent call last):
  File "/home/flidr/Development/ROS/CrazyFlie/crazyflie-clients-python/src/cfclient/utils/input/__init__.py", line 318, in start_input
    self._selected_mux.add_device(device, role)
  File "/home/flidr/Development/ROS/CrazyFlie/crazyflie-clients-python/src/cfclient/utils/input/mux/__init__.py", line 69, in add_device
    self._open_new_device(dev, role)
  File "/home/flidr/Development/ROS/CrazyFlie/crazyflie-clients-python/src/cfclient/utils/input/mux/__init__.py", line 55, in _open_new_device
    old_dev = self._devs[role]
KeyError: '&Device'

with subsequent dialog stating that the gamepad could not be found. Even though that the gamepad is visible in the Input device submenus (and can be configured) it cannot be used to control the CrazyFlie. Another side effect is that when trying to open config folder in the Settings menu, the directory is opened using SMB protocol, which of course doesn't  work.

After unsetting the KDE_FULL_SESSION and XDG_CURRENT_DESKTOP variables the cfclient work with the gamepad without issues. 

When comparing the console output the only difference between set and unset KDE_FULL_SESSION and XDG_CURRENT_DESKTOP variables can be found in just one line. When unset the cflient outputs

INFO:cfclient.ui.main:Role of Xbox Wireless Controller is Device

when set then the output is 

INFO:cfclient.ui.main:Role of Xbox Wireless Controller is &Device

I hope this report will help to resolve the issue or at least will be useful for somebody who will encounter it.

With regards
Miroslav

**Comment by ataffanel** [comment]
Hi,
Thanks for the report. The joystick driver for linux has been home-made by us and is working by opening the linux dev files directly.
Do you also have problem with other program using gamepad? You can try jstest for example.

**Comment by drfli** [comment]
Actually the gamepad is otherwise working without problem. It works in jstest and even in the input device configuration mode in cfclient. There are just the two error dialog boxes and the gamepad cannot be used for crazyflie control (even the bars with thrusts are not visible correctly). 

I think the problem is that the Qt5 tries to use some library from the KDE desktop (which is Qt5 based) and unsetting those two environment variables just hides the "advanced" features from the cfclient.

**Comment by ataffanel** [comment]
I can reproduce the problem on a kubuntu VM so I am trying to look at what could happen. This is very strange since the gamepad handling should not be dependent of QT, it is written in pure python.

**Comment by ataffanel** [comment]
I found something but there is still a bug. The string "device" comes from the UI, it is the name of the menu from there: https://github.com/bitcraze/crazyflie-clients-python/blob/069efa54069d55014490e17f7e324cb47d102e7b/src/cfclient/ui/main.py#L718. In kubuntu, QT returns "&Device" which is most likely the raw value (the & is used to mark the shortcut key). The following patch removes the error but it is still not possible to select the input map:

``` diff
diff --git a/src/cfclient/ui/main.py b/src/cfclient/ui/main.py
index f57ae0b..def8832 100644
--- a/src/cfclient/ui/main.py
+++ b/src/cfclient/ui/main.py
@@ -715,7 +715,7 @@ class MainUI(QtWidgets.QMainWindow, main_window_class):
                                 and dev_node is not self.sender():
                             dev_node.setChecked(False)
 
-            role_in_mux = str(self.sender().parent().title()).strip()
+            role_in_mux = str(self.sender().parent().title()).strip().strip('&')
             logger.info("Role of {} is {}".format(device.name,
                                                   role_in_mux))
```

I managed to get the client to work by loading the input map from the input device configuration box so there is most likely still a similar menu-related bug.

**Comment by krichardsson** [comment]
outdated
