### ISSUE TITLE
Log fly data into file 

### ISSUE THREAD

**Issue by gianand** [bitcraze/crazyflie-clients-python#318]
Hi all, I'm interested to log fly data into a text file for example. Now i'm studying the cfclient code to understand how the client can log data by plotting them and eventually store them into file.
There is someone that can help me?
Thank you!

**Comment by ataffanel** [comment]
The client can log data in a csv text file, just start a log block and check the "save to file" checkbox in the log block tab: https://wiki.bitcraze.io/doc:crazyflie:client:pycfclient:index#log_blocks

The files are saved in the config folder, you can open the config folder with the 'settings' menu in the client.

**Comment by gianand** [comment]
Ok for the client. But now I have a python script in which a trajectory is assigned to the drone. How can I modify this code to store fly data into a .csv file?
Thanks

**Comment by krichardsson** [comment]
Hi!
I will close this issue since it is not related to a bug or feature request. It is a good question, but please use the [forum](https://forum.bitcraze.io/) for this type of conversations. 

br
Kristoffer
