### ISSUE TITLE
Logging with ZMQ

### ISSUE THREAD

**Issue by RCYajad** [bitcraze/crazyflie-clients-python#321]
I'm using zmq to communicate with the crazyflie. I've also seen the code where it logs data from the crazyflie such as sampling the yaw, pitch, roll, and thrust data of the crazyflie. 

My question is: How do I access these variables in my code? How can I use the value of these variables to be used in my code?

![screenshot from 2018-01-03 15-11-33](https://user-images.githubusercontent.com/18350570/34511738-a38e9f7a-f098-11e7-9a4d-acfc8d3309e1.png)

**Comment by evoggy** [comment]
Once the logging has been started the data will be pushed to a ZMQ socket at the specified interval. Have a look at the [zmqsrvtest.py](https://github.com/bitcraze/crazyflie-clients-python/blob/master/examples/zmqsrvtest.py) example.The rows you have in your screenshot will start the logging but you need to subscribe to the correct socket to get the actual logging data.

The two sections below will create the socket and thread for receiving the logging data asynchronously-
https://github.com/bitcraze/crazyflie-clients-python/blob/0c5bd22c2c2073f39fdd5dda79d87c4a96fd3998/examples/zmqsrvtest.py#L130-L132

https://github.com/bitcraze/crazyflie-clients-python/blob/0c5bd22c2c2073f39fdd5dda79d87c4a96fd3998/examples/zmqsrvtest.py#L146-L147

And here's the code from the thread that reads out the data when it's sent from the Crazyflie:
https://github.com/bitcraze/crazyflie-clients-python/blob/0c5bd22c2c2073f39fdd5dda79d87c4a96fd3998/examples/zmqsrvtest.py#L47-L65

**Comment by RCYajad** [comment]
Thank you! I've been able to do it now. By the way, in creating log blocks, are there any limits in how many variables are we allowed to include?  
![screenshot from 2018-01-03 23-17-04](https://user-images.githubusercontent.com/18350570/34526106-541a137c-f0dc-11e7-8d9b-fdf1f4aa893a.png)

**Comment by evoggy** [comment]
Yes there's a limit to the size of the data generated by a log block. The library will only accept blocks that will generate data that is 30 bytes or less. This can't be deducted from the name alone, the easiest is to either connect using the client and create a log block there to test if the variables will fit or to look in the C code where the logging for the variables are declared.
