### ISSUE TITLE
Unable to connect to Crazyflie 2.0

### ISSUE THREAD

**Issue by zapurva** [bitcraze/crazyflie-clients-python#323]
Hello,

I'm getting started with development on the crazyflie 2.0 platform, using crazyradio PA to talk to the quadrotors. However, I am unable to establish connection using cfclient. The details are as follows:

OS: 
-- Ubuntu, 14.04.5

Crazyradio PA
-- Used [these](https://wiki.bitcraze.io/projects:crazyradio:programming) steps to update firmware to cradio-pa-0.53.bin. Successfully verified the update. 
-- The command `lsusb -d 1915:7777 -v | grep bcdDevice` returns 0.53 as expected

Crazyflie 2.0
-- Followed [these](https://www.bitcraze.io/getting-started-with-the-crazyflie-2-0/#config-client) steps to set up the quadrotor. Verified the powering up using the LED sequence.
-- I was able to update the firmware (contained in crazyflie-2017.06.zip) using the crazyradio, but unable to scan and connect to crazyflie!

I had the same issue with a couple of crazyflies and crazyradios. So it shouldn't be a hardware issue. Also, I'm able to connect to the crazyflie (over bluetooth) using the Android app. Could someone please help?

Thanks!

**Comment by ataffanel** [comment]
Have the Crazyflies been used before? It looks like they are on a different radio address which would explain why you cannot scan them.

You can try to connect one Crazyflie via the USB port and connect to it, it should appear in the list of link when you scann with the client. You can then check if the radio address is the default one (0xe7e7e7e7e7): https://wiki.bitcraze.io/doc:crazyflie:client:pycfclient:index#firmware_configuration

**Comment by zapurva** [comment]
Oh okay! Yeah, they'd been used earlier. I thought re-writing the firmware would set the address back to default. Didn't know how to check the address using the USB connection. Checked one pair and seems to work fine. Thanks @ataffanel  :)

**Comment by ataffanel** [comment]
Nice that it worked! This configuration is written in an external EEPROM which allows to reprogram the Crazyflies without erasing the configuration.
