### ISSUE TITLE
Invalid JSON send by ZMQ

### ISSUE THREAD

**Issue by sdalu** [bitcraze/crazyflie-clients-python#325]
JSON send by the ZMQ client can include forbidden values such as `Infinity`, `-Infinity`, `NaN`.
For interoperability they should be purged and be replaced (if possible by `null`) when generating JSON.

See: https://stackoverflow.com/q/1423081

**Comment by ataffanel** [comment]
Thanks for the report. Do you have an example of where this happen? In cfzmq we use the send_json function which should take care of that.

**Comment by sdalu** [comment]
I don't know much about python, it's why I'm using ZMQ as a blackbox to interact with the drone through ruby  (https://github.com/sdalu/crazyflie-zmq).  I'm using this to retrieve log data from a loco deck.

Which sometimes resulted in the parsing error:
~~~
/usr/local/lib/ruby/2.4/json/common.rb:156:in `parse': 246: unexpected token at '-Infinity},"event":"data","timestamp":180491,"name":"calib"}' (JSON::ParserError)
~~~
