### ISSUE TITLE
ZMQ server start sending log information after create

### ISSUE THREAD

**Issue by sdalu** [bitcraze/crazyflie-clients-python#327]
ZMQ server doesn't wait for the `start` action to send log data, it is sent as soon as the log block is created with the `create` action

It is not what I expected reading: https://wiki.bitcraze.io/doc:crazyflie:client:cfzmq:index

~~~
INFO:cfzmq:Got command {'name': 'range', 'action': 'create', 'variables': ['ranging.distance0', 'ranging.distance1', 'ranging.distance2'], 'version': 1, 'cmd': 'log', 'period': 100}
DEBUG:cflib.crazyflie.log:Adding ranging.distance0 with id=154 and type=0x77
DEBUG:cflib.crazyflie.log:Adding ranging.distance1 with id=155 and type=0x77
DEBUG:cflib.crazyflie.log:Adding ranging.distance2 with id=156 and type=0x77
DEBUG:cflib.crazyflie.log:Adding log block id 1
DEBUG:cflib.crazyflie.log:Have successfully added id=1
INFO:cflib.crazyflie.log:Have successfully started logging for id=1
~~~

**Comment by evoggy** [comment]
Good find. Yeah, this is a bug but a lot of code (including the examples and client) make assumptions about this. If this behavior is not a problem for you then I'll update the doc on the wiki to match what is really happening. What about that?

**Comment by sdalu** [comment]
That's not ideal, but for what I'm currently using it, I can live with that. Making an errata is a good idea.

**Comment by jonasdn** [comment]
@evoggy what is the status of this issue?

**Comment by evoggy** [comment]
The documentation for this has been updated to reflect that the log block starts when created.
