### ISSUE TITLE
Multiple Drones

### ISSUE THREAD

**Issue by spencerh-b** [bitcraze/crazyflie-clients-python#329]
Is there any implementation for multiple drones through the GUI? What is the best approach to take for running multiple drones through an API?

**Comment by krichardsson** [comment]
No, there is no support in the python client for connecting to multiple Crazyflies.

For scripted control of a swarm using the python lib please see the examples in bitcraze/crazyflie-lib-python, mainly [swarmSequence.py](https://github.com/bitcraze/crazyflie-lib-python/blob/master/examples/swarmSequence.py). 
[ROS](https://github.com/whoenig/crazyflie_ros) is also an option as well as [Crazyswarm](http://crazyswarm.readthedocs.io/en/latest/).

**Comment by spencerh-b** [comment]
@krichardsson thank you so much for the help I am currently running into an issue with swarmSequuence.py. When trying to run the python file I get an error

```
  File "crazyflie-lib-python/examples/swarmSequence.py", line 54, in <module>
    from cflib.crazyflie.swarm import CachedCfFactory
ImportError: cannot import name 'CachedCfFactory'
```

Any idea why this might be?

**Comment by spencerh-b** [comment]
I created a work around by simply moving the said class into the swarmSequence.py file, shouldn't be a permanent work around, but it does the job.

**Comment by ataffanel** [comment]
Sorry for the late answer, the fix would be to "git pull" the latest version of the lib and "pip install -e ." in the root of the lib git folder. The problem is that you are using the stable version of the lib that does not contains the class 'CachedCfFactory' while you are using example from unreleased git code that contains it.
