### ISSUE TITLE
Extreme values sent after opening input-device

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#34]
On Linux it's possible to do the following using the PS3:
- Start cfclient without the PS3 controller
- No input-device found
- Insert the PS3 controller
- Device found
- The first time events are read from the device it reads the extreme negative value for all the axis, this is then sent to the copter
- Since the PS button has not been pressed no more events are coming in from the device
- The driver will save the last values and keep re-sending them
- Since full negative is full thrust using the PS3, and the client keeps sending this, the Crazyflie will go...crazy.

This has only been seen on Linux and with the PS3 controller.

To fix this throw away all the events read the first time from the device.

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/34
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-05-06T19:43:51.886

**Comment by qubitter** [comment]
Just hit the PS button to bring everything back to normal.  This happened to me too.
