### ISSUE TITLE
Log write to file only work for the first time running

### ISSUE THREAD

**Issue by kyuhyong** [bitcraze/crazyflie-clients-python#341]
To save the log file into .csv file, I go to Log Blocks and press "Write to file"
This function works fine for the first time however it won't log data the next time. 
After first logging into file, next file only contain Timestamp data.
So I have to re run the client everytime I want to log into files.
Attached is the log file created by cfclient

Kyu

[log.zip](https://github.com/bitcraze/crazyflie-clients-python/files/2147649/log.zip)

**Comment by kyuhyong** [comment]
I investigated this issue and it looks like there is a bug in logdatawriter.py in /src/cfclient/utils
in line 87, where def stop(selft):
it does not exclusively reset self.header_written to False after resetting self.header_values = []
Adding just 
self._header_written = False
remedied this issue and successfully can log into files after again.

**Comment by krichardsson** [comment]
I merged the fix, closing
