### ISSUE TITLE
No Device option under the Input Device Menu

### ISSUE THREAD

**Issue by Ayshine** [bitcraze/crazyflie-clients-python#345]
Hi, 
I couldn't configure my controller because of the following error. Any help is appreciated. 
I am on Ubuntu and trying to launch the GUI from source (as explained here: To launch the GUI application in the source folder type: python3 bin/cfclient )  I couldn't also understand how I can complete the systemwide installation ( I would like to try launchng as explained here:To launch the GUI after a systemwide installation, execute cfclient.)

terminal:
![cmd_output](https://user-images.githubusercontent.com/28358926/44312564-2bb5ec00-a403-11e8-85f6-06117fcf9459.png)

GUI applicaton:
![device](https://user-images.githubusercontent.com/28358926/44312571-3a040800-a403-11e8-802f-cf79b55120e7.png)

Thanks,
Ayshine

**Comment by ataffanel** [comment]
The console output looks good, it does not contain any error related to the controller. What controller do you have and can you see it in jstest?

You can test with jstest-gtk by installing it and running it:
```
$ sudo apt-get install jstest-gtk
....
$ jstest-gtk
```
If a gamepad is detected it should look something like that:
![image](https://user-images.githubusercontent.com/6381499/44326737-ea522a80-a45c-11e8-9de3-2ede2ca0f192.png)

**Comment by Ayshine** [comment]
Hi @ataffanel,
Thank you for your quick response. After a little investigation, it turns out my gamepad somewhat faulty. I will try with another controller.
