### ISSUE TITLE
How can I install GUI systemwide ?

### ISSUE THREAD

**Issue by Ayshine** [bitcraze/crazyflie-clients-python#348]
Hello, 
I am trying to run client using `execute cfclient` but failing to start the GUI, so how can I know f I am successfully installing systemwide or not? 

Thanks,
Ayşin

**Comment by ataffanel** [comment]
Hi,
What commands did you run to install the client?

On my system when I run ```pip3 install -e .``` I have the cfclient script installed in a folder that is in my $PATH, it means that I can run the client with the command cfclient:
```
$ which cfclient
/home/arnaud/.local/bin/cfclient
$ cfclient
INFO:cfclient.gui:Disabling STL printouts
INFO:cfclient.utils.input.inputreaders:Input readers: ['linuxjsdev', 'pysdl2']
 (...)
```
If the client is installed with pip you can always run it from python as well:
```
$ python3 -m cfclient.gui
INFO:__main__:Disabling STL printouts
INFO:cfclient.utils.input.inputreaders:Input readers: ['linuxjsdev', 'pysdl2']
```

**Comment by Ayshine** [comment]
Hi @ataffanel,

I tried to run the commands as explained in the README.md files. Adding `sudo`  to them solved my problem. For example after running as `sudo pip3 install-e .` solved my problem.

Thanks,
Ayshine

**Comment by ataffanel** [comment]
Good that it solves your problem, you are installing the package system-wide in that case.

Out of curiosity, what linux are you using? On Ubuntu 16.04 I have ```~/.local/bin``` in my path out of the box which allows to install and run pip package as local user, without having to use sudo.

**Comment by Ayshine** [comment]
I am on Ubuntu 17.10 and I have use sudo everytime to solve those kind of problems.
