### ISSUE TITLE
Second connect to Crayzflie hangs using USB

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-clients-python#350]
### Description
Second connection attempt to a Crazyflie hangs. Happens with the LPS deck

### How to reproduce
1. Connect the Crazyflie to USB and boot it
1. Start the client
1. Connect the client to the Crazyflie (using USB)
1. Disconnect in the client
1. Close the client
1. Start the client again
1. Connect the client to the Crazyflie Again (using USB)

Expected result:
A clean connection

Observed result:
The connection sequence is locked half way and the client displays the "working" mouse cursor. Client is non responsive.

The log is filled with:
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=51
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=53
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=54
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=55
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=52
...

### Versions
All SW/firmware is latest and greatest from git repos 2018-10-05

### Hardware/OS
Crazyflie 2.0
LPS deck
Mac OS/python 3.6.4

**Comment by krichardsson** [comment]
This problem seems to be related to the _protocolVersionSemaphore in platformservice.py in the lib

**Comment by ataffanel** [comment]
This has been fixed when fixing bitcraze/crazyflie-lib-python#99

**Comment by GimliSonOfGloin** [comment]
I seem to be experiencing this same issue on the Roadrunner using the latest firmware as of 6 Mar 2020. 

Here is a snippet of the code we are running:
rr = crazyflie.Crazyflie(rw_cache='./cache')
rr.open_link(URI)
rospy.spin() # class thread running in the background reading data from roadrunner
rr.close_link()

Works great the first time. No issues. But it appears the rr.close_link() will close the link and then we cannot open the link in subsequent connections. We typically get the following:

WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=2
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=3
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=4

Any help or hints would be greatly appreciated!
