### ISSUE TITLE
"Configure positions" button greyed out in Windows build

### ISSUE THREAD

**Issue by benkuper** [bitcraze/crazyflie-clients-python#351]
In the new UI of the LPS tab, the configure position is greyed out, as well as every button in this tab.
I noticed that the anchorpos parameters are gone, so how to upload / check anchor position from a client and the drone ? 
More informations :
 - Last git version of the crazyflie client and last version of the CF2 firmware, using TDoA V2
 - DWM1000 Deck is detected in the Param tab
 - The estimated position in the LPS Tab is showing a coherent detected position based on previous configuration of the drone and anchors, but no way to change it

**Comment by benkuper** [comment]
![2018-09-17 15_02_47-window](https://user-images.githubusercontent.com/1291595/45624511-ccdba500-ba8a-11e8-91ac-8de978be5017.png)

**Comment by krichardsson** [comment]
The controls in the Loco Positioning tab are enabled when a LPS deck is detected on the Crazyflie. The mechanism for detecting the deck uses param deck.bcDWM1000 and is new. Which revision of the firmware are you using?

**Comment by benkuper** [comment]
I'm using the latest git commit, i compiled it and tested it with TDoA 2 and TDoA 3, both won't enable the buttons, and the Params TOC Tab shows DWM1000 = 1

**Comment by benkuper** [comment]
Update : cloning the repo and launching from command line works, the version in the screenshot is the latest artifact from appveyor, and is not working.

**Comment by ataffanel** [comment]
This was fixed by pushing the latest python lib to pypi. The windows build now works.
