### ISSUE TITLE
Unable to flash firmware using python client

### ISSUE THREAD

**Issue by paradox56** [bitcraze/crazyflie-clients-python#361]
Hello,

I try to flash the latest firmware with the python client. However, after I turn the crazyflie off and while holding the power button foe a few seconds. Only M2 light is blinking and I cannot initiate boot loader cold boot. Any ideas how I can fix this issue?

**Comment by ataffanel** [comment]
This looks like a problem with the STM32 bootloader, has this Crazyflie been programmed using a debug addapter?

You can see this thread in the forum for a solution to recover the STM32 bootloader: https://forum.bitcraze.io/viewtopic.php?f=5&t=3225&p=15771#p15771

**Comment by paradox56** [comment]
No,  I never used a debug adapter on crazyflie.. The firmware flashing does work with my phone for some reasons.

**Comment by paradox56** [comment]
It somehow works now..
