### ISSUE TITLE
About->Debug information about the Crazyflie is not correct

### ISSUE THREAD

**Issue by tobbeanton** [bitcraze/crazyflie-clients-python#364]
Here is an example connected to a CF2.0:

_Crazyflie
Connected: radio://0/80/2M
Firmware: a203d748e139 (MODIFIED)
Sensors found
BMP388: 0
HMC5883L: 1
MS5611: 1
Sensors tests
MPU6500: 1
HMC5883L: 1
MS5611: 1_

**Comment by jonasdn** [comment]
And to help a newcomer out, what would be the expected information?
