### ISSUE TITLE
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'

### ISSUE THREAD

**Issue by hanzheteng** [bitcraze/crazyflie-clients-python#365]
When I fixed this issue, the command line window has erased the previous error messages. I only recorded some keywords of this issue, but I want to report it in case someone else has the same issue in the future. The error message is the following:
```
INFO:cfclient.ui.main:Auto reconnect enabled: True
......
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'
......
INFO:cflib.drivers.cfusb:Looking for devices....
```
If running correctly the it should be
```
INFO:cfclient.ui.main:Auto reconnect enabled: True
INFO:cflib.crtp.radiodriver:v99.55 dongle with serial N/A found
INFO:cflib.drivers.cfusb:Looking for devices....
```

This problem is due to the locked version of numpy. The latest version is 1.16.0 on my computer. If I uninstall numpy and reinstall it again, the version is still 1.16.0. It doesn't work. If I revert it back to 1.15.4, it works. If now I uninstall 1.15.4 and install 1.16.0 again, it works fine this time. 

Showing in code,
- `pip3 uninstall numpy`
- `pip3 install numpy==1.15.4`
would solve this issue. 

Also, continue to execute the following two lines would upgrade numpy to 1.16.0 and cfclient would still work.
- `pip3 uninstall numpy`
- `pip3 install numpy`

I think the reason is 1.15.4 was not uninstalled clearly on my computer. Previously when this issue happens, no matter how I uninstall and install numpy, there is always a `numpy-1.15.4.dist-info` directory in position `~/.local/lib/python3.5/site-packages`. Now it only has a `numpy-1.16.0.dist-info` directory.

I found this solution in a numpy issue https://github.com/numpy/numpy/issues/12736#issuecomment-454442867

This issue can be closed after you guys read it.

**Comment by agcy1210** [comment]
This worked. Thanks a lot!!

**Comment by krichardsson** [comment]
Great info! Useful for the community. 
Thanks!

**Comment by rlfrmsdh** [comment]
Thanks a lot!!!
