### ISSUE TITLE
Installation fails when using setup_linux.sh or setup.py on Ubuntu 14.04

### ISSUE THREAD

**Issue by anusna** [bitcraze/crazyflie-clients-python#367]
Hi,

I have been trying to install the crazyflie client by git cloning to my laptop that runs **ubuntu 14.04**. When I tried to run it with setup_linux.sh it gave an error on the setup.py "**must use python 3.5 or greater**". I checked the version of python and it was 2.7 and for python3 it was 3.4. So, I googled it and found people recommended that I change the command to "**python3.5 setup.py install**" (I installed python 3.5 on my system). After this change, whenever I try to execute "**sudo ./setup_linux.sh**", the python 3.5 error seems to be fixed but I get a new error. 

"**No local packages or download links found for qtm>=2.0.2
error: Could not find suitable distribution for Requirement.parse('qtm>=2.0.2')**"

I have no clue how to resolve this issue. Please provide some suggestions for resolving this issue.

**Comment by anusna** [comment]
P.S - I also tried using the master branch and installing using pip3. I gave the same error

"**raise "must use python 3.5 or greater"
TypeError: exceptions must derive from BaseException**"

**Comment by ataffanel** [comment]
```setup_linux.sh``` is not in the repos anymore, what version are you using?

Anyway, the important point of this script was to run ```pip3 install -e .``` in the project folder. As indicated you need Python3.5 and so the best would be to use Ubuntu 16.04 that ships with Python 3.5. If you have managed to install python 3.5 on your Ubuntu, maybe "pip3.5 install -e ." would work (ie. you need pip to work with your install of Python 3.5).

**Comment by jonasdn** [comment]
Things have changed so much that this issue no longer is valid. If you disagree @anusna please re-open
