### ISSUE TITLE
Issue with Installing Software for CrazyFly 1.0

### ISSUE THREAD

**Issue by jackantico1** [bitcraze/crazyflie-clients-python#368]
I'm using macOS Mojave 10.14.3 and I have home-brew and python 3 installed. I followed the instructions on the readme file and got no errors until I ran the command to actually open up the controller and I got this following error:

critical:cfclient.gui:no pyqt5 installation found, exiting!

I tried doing what was suggesting in other threads but nothing worked. I reinstalled pyqt5 but that didn't work either

**Comment by ataffanel** [comment]
This kind of error often happen when you are not using the same python interpreter to install pyqt5 and to run the Crazyflie client.

you can make sure you are using Python from brew by typing in  a console ```which python3``` and ```which pip3```. Both should be in ```/usr/local/bin/```. And if you type ```ls -l /usr/local/bin/python3``` it should be a symlink to ```../Cellar/python3/(...)```.

Now, you can check that pyqt5 is well installed in this python by typing:
```
$ python3
Python 3.6.1 (default, Mar 24 2017, 09:53:17)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type “help”, “copyright”, “credits” or “license” for more information.
>>>import PyQt5
>>>
```

If that woks without error, you can check that you installed the client in the same python interpreter by launching it with: ```python3 -m cfclient.gui```.

**Comment by jackantico1** [comment]
When I type `which python3` I get back '/Library/Frameworks/Python.framework/Versions/3.6/bin/python3'

When I type `which pip3` I get back `/Library/Frameworks/Python.framework/Versions/3.6/bin/pip3`

When I type ls in usr/local/bin I get 

'2to3			dwebp			idle3			pal2rgb			python2-config		tiff2bw
2to3-2			easy_install		idle3.6			pcre-config		python2.7		tiff2pdf
2to3-2.7		easy_install-2.7	idle3.7			pcregrep		python2.7-32		tiff2ps
2to3-3.6		easy_install-3.6	idn			pcretest		python2.7-config	tiff2rgba
2to3-3.7		easy_install-3.7	idn2			pear			python3			tiffcmp
VBoxAutostart		event_rpcgen.py		ifnames			peardev			python3-32		tiffcp
VBoxBalloonCtrl		fax2ps			img2webp		pecl			python3-config		tiffcrop
VBoxBugReport		fax2tiff		inflatehd		phar			python3.6		tiffdither
VBoxDTrace		fcgistarter		isql			phar.phar		python3.6-32		tiffdump
VBoxHeadless		findbugs-algs4		iusql			php			python3.6-config	tiffinfo
VBoxManage		findbugs-cos226		java-algs4		php-cgi			python3.6m		tiffmedian
VBoxVRDP		findbugs-coursera	java-cos226		php-config		python3.6m-config	tiffset
VirtualBox		fisql			java-coursera		phpdbg			python3.7		tiffsplit
VirtualBoxVM		freebcp			javac-algs4		phpize			python3.7-config	tsql
ab			freetype-config		javac-cos226		pip			python3.7m		unlzma
apachectl		fuzzy_match		javac-coursera		pip2			python3.7m-config	unxz
apm			gdbm_dump		jemalloc-config		pip2.7			pythonw			valet
apxs			gdbm_load		jemalloc.sh		pip3			pythonw-32		vbox-img
argon2			gdbmtool		jeprof			pip3.6			pythonw2		vboximg-mount
aspell			gdbus			jpegtran		pip3.7			pythonw2-32		vboxwebsrv
aspell-import		gdbus-codegen		libmikmod-config	pmd-algs4		pythonw2.7		webpinfo
atom			gio			libpng-config		pmd-cos226		pythonw2.7-32		webpmux
autoconf		gio-querymodules	libpng16-config		pmd-coursera		pyuic5			wget
autoheader		glib-compile-resources	logresolve		png-fix-itxt		pyvenv			wheel
autom4te		glib-compile-schemas	lzcat			pngfix			pyvenv-3.6		wheel3
autoreconf		glib-genmarshal		lzcmp			pod			pyvenv-3.7		word-list-compress
autoscan		glib-gettextize		lzdiff			ppm2tiff		raw2tiff		wrjpgcom
autoupdate		glib-mkenums		lzegrep			precat			rdjpgcom		xcodeproj
brew			glibtool		lzfgrep			preunzip		rotatelogs		xz
brotli			glibtoolize		lzgrep			prezip			rtmpdump		xzcat
bsqldb			gobject-query		lzless			prezip-bin		rtmpgw			xzcmp
bsqlodbc		gresource		lzma			pspell-config		rtmpsrv			xzdec
checkgid		gsettings		lzmadec			pydoc			rtmpsuck		xzdiff
checkstyle-algs4	gtester			lzmainfo		pydoc2			run-with-aspell		xzegrep
checkstyle-cos226	gtester-report		lzmore			pydoc2.7		sandbox-pod		xzfgrep
checkstyle-coursera	h2load			nghttp			pydoc3			sdl-config		xzgrep
cjpeg			htcacheclean		nghttpd			pydoc3.6		sdl2-config		xzless
composer		htdbm			nghttpx			pydoc3.7		sip			xzmore
cwebp			htdigest		nginx			pylupdate5		slencheck		zipcmp
datacopy		htpasswd		node			pyrcc5			smtpd.py		zipmerge
dbmmanage		httpd			npm			python			smtpd2.7.py		ziptool
deflatehd		httxt2dbm		npx			python-32		smtpd2.py
defncopy		idle			odbc_config		python-config		suexec
djpeg			idle2			odbcinst		python2			tdspool
dltest			idle2.7			osql			python2-32		tidy'

However then I get this error message:

`Jacks-MacBook-Pro-6:bin jackantico$ python3
Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import PyQt5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5'`

**Comment by ataffanel** [comment]
You are not using python from home brew. Have you installed python by yourself on the side?

You should be able to install and run the client using the official python3 from python.org as well though. You can type the following from within the crazyflie source folder: ```pip3 install -e .[qt5]```, this will install all required packages and pyqt5. Then ```python3 -m cflient.gui``` should work.

**Comment by krichardsson** [comment]
Closed due to inactivity
