### ISSUE TITLE
Check for latest version of client/firmware from within client

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#37]
It would be nice to be able to check for the latest stable version of the client and the Crazyflie/Crazyradio firmware. Here's the plan so far:

On our server we serve a textfile with the latest versions of these components, like http:///www.bitcraze.se/versions/latest.

One option would be to be notified automatically:
- After the file is fetched the version of the client is compared
- After a Crazyradio is initialized the version of the firmware is compared
- After a Crazyflie has been connected the version of the firmware is compared

If there are any newer version the user would be notified using a pop-up with the options _Download now_, _Ignore_ or _Never show again_.

To be less intrusive this could also be triggered when opening the About box or when the user selects _File->Check for new software/firmware_.

The masterplan would of course be to be able to download and update directly without going through a browser for downloading a file.

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/37
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-05-07T16:53:19.141

**Comment by jonasdn** [comment]
This is kind of supported today, right?
