### ISSUE TITLE
Some parameters not updated on Param tab on connect

### ISSUE THREAD

**Issue by evoggy** [bitcraze/crazyflie-clients-python#373]
Host OS and version of OS: All
Crazyflie/Crazyradio version: All
Python version: 3.6.7

There seems to be a timing issue when creating the model for the Param tab after connect which leaves some parameters (the first values to be read) never updated (marked by red).

![Screenshot from 2019-05-22 14-55-08](https://user-images.githubusercontent.com/5947128/58175975-a1f0c300-7ca1-11e9-93a8-e26c32977342.png)

Once the Param and Log TOC has been downloaded the ```connected``` callback is called. Directly after this a request is made to update all the parameters in the TOC at which point updates will start coming in.

When the ```connected``` callback is called the model for the Param tab view is then created and callbacks are set-up for each parameter in the TOC. But at the same time the stack has requested to update all the parameters. The issue is that some parameters are updated before the model has been able to set up the callbacks for them, leaving them never to be updated (or until another part of the client requests an update).

Reproduced by connecting to a Crazyflie and looking at the Param tab.

**Comment by jonasdn** [comment]
I cannot seem to reproduce this issue. Do you have any tips for me @evoggy?
