### ISSUE TITLE
ImportError: No Qt implementations found

### ISSUE THREAD

**Issue by linghusmile** [bitcraze/crazyflie-clients-python#374]
Hi,
I have meet the follow error while running the comand "python3 bin/cfclient" ,and i do install the python3-pyqt5 and python3-pyqt5.qtsvg. So would someone kind could give me some advice adbout this issue? Thanks a lot.

Traceback (most recent call last):
  File "cfclient", line 2, in <module>
    from cfclient.gui import main
  File "/home/xxx/git/crazyflie-clients-python/src/cfclient/gui.py", line 37, in <module>
    from quamash import QSelectorEventLoop
  File "/usr/local/lib/python3.6/site-packages/quamash/__init__.py", line 40, in <module>
    raise ImportError('No Qt implementations found')
ImportError: No Qt implementations found

And my python is Python 3.6.4.

**Comment by ataffanel** [comment]
What linux distribution are you using and how did you install the client?

**Comment by linghusmile** [comment]
I 'm using ubuntu 16.04 and i install the client use the comand with the readme shows.

**Comment by linghusmile** [comment]
> It looks like pyqt is not installed in your python distribution. What linux distribution are you using and how did you install the client?

Thanks ,I 'm using ubuntu 16.04 and i install the client use the comand with the readme shows.

**Comment by linghusmile** [comment]
ls -l /usr/bin | grep python
lrwxrwxrwx 1 root root          26 1月  14 09:15 dh_pypy -> ../share/dh-python/dh_pypy
-rwxr-xr-x 1 root root        1056 11月 24  2017 dh_python2
lrwxrwxrwx 1 root root          29 1月  14 09:15 dh_python3 -> ../share/dh-python/dh_python3
lrwxrwxrwx 1 root root          23 11月 13  2018 pdb2.7 -> ../lib/python2.7/pdb.py
lrwxrwxrwx 1 root root          23 11月 13  2018 pdb3.5 -> ../lib/python3.5/pdb.py
-rwxr-xr-x 1 root root       73384 5月  16  2016 pvtkpython
lrwxrwxrwx 1 root root          31 1月  14 09:15 py3versions -> ../share/python3/py3versions.py
lrwxrwxrwx 1 root root          26 1月  14 09:15 pybuild -> ../share/dh-python/pybuild
lrwxrwxrwx 1 root root           9 1月  14 09:15 python -> python2.7
lrwxrwxrwx 1 root root           9 1月  14 09:15 python2 -> python2.7
-rwxr-xr-x 1 root root     3492656 11月 13  2018 python2.7
lrwxrwxrwx 1 root root          33 11月 13  2018 python2.7-config -> x86_64-linux-gnu-python2.7-config
lrwxrwxrwx 1 root root          16 11月 24  2017 python2-config -> python2.7-config
lrwxrwxrwx 1 root root           9 1月  14 09:15 python3 -> python3.5
-rwxr-xr-x 2 root root     4464368 11月 13  2018 python3.5
lrwxrwxrwx 1 root root          33 11月 13  2018 python3.5-config -> x86_64-linux-gnu-python3.5-config
-rwxr-xr-x 2 root root     4464368 11月 13  2018 python3.5m
lrwxrwxrwx 1 root root          34 11月 13  2018 python3.5m-config -> x86_64-linux-gnu-python3.5m-config
lrwxrwxrwx 1 root root          16 3月  23  2016 python3-config -> python3.5-config
lrwxrwxrwx 1 root root          10 1月  14 09:15 python3m -> python3.5m
lrwxrwxrwx 1 root root          17 3月  23  2016 python3m-config -> python3.5m-config
lrwxrwxrwx 1 root root          16 11月 24  2017 python-config -> python2.7-config
lrwxrwxrwx 1 root root          29 1月  14 09:15 pyversions -> ../share/python/pyversions.py
-rwxr-xr-x 1 root root       14704 5月  16  2016 vtk6python
-rwxr-xr-x 1 root root        2909 11月 13  2018 x86_64-linux-gnu-python2.7-config
lrwxrwxrwx 1 root root          34 11月 13  2018 x86_64-linux-gnu-python3.5-config -> x86_64-linux-gnu-python3.5m-config
-rwxr-xr-x 1 root root        3185 11月 13  2018 x86_64-linux-gnu-python3.5m-config
lrwxrwxrwx 1 root root          33 3月  23  2016 x86_64-linux-gnu-python3-config -> x86_64-linux-gnu-python3.5-config
lrwxrwxrwx 1 root root          34 3月  23  2016 x86_64-linux-gnu-python3m-config -> x86_64-linux-gnu-python3.5m-config
lrwxrwxrwx 1 root root          33 11月 24  2017 x86_64-linux-gnu-python-config -> x86_64-linux-gnu-python2.7-config
 
It seems like i am using python3.5, but the error while i run ./cfclient is:
Traceback (most recent call last):
  File "cfclient", line 2, in <module>
    from cfclient.gui import main
  File "/home/xx/git/crazyflie-clients-python/src/cfclient/gui.py", line 37, in <module>
    from quamash import QSelectorEventLoop
  File "/usr/local/lib/python3.6/site-packages/quamash/__init__.py", line 40, in <module>
    raise ImportError('No Qt implementations found')
ImportError: No Qt implementations found

Looks like i am using python3.6?

**Comment by linghusmile** [comment]
I have fixed this issue using sudo pip3 install pyqt5
