### ISSUE TITLE
Unable to connect to Crazyflie via a script on Windows 7

### ISSUE THREAD

**Issue by Cesaire-Njietche** [bitcraze/crazyflie-clients-python#375]
I am unable to connect the crazyflie 2.1 on windows 7 with the script provided [here](https://www.bitcraze.io/getting-started-with-stem-drone-bundle/). It blocks while trying to connect outputting the message  `Connecting to radio://0/80/2M
`

The cfclient connects well to the CF 2.1 since I can see how the flight control tab responds when I move, roll, pitch or yaw the CF.

When I try to run another script, I can clearly see that the RadioDriver fails to connect. 

> Connection to radio://0/80/2M failed: RadioDriver: Could not send packet to copter

I need help please ...

**Comment by ataffanel** [comment]
Is your Crazyflie setup for channel 80, 2M bitrate and default address? you can check that by connecting your Crazyflie using the Crazyflie client.

**Comment by Cesaire-Njietche** [comment]
Yes, everything is left to the default value. After connecting my CF, I can clearly see in the `Connect -> Configure 2.0` window that the values match the ones on the main interface : Ch. 80, BW, 2M and the default address (0xE7E7E7E7E7).

**Comment by Cesaire-Njietche** [comment]
I successfully ran the script on the Crazyflie.
To run the script, the Crazyflie client has to be closed since it uses the same link as the script. I didn't see it anywhere. It would be helpful to mention it somewhere to ease the life of beginners.

**Comment by krichardsson** [comment]
I'm glad it worked out for you!

Thanks for the suggested update of the documentation, sounds like a good idea! There are many possible locations to add it. Which documentation did you read? Do you have a preferred location where you think we should add it?

**Comment by Cesaire-Njietche** [comment]
[Here](https://www.bitcraze.io/getting-started-with-stem-drone-bundle/) in the [running your first flight script](https://www.bitcraze.io/getting-started-with-stem-drone-bundle/#running-your-first-flight-script)  section.

**Comment by krichardsson** [comment]
Thanks!
Fixed in bitcraze/bitcraze-website@55d80dca551568a70bb3bfdf13936eff8264d862
