### ISSUE TITLE
Client not showing tilt in flight data

### ISSUE THREAD

**Issue by cf11111** [bitcraze/crazyflie-clients-python#376]
Hi!

I am trying to fly the Crazyflie 2.0 with the python lib.  The drone flies well, can navigate to waypoints, etc. but I ran into a problem when I was unable to log gyro.x/y/z variables (and stabilizer).  I realized that when I tilt the crazyflie while connected to the CF Client, **the flight data screen does not show the tilt.**  The console says that the self tests all pass though.

CF is flashed with the latest firmware, and I have reinstalled the newest lib and client to try to solve my problem.

I do have another crazyflie with firmware from 2018 that does successfully show tilt in the client and allows me to log gyro variables.  I am ordering a new crazyflie in case something is wrong with the gyroscope on the flashed CF, but do you have any ideas about what could be going wrong?

**Comment by knmcguire** [comment]
Hi! Sorry it seems that nobody responded to this issue. Has this been resolved for you now?

**Comment by tobbeanton** [comment]
This problem could be that the sensors never was able to calibrate. When calibrated the red M1 LED starts blinking at 2Hz.

**Comment by krichardsson** [comment]
Closed due to inactivity
