### ISSUE TITLE
Controller must be connected before cfclient launched

### ISSUE THREAD

**Issue by ronswanson50** [bitcraze/crazyflie-clients-python#377]
My cfclient (Windows) will not recognize a controller unless it is plugged into USB before the client launches. If the controller gets disconnected for some reason during use, cfclient must be closed and reopened to recognize the controller again.

**Comment by krichardsson** [comment]
That sounds plausible. I think we have looked at that but it turned out to be hard to fix.
I have not worked on this my self, but if I'm not wrong it works on linux but not on Win and Mac.
I think it is caused by python lib we use.
