### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#38]
Add support for more languages and language switching in the QT client.

Figure out how to do this in a QT/Python way and implement it for at least English. The language should be settable in the client and saved in the config.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/38
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-05-07T16:59:24.372

**Comment by ataffanel** [comment]
Wontfix: we keep it in English for now.
