### ISSUE TITLE
Can't change default address

### ISSUE THREAD

**Issue by katzuv** [bitcraze/crazyflie-clients-python#382]
Hi,
Every time I open the cfclient, the address is `0xE7E7E7E706`.
These are the last lines of `config.json`:
```json
"flightmode": "Normal",
  "link_uri": "radio://0/120/2M/E7E7E7E706",
  "assistedControl": 3
```
The address of my Crazyflie quadocopter is `link_uri`.
So how can I change the default Crazyflie address?
Thank you!

**Comment by katzuv** [comment]
Any help, please?

**Comment by ataffanel** [comment]
As far as I know, the address is not saved in the client. After connecting a Crazyflie at adddress ```E7E7E7E706``` I get config.json similar to yours:
```json
  "link_uri": "radio://0/33/2M/E7E7E7E706",
```

But when I launched the client it is back to ```E7E7E7E7E7```:
![image](https://user-images.githubusercontent.com/6381499/67263296-ef1ece00-f4a7-11e9-9ddf-cf9d5a4a409d.png)

What version of the client are you running?

**Comment by katzuv** [comment]
<details><summary>Version info</summary>
<p>
Cfclient version: 2019.01-18-g9fb3ab6-modified

System: linux
Python: 3.5.2
Qt: 5.5.1
PyQt: 5.5.1
</p>
</details>
When I close and launch again the client, the address returns to be `E7E7E7E7E7` just as yours. But when I look at the `config.json` file, the address there stays `E7E7E7E706`.

**Comment by ataffanel** [comment]
Sorry I miss-understood your last message, I though the address was actually changed in the client for you. The behavior you are describing sounds correct, it is the currently expected behavior: the URI saved in config.mk is not used by the client to setup address or URI.

Do you need the address to be saved between launch?

**Comment by katzuv** [comment]
Well, I do not have to have this feature. I just thought it was the expected behavior.
It's a nice feature because I guess most people use only one Crazyflie and it's more convenient to not write the address every time the client comes up. But it's not a high priority.

**Comment by jonasdn** [comment]
I have made a PR that will attempt to reads the URI from the config and use it to set address in the main UI.
