### ISSUE TITLE
Export function of plot broken

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-clients-python#387]
Export function of the plotter tab is not able to save the plot output. It goes to 'name your file' phase, but after pressing save nothing is being saved.

**Comment by krichardsson** [comment]
Problem in pyqtgraph https://github.com/pyqtgraph/pyqtgraph/issues/454

**Comment by krichardsson** [comment]
Seems to be fixed in pyqtgraph 0.11.0
