### ISSUE TITLE
Assist mode does not send the setpoints correctly

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-clients-python#391]
From this forum thread: https://forum.bitcraze.io/viewtopic.php?f=6&t=4134 by Volmen3

Example copied from forum thread:
1) A press "Assist mode" button and hold it
2) I move the stick (which corresponds to setpoint->velocity.z) back and forth and see corresponding output on the Plotter, but nothing is transmitted to the motors.
3) Now I release the "Assist mode" button while holding the stick in lets say 20% deflection and motors start to rotate with 20% of the max. rotational rate.
4) I release the stick, motors still rotate
5) I press "Assist mode" button with the stick in 0% deflection and motors stop.
6) Now I can repeat the same, but this time release "Assist mode" button while holding the stick in 70% deflection, and motors will rotate with 70% of the max. rotational rate ans so on...

This needs to be verified if this is indeed the case.

**Comment by ataffanel** [comment]
I could not reproduce the problem with the latest version of the client. Using a Crazyflie 2.1 running the latest stable firmware, when pressing the assist button, it does enable the altitude-hold mode as expected. Since this is quite old not I will close the ticket.
