### ISSUE TITLE
Check boxes not correct in "Log Blocks" tab

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-clients-python#393]
There are a couple of reports of checkboxes not working in the Log Blocks tab.

Report 1:
Cfclient
Cfclient version: 2020.2
System: darwin
Python: 3.7.3
Qt: 5.14.1
PyQt: 5.14.1

The check boxes appear, but under the "Contents" column

Report 2:
https://forum.bitcraze.io/viewtopic.php?f=5&t=4196
Linux Mint 19.3, Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
python3-pyqt5 5.10.1+dfsg- amd64 Python 3 bindings for Qt5

No check boxes visible
Also reports errors when mouse over the (non-existing) checkboxes, see forum post.

**Comment by knmcguire** [comment]
Update on the forum. The update to Linux Mint 20 seems to correct the problem.

**Comment by krichardsson** [comment]
We should probably look at refactoring the UI for this functionality, checkboxes feel slightly weird. Maybe we can do something else?

**Comment by krichardsson** [comment]
We are now telling QT to render the UI using its own functions and not using objects in the underlying OS. This should solve this issue.
