### ISSUE TITLE
Only "Flight Control" tab visible in Mac OS, other tabs do not appear

### ISSUE THREAD

**Issue by mbaytas** [bitcraze/crazyflie-clients-python#394]
I have built the cfclient from source on Mac OS Catalina 10.15.3. It seems to run OK, but only the Flight Control tab is visible (and it does work properly). The other tabs are missing.

How to enable the other tabs?

Screenshot:

![image](https://user-images.githubusercontent.com/1661078/76788568-77856e80-67bb-11ea-9864-b5e177c1e25b.png)

Terminal output:

    INFO:cfclient.gui:Disabling STL printouts
    INFO:cfclient.gui:Foundation not found. Menu will show python as application name
    INFO:cfclient.utils.input.inputreaders:Input readers: ['linuxjsdev', 'pysdl2']
    INFO:cfclient.utils.input.inputreaders:Could not initialize [linuxjsdev]: Only supported on Linux
    INFO:cfclient.utils.input.inputreaders:Successfully initialized [pysdl2]
    INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['leapmotion', 'wiimote', 'zmqpull']
    INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk')
    INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid'
    INFO:cfclient.utils.config:Dist config read from /Users/mbaytas/Desktop/crazyflie-clients-python/src/cfclient/configs/config.json
    INFO:cfclient.utils.config:Config file read from [/Users/mbaytas/Library/Application Support/cfclient/config.json]
    INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: ZMQ input disabled in config file
    INFO:cfclient.ui.main:This is a MAC - checking if we can apply Progress Bar Stylesheet for Yosemite Skinny Bars 
    INFO:cfclient.ui.main:Found Yosemite - applying stylesheet
    INFO:cfclient.utils.zmq_param:Biding ZMQ for parameters at tcp://*:1213
    INFO:cfclient.utils.zmq_led_driver:Biding ZMQ for LED driverat tcp://*:1214
    INFO:cfclient.utils.input:Using device blacklist [(VirtualBox|VMware)]
    INFO:cflib.crtp.radiodriver:v0.53 dongle with serial N/A found
    INFO:cfclient.ui.tabs.QualisysTab:Switching Flight Mode to: FlightModeStates.DISCONNECTED
    qt.qpa.fonts: Populating font family aliases took 253 ms. Replace uses of missing font family "Serif" with one that exists to avoid this cost. 
    INFO:cfclient.ui.tabs.QualisysTab:Exception during qtm discovery: Passing `reuse_address=True` is no longer supported, as the usage of SO_REUSEPORT in UDP poses a significant security concern.
    INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
    INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
    INFO:cflib.crtp.serialdriver:Initialized serial driver.
    INFO:cflib.drivers.cfusb:Looking for devices....
    INFO:cflib.crtp.prrtdriver:Initialized PRRT driver.
    INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
    INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices

**Comment by krichardsson** [comment]
You enable/disable tabs from the view/tabs menu
