### ISSUE TITLE
Second connect to Roadrunner hangs using USB

### ISSUE THREAD

**Issue by GimliSonOfGloin** [bitcraze/crazyflie-clients-python#395]
### Description
I seem to be experiencing the same as Issue #350 but on the Roadrunner using the latest firmware as of 6 Mar 2020.

### How to reproduce

1. Connect Roadrunner to USB and boot it.
2. Connect to Roadrunner in code (USB)

```
rr = crazyflie.Crazyflie(rw_cache='./cache')
rr.open_link(URI)
rospy.spin() # class thread running in the background reading data from roadrunner
```
3. Disconnect in the code
```
rr.close_link()
```
3. Start the code again
4. Connect to Roadrunner in code (USB)

Expected result:
A clean connection

Observed result:
Works great the first time. No issues. But it appears the rr.close_link() will close the link and then cannot open the link in subsequent connections. Typically get the following from the log file:
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=2
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=3
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=4

### Versions
All SW/Firmware is latest and greatest from git repos as of 6 Mar 2020.

### Hardware/OS
Roadrunner
Raspbian Stretch/Python 3.5.3

**Comment by knmcguire** [comment]
Hi! Have you tried connecting directly without ROS ? Also this seems to be a issue for the crazyflie-lib-python repo. This repo is for the cfclient alone who uses that cflib.  If so, please close this issue and reopen it in the right repo, with a minum case trying this without the ros package.

I do very like the way that you have reported this issue though :) Very clear

**Comment by GimliSonOfGloin** [comment]
Moving to the crazyflie-lib-python repo. Thanks for the guidance!
