### ISSUE TITLE
cfclient stopped working

### ISSUE THREAD

**Issue by kashishdhal** [bitcraze/crazyflie-clients-python#398]
I have been using cfclient for a few months it just stopped working suddenly. Please see the output below:
<pre>Traceback (most recent call last):
  File &quot;/home/gnclab/.local/lib/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 584, in _build_master
    ws.require(__requires__)
  File &quot;/home/gnclab/.local/lib/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File &quot;/home/gnclab/.local/lib/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (PyYAML 5.3.1 (/home/gnclab/.local/lib/python3.6/site-packages), Requirement.parse(&apos;PyYAML==5.1.2&apos;), {&apos;cfclient&apos;})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/usr/local/bin/cfclient&quot;, line 6, in &lt;module&gt;
    from pkg_resources import load_entry_point
  File &quot;/home/gnclab/.local/lib/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 3252, in &lt;module&gt;
    @_call_aside
  File &quot;/home/gnclab/.local/lib/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 3236, in _call_aside
    f(*args, **kwargs)
  File &quot;/home/gnclab/.local/lib/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 3265, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File &quot;/home/gnclab/.local/lib/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File &quot;/home/gnclab/.local/lib/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File &quot;/home/gnclab/.local/lib/python3.6/site-packages/pkg_resources/__init__.py&quot;, line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The &apos;PyYAML==5.1.2&apos; distribution was not found and is required by cfclient
</pre>

When I try to install pyyaml then I get the following:

<pre><font color="#8AE234"><b>gnclab@system76-pc</b></font>:<font color="#729FCF"><b>~</b></font>$ pip install pyyaml
<font color="#C4A000">DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support</font>
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyyaml in ./.local/lib/python2.7/site-packages (5.1.2)
</pre>

**Comment by krichardsson** [comment]
Seems as you have PyYAML 5.3.1 installed while the client requires 5.1.2. 

I don't see why we would need this particular version, any version above it should be fine as well.

If you are running from source you need to pull down the latest version and run ```pip install -e .``` again.

Another option is to downgrade PyYAML using ```pip install PyYAML==5.1.2```

You should consider upgrading to python3 as well. The Crazyflie python client is not supporting python2 any more (though it probably still works).

**Comment by kashishdhal** [comment]
So I have python3 on my computer. What do I need to do?

**Comment by kashishdhal** [comment]
I reinstalled and it works now!
