### ISSUE TITLE
Loco tab anchor status does not always update

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-clients-python#409]
Switching between different lps methods, does not make the LPS node status in the lps node tab update correctly. If I want to switch from TWR to TDOA, the LPS blocks tend to stay on red eventhough they have correctly switched. Only after a reconnect with the crazyflie this is correct again.

I can assume that this can be very confusing for users in general. Maybe we have to add a force update of the parameters somewhere?

**Comment by jonasdn** [comment]
There is need for more investigation here, we need to verify that the brilliant state machine is doing everything correctly.
