### ISSUE TITLE
Improve input device config to support split axis

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#42]
The configuration dialog and writing should be improved to support the slit axis support added in the changeset 8f4111f

Maybe by adding an option to slit the axis in the UI?

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/42
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-05-11T11:47:02.794

**Comment by evoggy** [comment]
This has been implemented.
