### ISSUE TITLE
Wireless bootloader fails during firmware updating on Mac.

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#44]
http://forum.bitcraze.se/viewtopic.php?f=5&t=168&p=919#p919

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/44
- Originally Reported By: [Tobias Antonsson](http://bitbucket.org/tobbeanton)
- Originally Created At: 2013-05-14T16:52:43.928

**Comment by evoggy** [comment]
This has been tested on newer versions of Mac OSX and could not be reproduced.
