### ISSUE TITLE
Credits not shown in about box when installed with pip

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-clients-python#442]
When the client is installed with pip, either with ```pip3 install .``` or ```pip3 install cfclient```, the credits are not show in the about box.

This is likely due to the fact that the file ```CREDITS.txt``` is not copied in the distribution package by ```setup.py```.

**Comment by jonasdn** [comment]
My proposal is to drop CREDITS.txt to avoid the hassle of updating, distributing  and installing it. Instead link to GitHub graphs in client. See PR #478
