### ISSUE TITLE
Some JSON Python Exception

### ISSUE THREAD

**Issue by EceChaik** [bitcraze/crazyflie-clients-python#448]
Hi guys,

I have built installed the client from source in my Ubuntu 16 and I run it in a virtualenv. 
Everything appears to be working and I was able to fly my crazyflie using a PS4 controller, but after looking at the terminal window I noticed this exception had appeared, apparently during starting the client.

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dc4204/crazyflie-clients-python/src/cfclient/ui/dialogs/bootloader.py", line 397, in _get_firmware_releases
    response = json.load(resp)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

It appears to be originating from the bootloader script, any ideas how I can fix it, or if I should not pay attention to it?

**Comment by krichardsson** [comment]
Hi!

This seems to be related to your python version. I can verify that I get the same problem in python 3.5.7 but it works in 3.7.3.

The API changed in 3.6 https://docs.python.org/3/whatsnew/3.6.html#json
Maybe we should do something to support 3.5?

Upgrading python would be a workaround, if possible.

**Comment by jonasdn** [comment]
Hi, thank you for reporting this!

As of `pip` version 21 out 2021-01-23 support for Python 3.5 was dropped. Taking that in to account I, unfortunately , do not think it is feasible for us to support or fix problems that only appear < Python 3.6.
