### ISSUE TITLE
cfclient cannot be used

### ISSUE THREAD

**Issue by easy98** [bitcraze/crazyflie-clients-python#450]
Hello, I have installed cfclient before and it works perfectly. But today it is broken suddenly. I don't know what happen.
When I run the command "cfclient", I get the following issues:

> INFO:__main__:Disabling STL printouts
> INFO:cfclient.utils.input.inputreaders:Input readers: ['linuxjsdev', 'pysdl2']
> INFO:cfclient.utils.input.inputreaders:Successfully initialized [linuxjsdev]
> INFO:cfclient.utils.input.inputreaders:Could not initialize [pysdl2]: No SDL2 support on Linux
> INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['leapmotion', 'wiimote', 'zmqpull']
> INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk')
> INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid'
> INFO:cfclient.utils.config:Dist config read from /snap/cfclient/65/lib/python3.6/site-packages/cfclient/configs/config.json
> INFO:cfclient.utils.config:Config file read from [/home/coven-lab/snap/cfclient/65/.config/cfclient/config.json]
> INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: ZMQ input disabled in config file
> INFO:cfclient.utils.zmq_led_driver:ZMQ led disabled in config file
> INFO:cfclient.utils.zmq_param:ZMQ param disabled in config file
> Qt: Session management error: None of the authentication protocols specified are supported
> INFO:cfclient.utils.input:Using device blacklist [(VirtualBox|VMware)]
> INFO:cfclient.ui.main:Auto reconnect enabled: True
> INFO:cflib.crtp.radiodriver:v99.55 dongle with serial N/A found
> WARNING: could not determine DPI
> WARNING:vispy:could not determine DPI
> WARNING: Although PyQt5 is already imported, the PyQt5 backend could not
> be used ("cannot import name 'QtOpenGL'"). 
> Note that running multiple GUI toolkits simultaneously can cause side effects.
> WARNING:vispy:Although PyQt5 is already imported, the PyQt5 backend could not
> be used ("cannot import name 'QtOpenGL'"). 
> Note that running multiple GUI toolkits simultaneously can cause side effects.
> ===== 2020.10.10 12:10:01 =====
> Traceback (most recent call last):
>   File "/snap/cfclient/65/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/snap/cfclient/65/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/snap/cfclient/65/lib/python3.6/site-packages/cfclient/gui.py", line 197, in <module>
>     main()
>   File "/snap/cfclient/65/lib/python3.6/site-packages/cfclient/gui.py", line 189, in main
>     main_window = MainUI()
>   File "/snap/cfclient/65/lib/python3.6/site-packages/cfclient/ui/main.py", line 266, in __init__
>     tab = tabClass(self.tabs, cfclient.ui.pluginhelper)
>   File "/snap/cfclient/65/lib/python3.6/site-packages/cfclient/ui/tabs/locopositioning_tab.py", line 469, in __init__
>     self._set_up_plots()
>   File "/snap/cfclient/65/lib/python3.6/site-packages/cfclient/ui/tabs/locopositioning_tab.py", line 500, in _set_up_plots
>     self._plot_3d.native.setSizePolicy(sizePolicy)
> AttributeError: 'CanvasBackend' object has no attribute 'setSizePolicy'
> ===== 2020.10.10 12:10:01 =====
> Traceback (most recent call last):
>   File "/snap/cfclient/65/lib/python3.6/site-packages/cfclient/ui/main.py", line 837, in scan
>     self.interfaceFoundSignal.emit(cflib.crtp.scan_interfaces(address))
>   File "/snap/cfclient/65/lib/python3.6/site-packages/cflib/crtp/__init__.py", line 73, in scan_interfaces
>     found = instance.scan_interface(address)
>   File "/snap/cfclient/65/lib/python3.6/site-packages/cflib/crtp/radiodriver.py", line 361, in scan_interface
>     for c in self._scan_radio_channels(cradio)]
>   File "/snap/cfclient/65/lib/python3.6/site-packages/cflib/crtp/radiodriver.py", line 292, in _scan_radio_channels
>     return list(cradio.scan_channels(start, stop, (0xff,)))
>   File "/snap/cfclient/65/lib/python3.6/site-packages/cflib/drivers/crazyradio.py", line 275, in scan_channels
> Qt has caught an exception thrown from an event handler. Throwing
> exceptions from an event handler is not supported in Qt.
> You must not let any exception whatsoever propagate through Qt code.
> If that is not possible, in Qt 5 you must at least reimplement
> QCoreApplication::notify() and catch all exceptions there.
> 
> 
> (process:21041): GLib-CRITICAL **: 12:24:01.621: g_source_unref_internal: assertion 'source != NULL' failed

**Comment by ataffanel** [comment]
Hi, a new dependency was just added to add a 3D view in the LPS tab, this is likely causing problem here.

What distribution are you running and how did you install the client originally?

Can you try to run ```python3 -m pip install -e .``` again to see if it fixes things?

**Comment by easy98** [comment]
Hello, I installed it by the following way in my ubuntu18.04:

> $ sudo apt-get install git python3 python3-pip python3-pyqt4 python3-numpy python3-zmq
> $ sudo pip3 install pyusb==1.0.0b2
> $ sudo pip3 install pyqtgraph appdirs
> 
> $ cd ~/crazyflie
> $ git clone https://github.com/bitcraze/crazyflie-clients-python.git
> $ cd crazyflie-clients-python
> $ pip3 install --user -e .
> 
> $ mkdir ~/crazyflie
> $ cd ~/crazyflie
> $ git clone https://github.com/bitcraze/crazyflie-lib-python.git
> $ cd crazyflie-lib-python
> $ pip3 install --user -e .

I tried to run `python3 -m pip install -e .`

It doesn't  work, do I need to update or add any python packages?

**Comment by ataffanel** [comment]
I see the same problem as you in a VM and I cannot explain it yet.

One fix for now is to install all dependencies with pip, the best is to do that in a venv since installing pyqt5 with pip can interfere with your system.
``` bash
$ sudo apt install python3-venv
$ cd  ~/crazyflie/crazyflie-clients-python
$ python3 -m venv venv
$ . ./venv/bin/activate
(venv) $ pip3 install -e .[qt5]
(venv) $ cfclient
```

**Comment by easy98** [comment]
Thank you, it works for me!

**Comment by ataffanel** [comment]
Good that the workaround worked! Let's track the real bug in ticker #451.
