### ISSUE TITLE
Crazyflie 1.0 not showing flight data in macOS cfclient 2020.09.1

### ISSUE THREAD

**Issue by sighmon** [bitcraze/crazyflie-clients-python#452]
Hi there,

I've just bought a nice new [Rage 1S 3.7v 250mAh battery](https://www.modelflight.com.au/rage-rc-x-fly-1s-3-7v-250mah-lipo-battery.html) and shaved the connector down so I could revive my old Crazyflie 1.0

I installed the latest Python `cfclient 2020.09.1` using `pip3 install -e .` and updated both the Crazyradio firmware to `0.53` and Crazyflie firmware to `cf1-2017.06.bin`.

The Crazyflie connects and flies beautifully (woo hoo!), but the flight data isn't coming in. I don't see:

* Battery status
* Volts
* Flight data

The only data I do see is the `Link Quality` being updated.

When I'm connected, the UI doesn't update past `Connecting to radio://0/48/250K ...`, so I suspect the [self.connectionDoneSignal](https://github.com/bitcraze/crazyflie-clients-python/blob/master/src/cfclient/ui/main.py#L214) is never getting called.

<img width="1283" alt="Screen Shot 2020-10-31 at 4 27 33 pm" src="https://user-images.githubusercontent.com/314298/97772363-431dc180-1b96-11eb-8c30-1f370c0e2082.png">

I saw this old post from [2014](https://forum.bitcraze.io/viewtopic.php?t=1164), but the codebase seems to have changed too much to use the same fix.

Any ideas?

Cheers, Simon.

## Debug

**Cfclient**
Cfclient version: 2020.09.1-14-gcb1d399
System: darwin (macOS Catalina 10.15.7)
Python: 3.8.6
Qt: 5.12.9
PyQt: 5.12.3

**Interface status**
radio: Crazyradio version 0.53
udp: None
UsbCdc: No information available
prrt: No information available

**Input readers**
PySDL2 (1 devices connected)

**Input devices**
PySDL2: (0) Sony PLAYSTATION(R)3 Controller

**Crazyflie**
Connected: None
Firmware: None

Decks found

Sensors found

Sensors tests

**Comment by knmcguire** [comment]
Hi, we had somebody on the forum that reported the same problem. We proposed some fixes there but it didn't seem to work:
https://forum.bitcraze.io/viewtopic.php?f=6&t=4399&p=20039&hilit=crazyflie+old#p20039. We also didn't hear back from the user either

Maybe it would be good to discuss there on a different thread on the forum instead, since we would like to reserve github issues for requested features or bugs and Since we don't support crazyflie 1.0 in the current client anymore

**Comment by sighmon** [comment]
@knmcguire No problems, and thanks for the link to the forum post. I'll try your VM first and then post there if I don't get anywhere.

**Comment by knmcguire** [comment]
great thanks! yes let us know if there is still a problem

**Comment by sighmon** [comment]
FYI - I'm seeing the same experience on Ubuntu 20.10 and your Bitcraze VM. I'll cross-post to the forum now.

**Comment by ataffanel** [comment]
Hi, I answered on the [forum](https://forum.bitcraze.io/viewtopic.php?p=20642#p20642). The TLDR is: you should use an older client like the one released when CF1 firmware support was stopped. This can be installed with ```pip install cfclient==2017.6.1``` and requires python2.

**Comment by sighmon** [comment]
@ataffanel Unfortunately `2017.6.1` still doesn't show flight data - this is the Python3, QT5 release. I also tried to get `2016.4.1` to run under Ubuntu 20.10, but couldn't get `qt4` installed easily, so I might give up on it and save up for a Crazyflie 2.0. :-)
