### ISSUE TITLE
About local positioning

### ISSUE THREAD

**Issue by easy98** [bitcraze/crazyflie-clients-python#458]
Hi,

I am currently working on building the local positioning system. How can I fly position-hold from the cfclient? Do I need to set any desired point manually? Thanks.

**Comment by krichardsson** [comment]
You must use a gamepad, you can read more about it https://www.bitcraze.io/documentation/repository/crazyflie-clients-python/2020.09/userguides/userguide_client/#flightcontrol
and how to map your game pad here https://www.bitcraze.io/documentation/repository/crazyflie-clients-python/2020.09/userguides/userguide_client/#input-devices

Please consider using the forum (https://forum.bitcraze.io/) for this type of question, we mainly use github for bugs and features.

**Comment by ataffanel** [comment]
Closing since this does not seem to be a bug. Do not hesitate to re-open or open a new ticket if the existing functionality has a bug or needs to be improved.
