### ISSUE TITLE
Option to map shoulder buttons on Xbox Controller

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#46]
Currently, it appears one cannot map any functions to the shoulder buttons of an Xbox controller. It would be great if one could, say map the shoulder buttons to control yaw. I can successfully map trigger buttons to thrust, however.

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/46
- Originally Reported By: [skubie doo](http://bitbucket.org/skubie)
- Originally Created At: 2013-05-15T16:03:18.807

**Comment by ataffanel** [comment]
Shoulder button works find on Xbox controller now. Closing.
