### ISSUE TITLE
Build broken on Windows

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-clients-python#460]
The windows build fails with:

```
ImportError: Vispy requires the 'six' module of minimum version 1.8; normally this is bundled with the Vispy package so if you get this warning consult the packager of your Vispy distribution.
vispy.ext._bundled.six: No module named 'vispy.ext._bundled.six'
six: No module named 'six'
```

**Comment by ntamas** [comment]
We have also seen this with @vasarhelyi yesterday when trying to use the .exe installer for version 2021.06 on Windows. Installing the client from `pip` worked fine, though, after applying [this patch](https://github.com/bitcraze/crazyflie-clients-python/commit/ff872426ae8d9428f0d2be1af802be86e572e2f7) (2021.06.1 was not released yesterday when we tried).

**Comment by knmcguire** [comment]
Hi! @ntamas  We removed the .exe from that release, it shouldn't had been uploaded.... The exe build has been broken for quite some time, so we recommend the pip install in any case.

Thanks for notifying us though!

**Comment by krichardsson** [comment]
@ataffanel Do we want to do anything for this, or close the issue?
