### ISSUE TITLE
Why cfclient doesn't supports individually flash *bin files now?

### ISSUE THREAD

**Issue by inf1nityhhd** [bitcraze/crazyflie-clients-python#506]
**platform** windows10
**client version** 2021.4

I used to use cfclient(2020.9) to flash the *cf2.bin* firmware, but when I update the cfclient to 2021.4, I found it can't flash *bin files now, only supports *zip suffix.

**Comment by ataffanel** [comment]
This was done to simplify the client and the GUI when we implemented deck flashing in the client.

You can still flash individual ".bin" from the command line: `cfloader flash cf2.bin stm32-fw`

**Comment by inf1nityhhd** [comment]
> This was done to simplify the client and the GUI when we implemented deck flashing in the client.
> 
> You can still flash individual ".bin" from the command line: `cfloader flash cf2.bin stm32-fw`

It works! Thanks for your help.😄
