### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#51]
Many areas of the UI would benefit from tests. Foremost among them are input handing and config reading/writing. 

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/51
- Originally Reported By: [Allyn Bauer](http://bitbucket.org/allynbauer)
- Originally Created At: 2013-05-18T20:16:10.785

**Comment by ataffanel** [comment]
(early) duplicate of #221
