### ISSUE TITLE
Long flashing timings

### ISSUE THREAD

**Issue by aslw26** [bitcraze/crazyflie-clients-python#513]
The flashing timings into Crazyflie 2.0 appears to take comparatively longer. Is this an issue with the cfloader? 
I've tried the latest commit on multiple computers and they consistently require longer timings.

**Comment by jonasdn** [comment]
Hi!

This is a known issue (bitcraze/crazyflie-link-cpp#10) on master, we are trying out having the crazyflie-link-cpp as [default radio link library](https://www.bitcraze.io/2021/05/switching-to-crazyflie-link-cpp-by-default/).

We are working to resolve it. You can make the client or cfloader default to python by setting the `USE_CFLINK` environment variable:

```
USE_CFLINK=python cfclient
```
