### ISSUE TITLE
Undesired spinning of motors when disconnecting from cfclient

### ISSUE THREAD

**Issue by dominiknatter** [bitcraze/crazyflie-clients-python#514]
Hey everyone,

I just started working with Crazyflies today (and love your project!), so I'm playing around quite randomly. While doing so, I might have stumbled across a bug.

Setup:
- Ubuntu 20.04
- Crazyflie 2.1 with probably most basic hardware (i.e. no additional decks)
- cfclient and cflib freshly installed from source following the documentation

What the problem looks like:
after disconnecting the cfclient from the Crazyflie the motors can start spinning quite fast.

How to reproduce it:
1. Connect the Crazyflie via USB to your PC / laptop.
2. Start the cfclient and search for the Crazyflie usb, but do not connect yet.
3. Connect your smartphone via the (in this case Android) app with the Crazyflie.
4. Give some motor commands like thrust.
5. While motors are actively spinning, press connect in the cfclient
6. The motors will stop spinning, no matter what you do on the smartphone.
7. disconnect the smartphone from the Crazyflie (you can even turn of Bluetooth)
8. disconnect the cfclient from the Crazyflie
9. motors start spinning again (quite fast, for around 1-3 seconds).

I tried to generate a gif of step 8 and 9 (hopefully you see my mouse moving to the disconnect button in the cfclient).
![VID_20210519_172604(3)](https://user-images.githubusercontent.com/46818571/118842067-285c3180-b8c9-11eb-860a-70e88ab1e8ef.gif)

What I noticed:
- The combination of steps 4. and 5. seems crucial. I.e. if there's no motor command in the moment the laptop connects, there'll be no undesired spinning afterwards.
- in the gif I used rather low "advanced flight control preferences" for safe flights (max thrust ~60%, min thrust ~25%). However, the result can be much worse if you have high thrust settings. **For max thrust 100% and min thrust 50% the Crazyflie took off in step 9!**
- If step 7. is left out (i.e. smartphone stays connected), the motors in 9. spin only very shortly / lightly.
- If the cfclient gets connected to the Crazyflie before the smartphone does there seems to be no undesired spinning afterwards.

As I said I'm a cf-freshman, so I can't help you out with assumptions or fixes. But I thought it's worth publishing, to avoid potential damage or even injuries.

Best,
Dominik

PS: let me know whether this is the correct place to post this, or whether I should post it in another repo or in the forum.

**Comment by dominiknatter** [comment]
addendum for the "What I noticed" section: 
- I can't reproduce the error when the drone is connected to the laptop via Crazyradio PA instead of USB (in other words step 1. is crucial for this error too)

**Comment by krichardsson** [comment]
Thanks for your report!

Switching between communication channels (radio/BLE/USB) is not really supported in the current implementation and it is not unlikely that you will see weird behaviour like this. One manifestation of this is that if you connect via the Crazyradio, BLE is turned off until next reboot (on purpose).

I think this is a fairly unlikely use case, I'm not sure it is documented but maybe it should be added somewhere?

**Comment by dominiknatter** [comment]
Good to know. I totally agree with you, it is a very unlikely case (I myself am not even sure how I ended up in it). I have not found it in the documentation so far. However, I would not know where it could fit and due to its unlikeliness I'm not sure it's needed. I mainly raised the issue to be sure it's not a bug, but if it "is not really supported" anyway I'm fine if you simply want to close it.

**Comment by krichardsson** [comment]
Thanks!
