### ISSUE TITLE
Configure 2.0 Dialogue?

### ISSUE THREAD

**Issue by sarahterracina** [bitcraze/crazyflie-clients-python#516]
Hello,

I am attempting to change the address of my Crazyflie back to the factory default, since it is not currently being recognized by the Crazyradio PA and I suspect that those who used this drone before me may have changed the address but I do not know to what. I am following these instructions, 

1. Unplug your Crazyradio
2. Start the Crazyflie
3. Connect the Crazyflie with USB cable
4. Start the client
5. You should now have something like "usb://0" in the URI selector in the top left corner
6. Click connect
7. **Open the Configure 2.0 dialog**
8. Change the address
9. Click write
10. Close the configure dialog
11. Restart the Crazyflie
12. Reconnect by clicking Connect
13. Reopen the Config dialog

but **when I connect the drone via USB I cannot find a "Configure 2.0 Dialogue" anywhere in the Client window? 
If anyone can, please reply with a screenshot of where/how so I can find it and configure the address.** 

Thanks!

**Comment by jonasdn** [comment]
Hi sarahterracina!


You can find the information in this user guide: https://www.bitcraze.io/documentation/repository/crazyflie-clients-python/2019.09/userguide_client/


With screenshots! Hoppas you solve it!

**Comment by sarahterracina** [comment]
Thank you! It connects now!
