### ISSUE TITLE
Could not load the Qt platform plugin "xcb" (Ubuntu 20.04.02)

### ISSUE THREAD

**Issue by matejkarasek** [bitcraze/crazyflie-clients-python#518]
When launching `cfclient` I get the following error:
```
...
INFO:cfclient.utils.zmq_param:ZMQ param disabled in config file
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```
Starting from a clean installation of Ubuntu 20.04.02, I followed the latest installation instructions:
```
sudo apt install git python3-pip
pip3 install --upgrade pip
```
I set the udev rules and cloned the repo

I get the above error when installing from source (`pip install -e .`) as well as when installing from release (`pip install cfclient`).

If I install via Ubuntu Software everything works fine (but cannot modify the source then...).

**Comment by knmcguire** [comment]
Hi!

On my ubuntu 20.04 wsl I'm able to recreate the problem. By adding `export QT_DEBUG_PLUGINS=1` to .bashrc it is possible to seem more debug messages, then I get the following:

```
Cannot load library /home/kimberly/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/home/kimberly/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so" : "Cannot load library /home/kimberly/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb
```


Seems that libxcb-icccm.so is the curlprit here... and it seems to be connected to the opencv headless pip library. Perhaps there is some mismatching going on?

**Comment by knmcguire** [comment]
you can check it too with the same flag to see if you get the same error message

**Comment by matejkarasek** [comment]
Yes, with the debug on, I do get the exact same error message

**Comment by matejkarasek** [comment]
Following [this post](https://forum.qt.io/topic/115732/could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found/4) and launching
`ldd /home/matej/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so`
 the problem seems to be missing ''libxcb-xinerama0''

Probably not the best solution, but installing pyqt5 using apt-get seems to fix the issue:
`sudo apt-get install python3-pyqt5`

**Comment by matejkarasek** [comment]
https://askubuntu.com/questions/1298645/shared-library-not-found-for-pyqt5-libxcb-xinerama-so-0-not-found

**Comment by knmcguire** [comment]
ah good you found a temp solution there.

Indeed we need to find what is the curlpit. The pip install of the qt5 seems to have less things installed with than with the sudo-apt, so perhaps there is another python package that we are missing.

**Comment by knmcguire** [comment]
So I did a grep with the library (libqxcb.so), which shows which libraries it is missing

```
 ldd /home/kimberly/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so | grep "not found"
        libxcb-icccm.so.4 => not found
        libxcb-image.so.0 => not found
        libxcb-shm.so.0 => not found
        libxcb-util.so.1 => not found
        libxcb-keysyms.so.1 => not found
        libxcb-render-util.so.0 => not found
        libxcb-render.so.0 => not found
        libxcb-xinerama.so.0 => not found
```

Unfortunately I'm not really able to find a python package wrapper for these which would be the best. It might be annoying to install the apt-get package as the setup.py does not really take that into account.

**Comment by knmcguire** [comment]
I've now added additional comments to the install instructions in PR #519. It's only a temp solution though until we can find a nice python wrapper for this.

**Comment by ataffanel** [comment]
In PR #253 I updated the readme with the minimum package required and added a message in the console when the client starts to indicate what package needs to be installed. I think this is the best we can do so I am closing this ticket, feel free to re-open or open a new one if you have a better idea on how to solve the problem.
