### ISSUE TITLE
Where is the code of Set BS channel?

### ISSUE THREAD

**Issue by nigeiwo** [bitcraze/crazyflie-clients-python#525]
Hello, Sir. I find the code of sending the value of the channel to changing in basestation_mode_dialog.py , but I can't find the code that performs the change channel procedure. Where is the code that performs the change channel procedure？

**Comment by knmcguire** [comment]
That is all done within the [ _set_basestation_pressed](https://github.com/bitcraze/crazyflie-clients-python/blob/8722dd5bd2c16a2c201eb116fec3ad1653dec75f/src/cfclient/ui/dialogs/basestation_mode_dialog.py#L114) function. It is just interacting with the io interface of the basestation.

**Comment by nigeiwo** [comment]
Thank you.
