### ISSUE TITLE
Is there a command to set lighthouse basestation2.0 to sleep mode？

### ISSUE THREAD

**Issue by nigeiwo** [bitcraze/crazyflie-clients-python#527]
Hello. Are there any commands to set lighthouse basestation2.0 to sleep mode? Or a mode with just the laser off and one with both the laser and motor off. Via ble data or usb.

**Comment by knmcguire** [comment]
Not sure yet but I'm pretty sure it should be possible. The libsurvive discord channel has some mention of that as well. We will update here if we know more.

**Comment by jonasdn** [comment]
There are ways using ble, you can read more here: https://amp.reddit.com/r/ValveIndex/comments/ikl6eo/i_created_an_app_for_controlling_the_power_state/


We have not integrated anything in our lib or client. We may consider PRs to do so, but it is not obvious that we should.

**Comment by knmcguire** [comment]
With courtesy of @jdavidberger: 
https://github.com/cntools/libsurvive/blob/66e531e7900a64d832ecf86fce65168c4c99a5d9/tools/bsd_ctrl/bsd_ctrl.py

**Comment by nigeiwo** [comment]
> There are ways using ble, you can read more here: https://amp.reddit.com/r/ValveIndex/comments/ikl6eo/i_created_an_app_for_controlling_the_power_state/
> 
> We have not integrated anything in our lib or client. We may consider PRs to do so, but it is not obvious that we should.

Thank you.

**Comment by nigeiwo** [comment]
> With courtesy of @jdavidberger:
> https://github.com/cntools/libsurvive/blob/66e531e7900a64d832ecf86fce65168c4c99a5d9/tools/bsd_ctrl/bsd_ctrl.py

Thank you.
