### ISSUE TITLE
outdated param in flighttab

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-clients-python#530]
The flighttab refers to an older parameter that does not exist anymore, namely the switch between rate-attitude  or attitude based flight. Here is the piece of [code](https://github.com/bitcraze/crazyflie-clients-python/blob/3116e17facb5072f527a3e84bbb769a63a900df3/src/cfclient/ui/tabs/FlightTab.py#L210-L213)

However... since nobody really noticed this in the mean time, like in 5 years, perhaps this checkbox should just be removed?

**Comment by jonasdn** [comment]
That seems suitable! :)

**Comment by knmcguire** [comment]
awesome! thanks :)
