### ISSUE TITLE
Unable to work on LPS 

### ISSUE THREAD

**Issue by Avi241** [bitcraze/crazyflie-clients-python#533]
I am configuring crazy flie 2.0 ro get working with LPS .
I have 8 Anchors and configured it as said in Guide. the blinking lights on lps deck of drone drone and loco positioning nodes shows that they are communicating with each other even I can operate drone with Xbox 360 controller via Crazy file radio PA with cfclient software . but when I switch to loco positioning tab of cfclient app its empty I cannot see anything there and I am getting this kind of msg in terminal when I open cfclient and connect to drone.

INFO:cflib.crazyflie:Callback->Connected to [radio://0/100/2M]
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=1
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=1
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=1
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=1
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=1
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=1
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=1
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=1
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=1
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=1
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=1
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=1
WARNING:cflib.crazyflie.log:Error no LogEntry to handle id=1
INFO:cflib.crazyflie.platformservice:Protocol  version: 2
INFO:cflib.crazyflie.toc:TOC for port [5] found in cache
INFO:cflib.crazyflie:Log TOC finished updating
INFO:cflib.crazyflie.mem:3 memories found
INFO:cflib.crazyflie:Memories finished updating
INFO:cflib.crazyflie.toc:TOC for port [2] found in cache
INFO:cflib.crazyflie:Param TOC finished updating
INFO:cflib.crazyflie:Callback->Connection setup finished [radio://0/100/2M]
INFO:cfclient.utils.logconfigreader:Parsing [stabilizer.json]
WARNING: QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING:vispy:QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING: QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING:vispy:QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING: QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING:vispy:QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING: QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING:vispy:QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING: QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING:vispy:QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING: QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING:vispy:QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING:cflib.crazyflie.toc:Unable to find variable [stateEstimate.x]
WARNING:cflib.crazyflie.log:Log: stateEstimate.x not in TOC, this block cannot be used!
WARNING:cfclient.ui.pose_logger:'Variable stateEstimate.x not in TOC'
WARNING:cflib.crazyflie.toc:Unable to find variable [stabilizer.controller]
WARNING:cflib.crazyflie.param:Cannot set value for [stabilizer.controller], it's not in the TOC!
===== 2021.09.14 17:09:33 =====
INFO:cfclient.ui.main:LED write done callback
Traceback (most recent call last):
  File "/home/arvind/crazyflie-clients-python/src/cfclient/ui/tabs/FlightTab.py", line 441, in connected
    controller=PositionHlCommander.CONTROLLER_PID
  File "/home/arvind/.local/lib/python3.6/site-packages/cflib/positioning/position_hl_commander.py", line 78, in __init__
    self._activate_controller()
  File "/home/arvind/.local/lib/python3.6/site-packages/cflib/positioning/position_hl_commander.py", line 288, in _activate_controller
    self._cf.param.set_value('stabilizer.controller', value)
  File "/home/arvind/.local/lib/python3.6/site-packages/cflib/crazyflie/param.py", line 259, in set_value
    raise KeyError('{} not in param TOC'.format(complete_name))
KeyError: 'stabilizer.controller not in param TOC'
INFO:cfclient.ui.tabs.LEDTab:Memory: id=1, type=LED driver, size=24
Controller parameters 
This parameter group contain read-only parameters pertaining to the CPU in the Crazyflie.

These could be used to identify an unique quad. 
There are 2 levels to control: Position (X, Y, Z) and Attitude (pitch, roll, yaw or in quaternions)

These can be controlled in different modes: Absolute mode, Velocity mode or Disabled

These parameters have impact on which level and mode to use. 
An inertial measurement unit (IMU) is an electronic device that measures and reports a body's specific force, angular rate, and sometimes the orientation of the body, using a combination of accelerometers, gyroscopes, and sometimes magnetometers. 

Override power distribution to motors. 
Tuning settings for the gains of the PID controller for the attitude of the Crazyflie which consists of the Yaw Pitch and Roll 
INFO:cflib.crazyflie.log:Have successfully started logging for id=1
Tuning settings for the gains of the PID controller for the rate angles of the Crazyflie, which consists of the yaw, pitch and roll rates 
Tuning settings for the gains of the PID controller for the position of the Crazyflie ¨ in the X, Y and Z direction in the global coordinate system. 
The LED ring expansion deck contains two powerful front-facing white LEDs and 12 bottom-facing RGB individually addressable LEDs (it uses the same LEDs as used in the NeoPixel products by Adafruit).

The deck is designed to be installed as the last deck on the bottom of the quad. It does not have pass-through holes for the expansion port connector. 
With the Buzzer deck you’ll get audio feedback on system events, like low battery or charging completed. Or why not create your own melodies that will play while you’re buzzing around. If you’re tapped out on creativity there are already a few melodies pre-programmed that you can use.

Changing the sounds requires modifications to the firmware. The code for the sounds is located in [sound_cf.c](https://github.com/bitcraze/crazyflie-firmware/blob/master/src/modules/src/sound_cf2.c) 

INFO:cfclient.ui.tabs.locopositioning_tab:Crazyflie connected to radio://0/100/2M
INFO:cfclient.ui.tabs.lighthouse_tab:Crazyflie connected to radio://0/100/2M
WARNING: QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING:vispy:QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING: QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING:vispy:QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING: QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING:vispy:QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING: QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
WARNING:vispy:QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
INFO:cfclient.ui.tabs.FlightTab:[imu_sensors.HMC5883L]: 1
INFO:cfclient.ui.tabs.FlightTab:[imu_sensors.MS5611]: 1
INFO:cfclient.ui.tabs.FlightTab:Changed effect to 0
ERROR:cflib.crazyflie:Exception while doing callback on port [2]

Traceback (most recent call last):
  File "/home/arvind/.local/lib/python3.6/site-packages/cflib/crazyflie/__init__.py", line 405, in run
    cb.callback(pk)
  File "/home/arvind/.local/lib/python3.6/site-packages/cflib/crazyflie/param.py", line 337, in _new_packet_cb
    self.updated_callback(pk)
  File "/home/arvind/.local/lib/python3.6/site-packages/cflib/crazyflie/param.py", line 191, in _param_updated
    self.all_updated.call()
  File "/home/arvind/.local/lib/python3.6/site-packages/cflib/utils/callbacks.py", line 56, in call
    cb(*args)
  File "/home/arvind/crazyflie-clients-python/src/cfclient/ui/tabs/FlightTab.py", line 659, in _all_params_updated
    self._ring_populate_dropdown()
  File "/home/arvind/crazyflie-clients-python/src/cfclient/ui/tabs/FlightTab.py", line 708, in _ring_populate_dropdown
    if int(self.helper.cf.param.values["deck"]["bcLedRing"]) == 1:
KeyError: 'deck'

Please help me to figure out the problem

**Comment by krichardsson** [comment]
Hi!

It looks like the firmware in your Crazyflie might be outdated, have you tried to updated it? You can find instructions on how the do it here https://www.bitcraze.io/documentation/repository/crazyflie-clients-python/master/userguides/userguide_client/#firmware-upgrade

**Comment by Avi241** [comment]
Hello, @krichardsson  Thanks for your response.
Yes you are right the firmware was outdated earlier I was unable to flash it but after some tries, I flashed it and now it's working fine I am able to set the position of anchors and even I can get the Anchor Estimation when I take the drone near to any Anchor.
But the problem is when I click the radio button of Position estimate after that I am unable to get the position of  Drone in the Loco positioning tab whether I move the drone in the area it always sticks to (0.0,0.0,0.0) axis are not moving.
I am stuck at this point please help me.

**Comment by krichardsson** [comment]
Ok, great!

Do you have the latest versions of the python lib and client as well? The latest release of the lib is 0.1.16 and 2021.06 of the client.

I'm a bit unclear on the versions of the various components in your software when you captured the log in the original comment. Could you please specify the version of the firmware, python lib and client. 

If you have updated all the components to the latest version and still see problems, please add a new log. (that is if you were not already on the latest version)

Cheers!

**Comment by Avi241** [comment]
Thank you for the Guidance it solved my problem for now, but actually, the problem was with the version of the firmware of crazyflie. Earlier I have flashed 2018 firmware then I flashed it with 2021 firmware and now I am getting position data in crazyflie client but unfortunately now I am unable to get a position in ROS . Ok, I will figure it out later.
But yet I am unable to use in position hold mode don't know why. I have Xbox 360 controller.
https://www.bitcraze.io/documentation/tutorials/getting-started-with-flying-using-lps/
I have followed this guide but had no luck. the controls of Xbox are the same as earlier roll/pitch/yaw/thrust, not x/y/z/yaw.
Am I missing out on something? Like I have to configure Xbox for this or anything if you know please help I am stuck at the last part of this Process.

**Comment by krichardsson** [comment]
I'm happy it solved your problem!

We are mainly using github issues for bugs and issues. Further more appending a new question to an existing issue makes it hard for other users to find, so for this reason I will close this issue. 
Our forum (https://forum.bitcraze.io/) is a better place for configuration questions, there might even be an answer to your question? If you don't find an answer, feel free to post a new question there.

**Comment by Avi241** [comment]
Okk Sir Thank You
