### ISSUE TITLE
Path manipulation in bin/cfclient

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#54]
In bin/cfclient, the bootstrapper does some almost-magical work to insert the CF libraries into the system path used at runtime. Maybe I'm overzealous, but I normally try to avoid modifying sys.path at runtime.

IMHO, the code could be made simpler by asking the user to install the program before running it and then using absolute imports based on the system path. Most programs do this and users can normally understand the necessity of installing the software before running it.

I would change this myself, but there's a lot of platform-specific stuff on there (some of it looks like it wouldn't work - e.g. an apparent variable "frozen" is checked before it is set in init_paths. As I only have a Linux box, I can't test the platform-specific stuff and would not want to break anything for non-Linux users. However, it really does seem like requiring installation so that the libraries are in the system path would be a cleaner solution. What do you guys think?

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/54
- Originally Reported By: [Daniel Lee](http://bitbucket.org/erget)
- Originally Created At: 2013-05-27T18:05:30.927

**Comment by ataffanel** [comment]
This is about to be fixed in issue #227

**Comment by ataffanel** [comment]
This has been fixed and is now in much better shape. Thanks for the original report!
