### ISSUE TITLE
Connection dropped more easily on Windows than Linux

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#55]
There's been reports that the client will more easily drop the connection due to packet loss in Windows than in Linux. (http://forum.bitcraze.se/viewtopic.php?f=5&t=269)

Could it be that we are sometimes getting a USBError when writing to the device in crazyradio.py? This could be one explanation to why the retry count is consumed faster.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/55
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-05-30T10:45:41.658

**Comment by evoggy** [comment]
I haven't been able to reproduce this.
