### ISSUE TITLE
Switch to PyQt6/Qt6

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-clients-python#551]
As far as I understand, support for the open-source release of Qt 5.15 has ended or will end soon.

This is not causing practical problems on windows/mac/linux x86 since there is builds of Qt5.15 for all released version of Python. Though it is starting to cause problems on other platforms, for example it prevented me to run the client on OpenSuse tumbleweed on a raspberry pi (arm64) since the only available package for pyqt are PyQT6.

This is something we should look at for the next-next release (after 2022-01/02).

**Comment by knmcguire** [comment]
fixed in https://github.com/bitcraze/crazyflie-clients-python/pull/676
