### ISSUE TITLE
Param tab, text does not fit

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-clients-python#558]
On Ubuntu 21.10
Python: 3.9.7
Qt: 5.15.2
PyQt: 5.15.4

The text does not fit in various boxes in the parameter tab

![Screenshot from 2022-01-20 16-33-31](https://user-images.githubusercontent.com/1464817/150370140-9ed5f37f-df62-4889-a37e-e311aea09384.png)

**Comment by jonasdn** [comment]
Could you try the patch in #561 ?

**Comment by krichardsson** [comment]
Yes #561 solves the problem!
