### ISSUE TITLE
Add arming mechanism for controls

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#56]
It would be safer to add some kind of arming mechanism, like full thrust and back down, before you are able to control the Crazyflie.

There's been some bugs that makes the throttle go to max and problems here could be avoided using arming.

One issue that would be solved by this is when no joystick is present when running the VM in VirtualBox. Then the throttle will be set to max from the _VirtualBox USB Tablet_.

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/56
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-06-05T22:29:43.100

**Comment by evoggy** [comment]
This has been fixed in the firmware (where you need to send 0 before any thrust is accepted) but it should also be added to the client.

**Comment by cbiffle** [comment]
Units shipping this week don't appear to have the fix -- I plugged in a PS3 gamepad which appears to indicate 75% thrust until enabled as a joystick by pressing the "PS" button, causing my Crazyflie 2.0 to ram its way into the ceiling.

Not amused.

**Comment by ataffanel** [comment]
A fix has been added to the firmware and is working fine (no complain since the fix was implemented). Closing this ticket.
