### ISSUE TITLE
Setting param values does not always work

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-clients-python#560]
On Ubuntu 21.10
Python: 3.9.7
Qt: 5.15.2
PyQt: 5.15.4

In the parameter tab, setting parameter values does not always work. Sometimes it seems to be set and sometimes not. Values are not always updated. 

This is probably because callbacks from the Crazyflie are acting directly on the qt thread instead of using signals. A quick check shows that `_param_default_cb` seems to be doing this for instance.

**Comment by jonasdn** [comment]
Hardfaults can be traced to bad values of sound effect: https://github.com/bitcraze/crazyflie-firmware/pull/919

**Comment by krichardsson** [comment]
After re-testing the following problems were found:
1. The "enter" should be connected to the set button to make it fast to set values
2. It seems as an eval() is used to get the value when clicking set. It does not work for "03" for instance, but is also bad as you can add print("hello") or even code that is "evil" in the value box
3. The list on the left side is not updated until the user clicks another parameter after a parameter value is set.
