### ISSUE TITLE
Add more status feedback from Crazyflie

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#58]
After this is added: https://bitbucket.org/bitcraze/crazyflie-firmware/issue/11/add-loggable-variables-to-check-crazyflie

Then we should also add indicators/feedback in the UI to show:
- Power management status (low-battery, charging, fully charged)
- Are we able to fly (using canFly)
- Have the self tests failed, are they running or are they passed

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/58
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-07-02T14:30:18.717

**Comment by ataffanel** [comment]
The battery status is now added. Selftest is indicated by LEDs in the firmware and canFly has not been needed so far so I close this ticker.
