### ISSUE TITLE
"Firmware" parameter description bug

### ISSUE THREAD

**Issue by matejkarasek** [bitcraze/crazyflie-clients-python#585]
In 2022.1, the description of "firmware" parameter group and parameters is incorrect. It shows up the description of the previously selected param group instead of the one belonging to firmware. If it is selected first, it remains empty, but once other parameter group is selected it will again behave as described.

Tested with 2022.1 installed with pip on Win 11, and 2022.1 firmware on the CF2

(I noticed this behavior also with some custom parameter groups in our fork)

**Comment by krichardsson** [comment]
I see the same behavior. Thanks!

**Comment by krichardsson** [comment]
This seems to actually be two problems:
1. The documentation for the firmware parameter group is not generated. Fixed by bitcraze/crazyflie-firmware#928
2. If the documentation for a parameter is missing, the description is not cleared in the param tab. Fixed by #586
