### ISSUE TITLE
Log Blocks bug on Windows

### ISSUE THREAD

**Issue by matejkarasek** [bitcraze/crazyflie-clients-python#588]
On Windows 11 with pip installation, in the Log Blocks tab the Start and Write to file columns are empty, no checkboxes...
However, clicking into the empty space will start the logging and writing to file, so it only seems to be a problem with rendering...

**Comment by knmcguire** [comment]
I pip installed the latest cfclient from master. I'm still on windows 10 myself but I did see the logblocks were being rendered.

<img width="602" alt="cfclient_logblocks_win10" src="https://user-images.githubusercontent.com/11061260/157629453-9d76336e-5159-42e5-8359-79ae93d8440c.PNG">

On windows I have python 3.9 with these QT pip libraries:
```
PyQt5                                5.15.6
PyQt5-Qt                             5.15.2
PyQt5-Qt5                            5.15.2
PyQt5-sip                            12.9.0
```

**Comment by matejkarasek** [comment]
I have Python 3.10
The PyQt5 versions are the same (PyQt5-Qt was not installed, but pip-installing that did not change anything).

This is what I am seeing:
![Screenshot 2022-03-10 105922](https://user-images.githubusercontent.com/10943061/157638190-78ed97dd-0f16-4e94-9447-af6f989534eb.png)

Anyone else on Windows 11 that could replicate this? :)

**Comment by knmcguire** [comment]
another reason for my to upgrade my computer hardware :)

**Comment by knmcguire** [comment]
I have windows 11 now! And I confirm this issue with python 3.10

Seems like I also get this error too:

```
Traceback (most recent call last):
  File "C:\Users\kimbe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cfclient\ui\tabs\LogBlockTab.py", line 294, in paint
    s.rect.adjust(center_offset, 0, 0, 0)
TypeError: adjust(self, int, int, int, int): argument 1 has unexpected type 'float'
```

So it seems to be a problem with the graphics... A type error would fit an python version issue perhaps?

**Comment by matejkarasek** [comment]
Oh, and yes, I see the same error (was hidden among those mentioned in #587)

**Comment by krichardsson** [comment]
Also on linux. 

I get a lot of logs like this

```
  File "/home/kristoffer/code/bitcraze/crazyflie-clients-python/src/cfclient/ui/tabs/LogBlockTab.py", line 294, in paint
    s.rect.adjust(center_offset, 0, 0, 0)
TypeError: adjust(self, int, int, int, int): argument 1 has unexpected type 'float'

```

This seems to be related to changes in Qt, also see #595
