### ISSUE TITLE
cfclient fails to set value to GUI element, spams stderr

### ISSUE THREAD

**Issue by schlagenhauf** [bitcraze/crazyflie-clients-python#595]
Latest pypi version installed with pipx.

When running cfclient with a gamepad connected, the following error continuously occurs, even before connecting to a crazyflie:

```
Traceback (most recent call last):
  File "/home/pntagrl/.local/pipx/venvs/cfclient/lib/python3.10/site-packages/cfclient/ui/tabs/FlightTab.py", line 555, in updateInputControl
    self.thrustProgress.setValue(thrust)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
```
As far as I can tell this is caused by `setValue` only accepting `int`, however `thrust` is `float`. Changing [the line](https://github.com/bitcraze/crazyflie-clients-python/blob/3cb5c3f40a257e49e7d978cd99b48d5438cd0752/src/cfclient/ui/tabs/FlightTab.py#L554) to `self.thrustProgress.setValue(int(thrust))` gets rid of the error and seems to produce the right progress bar value.

**Comment by krichardsson** [comment]
Thanks for notifying us!

We got a similar report for the LPS-tools the other day (that also uses QT), it seems as the setValue() method has changed in the latest version of qt.
