### ISSUE TITLE
Opencv dependency Problem

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-clients-python#611]
This issue describes the problem of the conflicting python libraries of opencv.

Platform: Ubuntu 20.04
Libraries:
opencv-python          4.5.5.64
opencv-python-headless 4.5.5.64 

Then you get the error:
```
INFO:cfclient.gui:If startup fails because of "xcb", install dependency with `sudo apt install libxcb-xinerama0`.
QObject::moveToThread: Current thread (0xc49380) is not the object's thread (0x20f2210).                               
Cannot move to target thread (0xc49380)
 qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/knmcguire/.local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found. 
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem. 

 Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.  
```

This does not happen in Windows 11.

Solution:

Deinstall opencv-python by `pip3 uninstall opencv-python`
or
Install the cfclient in a separate python environment

Also we would need to make the error description better, as it now indicates another solution to solve this.

**Comment by krichardsson** [comment]
Note: There are links to this issue from the [aideck-gap8-examples](https://github.com/bitcraze/aideck-gap8-examples) and [bitcraze-website](https://github.com/bitcraze/bitcraze-website)

Please remove the references when closing this issue

**Comment by knmcguire** [comment]
This is now solved with the latest development branch of both the cfclient and cflib. People that don't wan this dependency anymore should update to the latest and greatest from source.

**Comment by knmcguire** [comment]
We can keep the references in the tutorials a bit longer open, as the release is not out yet, also they can check the status of this issue and the solution so it is not that bad. 

This will still hold anyway if users are using an older version of the cfclient
