### ISSUE TITLE
CFclient can't update deck when multiple are attached

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-clients-python#616]
In this discussion somebody encountered that the lighthouse deck's firmware does not get updated if any other deck is attached: https://github.com/orgs/bitcraze/discussions/96

This also occurs with the AIdeck if a flowdeck or any other deck is attached.

Platform: Windows 11

**How to reproduce:** 
1. Have a Crazyflie with a lighthouse deck or AIdeck, and attach another deck to it as well (which is [compatible](https://www.bitcraze.io/documentation/system/platform/cf2-expansiondecks/#deck---deck)). 
2. Go the the cfclient, go to Connect >Bootloader>flash the latest release (with warmboot)

**Result:** 
The NRF and STM get reflashed but the to be updated deck is skipped.

**What I would expect:**
Either that the deck is updated without problems, or that there is at least a warning like: 'Multiple decks detected, Can't update'

**Comment by krichardsson** [comment]
Can not reproduce

**Comment by krichardsson** [comment]
This problem still exists. I get if from time to time, but it is a bit random.
I got it with a Lighthouse deck (with outdated FPGA binary) and a LED ring deck. Curiously enough it works sometimes, but not allways.

**Comment by whoenig** [comment]
I have the update problem also frequently (usd + aideck). The main problem I have is that there seems that there is no proper error checking: if the 1wire reports the aideck works, but the UART connection doesn't work for some reason, there is no message. Similarly, when updating the firmware and there is some sort of error, there is no report on that at the end.

**Comment by krichardsson** [comment]
Thanks for the input @whoenig !

**Comment by krichardsson** [comment]
There seems to be a number of problems here working together. PRs https://github.com/bitcraze/crazyflie-clients-python/pull/664 and https://github.com/bitcraze/crazyflie-lib-python/pull/398 hopefully fixes them.

Tested with LED-ring + AI-deck + LH-deck
