### ISSUE TITLE
Found 0 devices in cfclient connection in Macos

### ISSUE THREAD

**Issue by somBabu1996** [bitcraze/crazyflie-clients-python#635]
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cflib.crazyflie:Callback->Connection initialized[udp://192.168.43.42]
ERROR:cflib.crazyflie:Couldn't load link driver: [Errno 56] Socket is already connected

Traceback (most recent call last):
  File "/Users/somprakash/crtp/crazyflie-lib-python/cflib/crazyflie/__init__.py", line 222, in open_link
    self.link = cflib.crtp.get_link_driver(
  File "/Users/somprakash/crtp/crazyflie-lib-python/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/Users/somprakash/crtp/crazyflie-lib-python/cflib/crtp/udpdriver.py", line 71, in connect
    self.socket.sendto(str1,self.addr)
OSError: [Errno 56] Socket is already connected

INFO:cflib.crazyflie:Callback->Connected failed to [udp://192.168.43.42]: Couldn't load link driver: [Errno 56] Socket is already connected

Traceback (most recent call last):
  File "/Users/somprakash/crtp/crazyflie-lib-python/cflib/crazyflie/__init__.py", line 222, in open_link
    self.link = cflib.crtp.get_link_driver(
  File "/Users/somprakash/crtp/crazyflie-lib-python/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/Users/somprakash/crtp/crazyflie-lib-python/cflib/crtp/udpdriver.py", line 71, in connect
    self.socket.sendto(str1,self.addr)
OSError: [Errno 56] Socket is already connected

INFO:cflib.crazyflie:Closing link
INFO:cflib.crazyflie:Callback->Disconnected from [udp://192.168.43.42]
INFO:cfclient.ui.tabs.QualisysTab:Crazyflie disconnected from udp://192.168.43.42
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices

<img width="869" alt="cv bjnk" src="https://user-images.githubusercontent.com/112747346/189596454-14c15f24-05d3-444d-83fb-68f1af994dae.png">

Any comments as a solution will be appreciated.

**Comment by krichardsson** [comment]
I'm not sure how this functionality (UDP connection) is supposed to work, or what the status of it is. Could you please describe more in detail the steps you do to get to the state you are in and also what your goal is

**Comment by somBabu1996** [comment]
installed Cf client. and introduced crazyflie drone inside esp. now the ESP board generates hotspot to join, by using which i had tried to connect my mobile and its happened properly. but the cf client scan is not working and not connecting to the ESP device. and it shows 0 device connected. 
Other details i have updated before. Please check it.
It would be helpful for any information will be shared regarding the same.

**Comment by krichardsson** [comment]
I'm not sure how this works really as it is not a use case that is supported by Bitcraze, As you are using an ESP drone, maybe you can some help in their forum?
