### ISSUE TITLE
Install instructions don't install pysdl2

### ISSUE THREAD

**Issue by sawyerbfuller** [bitcraze/crazyflie-clients-python#636]
When I tried to run `cfclient` for the first time, using the command `/usr/local/bin/python3.9 /usr/local/bin/cfclient` to make sure I was running the x86-64 version of various binaries, I encountered this error: 

```
CRITICAL:cfclient.gui:No pysdl2 installation found, exiting!
```

Suggested change: Update [this page](https://www.bitcraze.io/documentation/repository/crazyflie-clients-python/master/installation/install/) to either include `pysdl2` and `pysdl2-dll` on the  install instructions. That is, change 

`pip3 install cfclient`

to 

`pip3 install pysdl2 pysdl2-dll cfclient`  

or somehow make cfclient force an install of `pysdl2`. Otherwise newbs might get stuck. 

(my computer: M1 Macbook Pro)

**Comment by krichardsson** [comment]
Thanks for the feedback!

There is actually a [bit of code](https://github.com/bitcraze/crazyflie-clients-python/blob/088f5e8c704a4a8395f72539cbac58aabf1a87c5/setup.py#L78-L81) that is supposed to handle this. 

This probably requires some more investigations to figure out why it did not work for you.

**Comment by krichardsson** [comment]
I did run a quick test on our M1 and it seems to work as expected, not sure how to reproduce the problem.
@sawyerbfuller do you have any more information that might be helpful?

**Comment by krichardsson** [comment]
Hmm, I do not get your error, but on the other hand my game pad (PS3) does not seem to work either. I don't have any experience with M1s, this will require more investigations.

**Comment by sawyerbfuller** [comment]
Hi @krichardsson I see, it does look like those packages should be automatically installing. 

The only possible cause I can imagine is that there is some complexity associated with having arm native and x86 libraries on the same system. I had to uninstall the arm version of brew so that I could install the x86 `cfclient`. 

Anyway, I'll assume for now that it's caused by something unusual in my system, feel free to close this issue unless you want to keep it open to work on the controller issue. I haven't tried that yet so I'll post here or open a new issue if I have the same problem.

**Comment by krichardsson** [comment]
Thanks for the feedback!
I'll close this for now, but please open a new issue if you run into problems with the controller.
