### ISSUE TITLE
Add possibility to mapp L2 and R2 on PS controller

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#64]
Is there any possibility to add all the buttons of the PS3 controller? 
I would like to use the L2 and R2 for stuff like thrust control. 
Or maybe L1 and R1 to change the yaw together...

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/64
- Originally Reported By: [Pär Stålberg](http://bitbucket.org/rabbadab)
- Originally Created At: 2013-08-22T08:56:36.366

**Comment by ataffanel** [comment]
Fixed in #46.
