### ISSUE TITLE
Parameters not updated in UI

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/crazyflie-clients-python#657]
Parameters that are updated from the firmware pushes the new value to the client. The problem is that the value in the parameter tab is not updated.

How to reproduce:
1. Create a firmware app that sets a parameter
2. Open the client and connect to the Crazyflie
3. Open the parameter tab and look at the value of the parameter
4. Let the firmware app update the parameter
5. Observe the parameter value in the parameter tab

Observed behavior:
The value in the parameter tab is not updated

Expected behavior:
The value in the parameter tab is updated

**Comment by knmcguire** [comment]
This might be fixed already with this PR in the crazyflie? https://github.com/bitcraze/crazyflie-firmware/pull/1193

**Comment by knmcguire** [comment]
We will try this out if this is still an issue or not. It might have been fixed but we can't be sure.

**Comment by knmcguire** [comment]
tested! and this is fixed now. Thanks!
