### ISSUE TITLE
Low FPS running cfkinect

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#66]
Low FPS has been reported even on computers with higher specs. Is there anything we can do to optimize it?

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/66
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-09-02T09:17:50.458

**Comment by evoggy** [comment]
Here's a new version out of the scripts where the Kinect is used from C++ which should increase the performance.
