### ISSUE TITLE
cfclient fails to launch in Ubuntu 22.04, but works fine in 20.04

### ISSUE THREAD

**Issue by loki980** [bitcraze/crazyflie-clients-python#662]
I've narrowed this issue down to the Ubuntu version I'm using.

Starting with a clean install of Ubuntu 20.04, I installed [crazyflie-lib-python](https://github.com/bitcraze/crazyflie-lib-python) and [crazyflie-clients-python](https://github.com/bitcraze/crazyflie-clients-python) from source using `pip install -e .` After this, `cfclient` starts up just fine.

I wiped 20.04 and installed 22.04, following the exact same procedure.  However, I'm now getting the following error:
`TypeError: addWidget(self, QWidget, stretch: int=0, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 1 has unexpected type 'CanvasBackend'`

**Comment by loki980** [comment]
This looks to be a recently broken issue with PyQT5==5.15.x

I was able to resolve it with `pip install pyqt5==5.15.0`, but I'm not sure how to fix the source to work with the latest version of PyQT5.

**Comment by krichardsson** [comment]
Qt is/has been a bit of a mystery sometimes...

What python version are you using (run `python --version`)?

If you want to force a specific version, update [`setup.py`](https://github.com/bitcraze/crazyflie-clients-python/blob/f9465d11436d9ef45cfc515fa183697427c3bfa2/setup.py#L103) and change to `'pyqt5==5.15.0'`. 
Then reinstall with `pip install -e .`

**Comment by loki980** [comment]
I'm have Python 3.10.6 installed.

**Comment by krichardsson** [comment]
Thanks!

**Comment by knmcguire** [comment]
So both me and @krichardsson have tried this out on 22.04 and 22.10, and we both have the latest version of QT, so that is not it I'm afraid. It might be another package that is interfering, so we usually advise to install the cfclient in a clean python environment. 

I'll close it for now
