### ISSUE TITLE
minimal version python client not working anymore

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/crazyflie-clients-python#704]
This discussion indicated that 3.8 or 3.9 doesn't work with the client anymore: https://github.com/orgs/bitcraze/discussions/1186

On our installation guide we say 3.8-3.12 so lets test if that is still the case:
https://www.bitcraze.io/documentation/repository/crazyflie-clients-python/master/installation/install/

**Comment by ataffanel** [comment]
At least, Python 3.9.4 on MacOS does work fine.
