### ISSUE TITLE
Fix functionality to reset the crazyflie for bootloading

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#73]
Fix the functionality that is for resetting the Crazyflie and then bootloading it. There's some old code for doing this but it's currently not working.

The reset will be done by connecting to a Crazyflie and sending a packet containing the MCU serial number. This number can be obtained from cfclient while in the bootloader.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/73
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-09-26T10:35:24.736

**Comment by evoggy** [comment]
This has been fixed while integrating the Crazyflie 2.0 code.
