### ISSUE TITLE
Add support for updating Crazyradio firmware from GUI

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#9]
Support for updating the Crazyradio firmware should be added to the GUI and to the library. Currently this can only be done using the command-line.

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/9
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-02-21T17:56:59.758

**Comment by ataffanel** [comment]
Very old ticket. Lets add it back next time we have a major release of Crazyradio.
