### ISSUE TITLE
cfclient can not connect to crazyflie. Fatal IO error

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#93]
After updating to the last mercurial version (1b45d73) the cfclient on Linux can not connect to the crazyflie.
The connections was working fine until the last update. No other changes made to the system.

Linux debian unstable
Python 2.7.6
Crazyflie 10-DOF

$ cfclient
INFO:cfclient.cfclient:Disabling STL printouts
INFO:cfclient.utils.config:Dist config read from /usr/local/cfclient/configs/config.json
INFO:cfclient.utils.config:Config file read from [/home/sebas/.local/cfclient/config.json]
INFO:cfclient.utils.config:Dist config read from /usr/local/cfclient/configs/config.json
INFO:cfclient.utils.config:Config file read from [/home/sebas/.local/cfclient/config.json]
INFO:cfclient.utils.input:Using device blacklist [(VirtualBox|VMware)]
INFO:cfclient.utils.config_manager:Parsing [PS3_Mode_1.json]
INFO:cfclient.utils.config_manager:Parsing [PS3_Mode_2.json]
INFO:cfclient.utils.config_manager:Parsing [xbox360_mode1.json]
INFO:cfclient.utils.config_manager:Parsing [Generic_OS_X.json]
INFO:cfclient.utils.config_manager:Parsing [my_mode.json]
INFO:cfclient.utils.config_manager:Parsing [xbox360_mode1_linux.json]
INFO:cfclient.utils.config_manager:Parsing [PS3_Mode_1.json]
INFO:cfclient.utils.config_manager:Parsing [PS3_Mode_2.json]
INFO:cfclient.utils.config_manager:Parsing [xbox360_mode1.json]
INFO:cfclient.utils.config_manager:Parsing [Generic_OS_X.json]
INFO:cfclient.utils.config_manager:Parsing [my_mode.json]
INFO:cfclient.utils.config_manager:Parsing [xbox360_mode1_linux.json]
INFO:cfclient.ui.tabs.FlightTab:Changed flightmode to Advanced
INFO:cfclient.ui.tabs.FlightTab:Changed flightmode to Advanced
INFO:cfclient.ui.tabs.FlightTab:Clientside X-mode enabled: True
INFO:cflib.crazyflie:Callback->Connection initialized[radio://0/1/250K]
INFO:cflib.crazyflie:We are connected[radio://0/1/250K], request connection setup
INFO:cflib.crazyflie:Callback->Connected to [radio://0/1/250K]
ERROR:cflib.crazyflie.toc:Got packet that was not on TOC channel, TOC fetch will probably not succeed
INFO:cflib.crazyflie.toc:TOC for port [5] found in cache
INFO:cflib.crazyflie:Log TOC finished updating
INFO:cflib.crazyflie.toc:TOC for port [2] found in cache
INFO:cflib.crazyflie:Param TOC finished updating
INFO:cflib.crazyflie:Callback->Connection setup finished [radio://0/1/250K]
INFO:cfclient.utils.logconfigreader:Parsing [stabilizer.json]
INFO:cflib.crazyflie.log:Have successfully started logging for block=2
INFO:cflib.crazyflie.log:Have successfully started logging for block=3
INFO:cflib.crazyflie.log:Have successfully started logging for block=4
INFO:cflib.crazyflie.log:Have successfully started logging for block=5
INFO:cfclient.ui.tabs.FlightTab:[imu_sensors.HMC5883L]: 1
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
cfclient: Fatal IO error: client killed
python: ../../src/xcb_io.c:179: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
Aborted

Until the line "INFO:cfclient.ui.tabs.FlightTab:Clientside X-mode enabled: True" it is the cfclient startup. I press Connect and select the crazyflie. Then I get this error.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/93
- Originally Reported By: [el draco](http://bitbucket.org/eldraco2000)
- Originally Created At: 2014-01-01T20:04:38.710

**Comment by evoggy** [comment]
This is old and probably due to issues outside the client.
