### ISSUE TITLE
Make API/client work with Python3

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#96]
---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/96
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2014-01-08T15:14:05.317

**Comment by qubitter** [comment]
PLEASE DO THIS!!! I have been through so many incompatibility issues!

**Comment by evoggy** [comment]
The client has been moved to Python 3 and the cflib has dual compatibility with 2.7+ and 3+. The main commit for moving to Python 3 was 0f6634e0a11039227459cfa04c95b39c42144afb and for regaining 2.7 compatibility for the cflib 0239f7ad9bc0c796731bc32f49eb6f71704c84cf

**Comment by hawanna** [comment]
Hello!

 

New message, please read <http://phpproject.ru.fstest.ru/house.php?p>

 

haw@xdstudios.de
