### ISSUE TITLE
Automatically generate CREDITS.txt and pick up in UI

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#98]
---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/98
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2014-01-09T15:31:20.355

**Comment by krichardsson** [comment]
List of contributors are added to the release notes in github
